README.md
package.json

update email for Noah Katzman
update badges to be correct

Updating Contributors and README

---

lib/registerPlugins.js
package.json
test/lib/registerPlugins.test.js

Will include changes from https://github.com/screwdriver-cd/plugin-pipelines/pull/1

Register screwdriver-plugin-pipelines

---

Dockerfile
bin/server
package.json

This allows us to run this in Docker as well as auto-use the in-memory datastore

Adding Dockerfile and using in-memory-datastore

---

lib/registerPlugins.js
package.json
test/lib/registerPlugins.test.js

Register the platforms plugin so we can use it in aws-api

Register platforms plugin

---

kubernetes/api_deployment.yaml

- Also switched to :LATEST tag for the container

Mounting the IMDB EBS volume into the container for persistence

---

bin/server

This is waiting on the IMDB change to support loading from a file.
https://github.com/screwdriver-cd/screwdriver-datastore-imdb/pull/8

Loading from mounted data volume

---

kubernetes/api_deployment.yaml

Didn't have the correct volume in the previous PR

changing the volume to the correct one

---

bin/README.md
bin/server

README about how to configure and run the `bin/server` locally

Adding README for running/configuring locally

---

kubernetes/api_deployment.yaml

Use new volume

---

.dockerignore
.gitignore
Dockerfile
README.md
bin/server
config/custom-environment-variables.yaml
config/default.yaml
kubernetes/api_deployment.yaml
package.json

- Uses a config manager
- Can set settings via a config.yaml OR environment variables
- Simplifies server startup

Migrating to a more local-friendly setup

---

kubernetes/api_deployment.yaml

Remove apikey from volume mounts

---

package.json

We rely on this in the `./bin/server` script
This PR is adding in K8s as a dependency

Adding in K8s

---

README.md
package.json

Renaming the GitHub repository to `screwdriver`

---

README.md

New Wercker build and fixing the link to Docker

Fixing links to Docker and Wercker

---

config/custom-environment-variables.yaml
config/default.yaml
kubernetes/api_deployment.yaml
package.json

This adds the DynamoDB datastore and an ability to configure it.

Adding support for using DynamoDB as a datastore

---

README.md
kubernetes/api_deployment.yaml

https://hub.docker.com/r/screwdrivercd/screwdriver/

Renaming to new docker image

---

bin/server
package.json
plugins/login/index.js
plugins/login/login.js
plugins/pipelines/create.js
plugins/platforms/create.js
test/plugins/builds.test.js
test/plugins/jobs.test.js
test/plugins/login.test.js
test/plugins/pipelines.test.js
test/plugins/platforms.test.js

- Save token after logged in
- Use generateId
- Use seal/unseal methods that just got added

Save token after logged in

---

plugins/login/login.js
test/plugins/login.test.js

Fix bug for login

---

plugins/builds/list.js
plugins/jobs/list.js
plugins/pipelines/list.js
test/plugins/builds.test.js
test/plugins/jobs.test.js
test/plugins/pipelines.test.js

Because i broke stuff, here's a fix that calls the model.list functions with the correct values

Calling list with correct parameters

---

plugins/pipelines/README.md
plugins/pipelines/index.js
test/plugins/pipelines.test.js

Need to add the password when creating a pipeline

Pass password into pipeline create

---

plugins/pipelines/create.js

Making error message pretty for when user is not an admin of the repo

Fix unauthorized error message

---

README.md
package.json
wercker.yml

Codacy was more confusing than helpful.  Just showing coverage now.
Also added synk vulnerability checking

Adding Coveralls and Snyk (removing Codacy)

---

package.json
plugins/pipelines/create.js
test/plugins/pipelines.test.js

Formatting scmUrl before calling get and create
Resolves https://github.com/screwdriver-cd/screwdriver/issues/59

Format scmurl for pipeline create

---

plugins/pipelines/create.js
test/plugins/pipelines.test.js

Fix bug from https://github.com/screwdriver-cd/screwdriver/pull/61
Did not merge in the formatted scmUrl

Hoek applyToDefaults the correct scmUrl

---

lib/credentials.js
lib/server.js
plugins/builds/create.js
plugins/builds/stream.js
plugins/builds/update.js
plugins/jobs/update.js
plugins/login/index.js
plugins/login/login.js
plugins/pipelines/create.js
plugins/pipelines/update.js
test/lib/server.test.js
test/plugins/builds.test.js
test/plugins/jobs.test.js
test/plugins/pipelines.test.js

Also added pretty-printing of errors (no more 500 with no context).

Refactoring Credentials and adding Scope

---

plugins/github.js
test/plugins/github.test.js

When a PR is updated with another commit, it sends a `synchronize` event. When that event occurs, we want a new build to be started for that commit. This PR aims to include that functionality.

Synchronize PR

---

package.json
plugins/webhooks/build.js
plugins/webhooks/github.js
plugins/webhooks/index.js
test/plugins/webhooks/build.test.js
test/plugins/webhooks/github.test.js

This adds a new webhook for the launcher to update the meta, status, and stopTime.
Depends on https://github.com/screwdriver-cd/data-schema/pull/20

Adding a /webhooks/build

---

bin/server
package.json
plugins/builds/create.js
plugins/builds/index.js
plugins/pipelines/create.js
plugins/webhooks/build.js
plugins/webhooks/github.js
plugins/webhooks/index.js
test/plugins/builds.test.js
test/plugins/webhooks/github.test.js

Using the new models, Build create now takes in another param called config.username: https://github.com/screwdriver-cd/models/blob/master/lib/build.js#L95
Build model constructor now takes in password.

Build create passes username

---

features/authorization.feature
features/git-flow.feature
features/secrets.feature
features/workflow.feature
package.json

Adding the feature files for:
- Authorization
- Git Flow (https://github.com/screwdriver-cd/screwdriver/issues/79)
- Workflow
- Secrets
Also sets package.json to require node 4+

Adding some feature files and pinning to engine >= 4

---

bin/server
lib/server.js
package.json
plugins/builds/README.md
plugins/builds/create.js
plugins/builds/get.js
plugins/builds/list.js
plugins/builds/stream.js
plugins/builds/update.js
plugins/jobs/README.md
plugins/jobs/get.js
plugins/jobs/list.js
plugins/jobs/update.js
plugins/login/login.js
plugins/pipelines/README.md
plugins/pipelines/create.js
plugins/pipelines/get.js
plugins/pipelines/list.js
plugins/pipelines/update.js
plugins/webhooks/build.js
plugins/webhooks/github.js
test/lib/server.test.js
test/plugins/builds.test.js
test/plugins/jobs.test.js
test/plugins/login.test.js
test/plugins/pipelines.test.js
test/plugins/webhooks/build.test.js
test/plugins/webhooks/github.test.js

Refactored api plugins to utilize new models/factories.

Use new models in api

---

bin/server

https://github.com/screwdriver-cd/models/pull/47 
Gives password param to user models for encryption of tokens.

Add password param to UserFactory construction

---

config/custom-environment-variables.yaml
config/default.yaml

This allows the launcher version to be overridden via an environment variable

Configurable Launcher Version

---

package.json

Use model v8

---

bin/server
config/default.yaml
package.json
plugins/webhooks/build.js
test/plugins/data/build.json
test/plugins/data/builds.json
test/plugins/data/pipeline.json
test/plugins/data/pipelines.json
test/plugins/webhooks/build.test.js

- Pull in new datastore dynamo and models, which uses the new schema to validate. 
- Pull in scmPlugin to pass into model factories

Add scmPlugin and fix Endtime

---

plugins/webhooks/github.js
test/plugins/webhooks/github.test.js

Jobs need a list of containers for builds to look up. Give a default for now.

Give a default container list to PRs

---

features/step_definitions/server.js
wercker.yml

- Added INSTANCE environment variable in Wercker
- Add run Cucumber test step in Wercker yaml

Run Cucumber tests in wercker

---

plugins/login/index.js
plugins/login/login.js
test/plugins/builds.test.js
test/plugins/jobs.test.js
test/plugins/login.test.js
test/plugins/pipelines.test.js
test/plugins/webhooks/github.test.js

======== Coverage summary ========
Statements   : 100% ( 435/435 ), 3 ignored
Branches     : 96.67% ( 58/60 ), 2 ignored
Functions    : 100% ( 7/7 )
Lines        : 100% ( 414/414 )

Add tests for coverage

---

config/default.yaml

Adding documentation for Prefix support

---

plugins/webhooks/github.js
test/plugins/data/github.push.json
test/plugins/webhooks/github.test.js

This will trigger the main job on push to the branch.

Adding push support

---

package.json

Pulling in new scm-github

---

config/default.yaml
plugins/login/index.js
plugins/login/login.js
test/plugins/login.test.js

This enables other people deploying this to be able to use it :)

Move whitelist to config file

---

lib/server.js
package.json

More details about the log and l3l

Adding more logging around failures and adding l3l support

---

bin/server
config/default.yaml
lib/server.js

Add a CORS configuration to the server globally that applies to all routes.

Add cors support for all routes

---

package.json
plugins/builds/create.js
plugins/builds/index.js
plugins/builds/steps/get.js
plugins/builds/steps/logs.js
plugins/builds/steps/update.js
test/plugins/builds.test.js
test/plugins/data/build.json
test/plugins/data/builds.json

Depends on https://github.com/screwdriver-cd/data-schema/pull/34
Feature: https://github.com/screwdriver-cd/screwdriver/issues/135

Adding steps and a shell of logs

---

config/custom-environment-variables.yaml

So we can edit the version to use

Adding environment override

---

config/default.yaml

Expose the x-more-data header for CORS

---

config/custom-environment-variables.yaml
config/default.yaml
package.json
test/plugins/data/validator.output.json

Pulls in new change from https://github.com/screwdriver-cd/executor-k8s/pull/36

Using new executor with Launcher docker image

---

README.md
bin/server
lib/registerPlugins.js
lib/server.js
plugins/secrets/README.md
plugins/secrets/create.js
plugins/secrets/index.js
test/lib/registerPlugins.test.js
test/plugins/data/secret.json
test/plugins/data/validator.output.json
test/plugins/secrets.test.js

- Add upload secret API endpoint
- Add README.md
Feature: https://github.com/screwdriver-cd/screwdriver/issues/148

Add secret upload api

---

config/custom-environment-variables.yaml
config/default.yaml

Specifically to use HTTPS and the URL for the UI

Exposing more environment variables to customize

---

plugins/pipelines/index.js
plugins/pipelines/listSecrets.js
test/plugins/data/secrets.json
test/plugins/pipelines.test.js

Feature #148 
Fixes https://github.com/screwdriver-cd/screwdriver/issues/161

Add endpoint for getting pipeline's secrets

---

package.json
plugins/builds/index.js
plugins/builds/listSecrets.js
plugins/pipelines/listJobs.js
test/plugins/builds.test.js

Blocked on https://github.com/screwdriver-cd/models/pull/95
Feature https://github.com/screwdriver-cd/screwdriver/issues/148
Fixes https://github.com/screwdriver-cd/screwdriver/issues/163

Adding secrets to the build API

---

bin/server
config/default.yaml
lib/server.js
test/lib/server.test.js

Instead of having to change the CORS AND the ecosystem.ui config, I'm combining them.

Move CORS out of config and just use the ecosystem.ui value

---

ci/publish
screwdriver.yaml

This adds a new secret for triggering our Docker Hub rebuild of `latest`

Trigger Docker Hub on complete

---

plugins/builds/update.js
test/plugins/builds.test.js

When a build has succeeded -- and is updated as such -- we look up the next build in the workflow and trigger that build prior to returning.

Build triggers next job in the workflow

---

package.json
plugins/pipelines/listJobs.js
test/plugins/jobs.test.js
test/plugins/pipelines.test.js

This uses https://github.com/screwdriver-cd/models/pull/99. That needs to be merged before this PR
Solves https://github.com/screwdriver-cd/screwdriver/issues/188

[5] List active jobs

---

test/plugins/data/pipeline.json
test/plugins/data/pipelines.json

Just removing from the mock.  This is currently breaking the build.

Config URL is removed, no need to have it in the mocks anymore

---

screwdriver.yaml

- waits for docker hub to build the image
- deploys that new image to k8s
- runs "tests"
_note: we don't have a beta environment, yet_

Trying to deploy to our beta environment

---

screwdriver.yaml

This will check for duplicate screwdriver- packages

Adding a duplicate package check

---

screwdriver.yaml

Until we get a beta environment, let's deploy to prod

Switch to deploying to Prod for now

---

features/step_definitions/git-flow.js
features/step_definitions/server.js
lib/registerPlugins.js
plugins/auth/login.js
test/lib/registerPlugins.test.js

Blocked by https://github.com/screwdriver-cd/launcher/pull/79

Switching to V4 instead of V3

---

package.json
plugins/secrets/index.js
plugins/secrets/remove.js
test/plugins/secrets.test.js

Needs https://github.com/screwdriver-cd/datastore-dynamodb/pulls
Related to https://github.com/screwdriver-cd/models/issues/105

[remove:4] Delete a secret route

---

config/default.yaml

whitelist build bot

---

plugins/pipelines/index.js
plugins/pipelines/remove.js
test/plugins/pipelines.test.js

- Adding a route for removing a pipeline 
- Refactor some code in test
- Blocked by https://github.com/screwdriver-cd/models/pull/109
- Relates to https://github.com/screwdriver-cd/models/issues/105

[2] Add route for remove a pipeline

---

plugins/builds/README.md
plugins/pipelines/README.md

Resolves https://github.com/screwdriver-cd/screwdriver/issues/180
Resolves https://github.com/screwdriver-cd/screwdriver/issues/228

Update READMEs for build create and pipeline remove

---

plugins/pipelines/remove.js
plugins/secrets/remove.js
test/plugins/builds.test.js
test/plugins/jobs.test.js
test/plugins/pipelines.test.js
test/plugins/secrets.test.js
test/plugins/validator.test.js

- `200` expects some content there, so we should return `204` instead
- Update old tests to promise form

DELETE should return 204 because of no content

---

.func_config.json
README.md
features/git-flow.feature
features/step_definitions/git-flow.js
features/step_definitions/secrets.js
features/support/before-hook.js
features/support/github.js
features/support/sdapi.js
package.json
screwdriver.yaml

Rewritten the functional tests for the Git Flow feature. This asserts the scenarios described in the `git-flow.feature` file.

Functional Tests for Git-Flow Feature

---

features/step_definitions/git-flow.js

Master branch current failing:
https://cd.screwdriver.cd/pipelines/27cec39c9baea6cf64c684479115300d22039b2a/build/3a0dfd510665887935fa7e6f645c0b92aef84e1a
It might take some time to create a file.

Add timeout for createFile in git-flow

---

package.json

Since @FenrirUnbound was kind enough to fix the IMDB class, we can import it again.

Adding IMDB back into the mix

---

README.md

Missing spaces around badge

---

features/authorization.feature
features/step_definitions/authorization.js
package.json

We only have an access key working for the user Calvin at the moment, so adding a fully working scenario for that user here.
**Not sure where pipeline creation should happen.

Add working auth tests for user Calvin

---

README.md
config/custom-environment-variables.yaml
config/default.yaml
package.json

Not much here, just exposing the right options

Adding Sequelize support

---

package.json

This is for Greenkeeper to leave us alone

Ignore all screwdriver packages, we know when to upgrade these.

---

plugins/auth/login.js
test/plugins/auth.test.js

Bug fix: login never updates token

---

config/default.yaml

Just to poke around and kick the tires

requesting access to tonytamsf @ Splunk

---

config/default.yaml

Give me the accesses

---

README.md
config/default.yaml
package.json

Rename s3m to Docker

---

config/custom-environment-variables.yaml

Not a fan of the name, but meh

Renaming environment variables as well

---

README.md
in-a-box.py

Adding a quickstart to getting Screwdriver up and running.

Adding Quickstart "in-a-box.py"

---

README.md

Just adding OS X and Docker as required

Updating requirements for in-a-box

---

screwdriver.yaml

This didn't work, even though it does in bash.  Sorry.

Fix variable setting

---

package.json

Let's add this back until we figure out https://github.com/screwdriver-cd/screwdriver/issues/308. 
Otherwise the pipeline is blocked and no change can go out.

Add back timeout

---

features/step_definitions/git-flow.js
features/support/github.js
package.json

Upgrading a couple packages:
- [github@5](https://github.com/mikedeboer/node-github/blob/master/CHANGELOG.md#500)
- [chai-as-promised@6](https://github.com/domenic/chai-as-promised/releases/tag/v6.0.0)
- [nock@9](https://github.com/node-nock/nock/blob/2a1bc2d68cb5e36bc4a1501b5cbe9fe3cbcd576f/CHANGELOG.md#900--2016-10-23)
- mockery@2

Upgrading a couple packages

---

README.md
config/custom-environment-variables.yaml
config/default.yaml

Allow user to configure bitbucket
Relates to https://github.com/screwdriver-cd/screwdriver/issues/302

Allow bitbucket in config

---

features/event.feature

Add feature file for events 
Relates to https://github.com/screwdriver-cd/screwdriver/issues/221

Add event feature file

---

test/plugins/pipelines.test.js
test/plugins/secrets.test.js
test/plugins/webhooks/github.test.js

- Fixed to adapt to new eslint rules

Fix eslint rules

---

plugins/auth/index.js

- Allow /webhooks to be accessed without auth

Allow /webhooks to be accessed without auth

---

plugins/pipelines/index.js
plugins/pipelines/listEvents.js
test/plugins/data/events.json
test/plugins/pipelines.test.js

Add `pipeline/:id/events` route
This will be used by the UI to get all the pipeline events of a pipeline

Add listEvents for pipeline

---

plugins/builds/update.js
test/plugins/builds.test.js

The triggered build should have an eventId as well

Add eventId when triggering next job

---

config/custom-environment-variables.yaml
config/default.yaml

They should be inside `kubernetes`: https://github.com/screwdriver-cd/executor-k8s/blob/master/index.js#L19-L22
Relates to https://github.com/screwdriver-cd/screwdriver/issues/347

Pass in kubernetes config correctly

---

config/custom-environment-variables.yaml

Allow configuring jobs namespace for k8s

---

plugins/webhooks/index.js
test/plugins/webhooks/index.test.js

- Modify cause msg for pr and push events

Modify cause msg for pr and push events

---

features/authorization.feature
features/events.feature
features/secrets.feature
features/step_definitions/authorization.js
features/step_definitions/events.js
features/step_definitions/git-flow.js
features/step_definitions/secrets.js
features/support/github.js
features/workflow.feature
package.json

- Add @ignore tags to workflow, secret, and auth feature files
- Add a mergePullRequest method to the Github helper
- Get pipelineId when pipeline already exists
- Make timeout into a constant variable
Related to https://github.com/screwdriver-cd/screwdriver/issues/221

Add cucumber test for events

---

plugins/pipelines/create.js
plugins/secrets/create.js
test/plugins/pipelines.test.js
test/plugins/secrets.test.js

Resolves https://github.com/screwdriver-cd/screwdriver/issues/284

Prevent creating duplicate secrets

---

features/step_definitions/git-flow.js

Increase to 2 minutes
Workaround until https://github.com/screwdriver-cd/screwdriver/issues/358 is resolved

Increase git-flow timeout

---

package.json

Need this before we pull in the new launcher to use get checkout commands

Update to models v18

---

plugins/builds/steps/logs.js
test/plugins/builds.test.js

Currently, when we load a step that has 5k of log lines, the API will make 50 sequential calls to the store.  This takes both time and memory to store the results.  On the UI, we don't see anything happen for 10-20 seconds until BAM logs.
This pull request limits the pages we load so that the API doesn't run out of memory and the user sees progressive loading.  Overall time should remain the same.

Limit the number of log pages the API returns to reduce fetch time and memory usage

---

package.json

Uses new fix from bookend. https://github.com/screwdriver-cd/build-bookend/pull/3

Use new patch that fixes promise resolving

---

package.json

fix: ensure pick up the right models

---

plugins/webhooks/index.js
test/plugins/webhooks/index.test.js

generateId doesn't exist anymore. Now get the job's id by going through the pipeline's jobs and find the right job record and get its ID.

fix: generateId does not exist anymore

---

plugins/webhooks/index.js
test/plugins/webhooks/index.test.js

- For PR sync event, the job already exists, so we do an `update` instead of a `create`
- Revert https://github.com/screwdriver-cd/screwdriver/pull/407/commits/aa33dff74ee523b214d2fb734d41a8b01f2086b5 since it was meant to archive the old PR job, and create another PR job. But that doesn't really make sense.
Related: https://github.com/screwdriver-cd/screwdriver/issues/399

fix(399): update job for PR sync

---

config/custom-environment-variables.yaml

- add prefix for executor containers

feat: add prefix for executor containers

---

features/step_definitions/authorization.js
features/step_definitions/events.js
features/step_definitions/secrets.js

fix: Increase all the timeouts in functional tests

---

config/default.yaml

Need to add our new intern to the whitelist

fix: Whitelist Jerry

---

in-a-box.py

modify some parts of this issue https://github.com/screwdriver-cd/screwdriver/issues/321
> Small:
>
> - [x] Do requirement checking (docker, docker-compose, openssl)
> - [x] Tell user what to put in 'Homepage URL' for GitHub OAuth
> - [x] Warn user about Webhooks/PRs not working
> - [x] Perform a pull before starting to get latest stable images
How does it look?

improve in-a-box

---

config/custom-environment-variables.yaml

Small changes to allow users to set setup and teardown plugins as environment variables.

feat: Made setup and teardown plugins configurable

---

config/custom-environment-variables.yaml

Fix to this: https://github.com/screwdriver-cd/screwdriver/pull/437
based on Stjohn's comment

fix: Make bookends_setup & bookends_teardown array

---

config/default.yaml

Welcoming our newest addition to the team :)

Add Reetika to whitelist

---

features/metadata.feature

Add Cucumber feature file of metadata.
How does it look?
Related: #293

feat: Add metadata feature file

---

features/executor-queue.feature
test/plugins/data/validator.output.json

Add cucumber feature file of executor queue.
How does it look?
Related:#431

feat(431): Add executor queue feature file

---

test/lib/server.test.js

In the past, there was additional code that was introduced without an accompanying test case. Specifically it did not cover a branch case, but preserved the major functionality of the module. 
Recently our Pull Requests now include a check for drops in code quality. This check flags a PR for drops because of this missing branch, even if the new PR does not affect the `lib/server.js` file. This is negatively affecting the team's trust in the check, as well as creating a soft-block on the PR.
This change aims to create a test case that covers the missing branch.
* PR #130

chore: test for missing branch

---

in-a-box.py

Enable UI talk to Store with in-a-box so that UI can query the ARTIFACTS 
Related to https://github.com/screwdriver-cd/screwdriver/issues/468

feat(468): enable ui talk to store with in-a-box

---

features/data/invalid-template.yaml
features/data/valid-template.yaml
features/step_definitions/templates.js
features/templates.feature
package.json

Functional testing helps us assert that new functionality works as expected, in addition to ensuring that it does not negatively affect other features. For the template validation feature, we want to include a set of test scenarios that represent how a user would utilize the functionality.
A cucumber test to cover the scenarios for a template owner to validate their template.
* Contributes to screwdriver-cd/screwdriver#470 
* Extended form PR screwdriver-cd/screwdriver#480
EDIT 1: Included the step definitions along with the feature file

feat(470): cucumber tests for templates

---

features/metadata.feature
features/step_definitions/metadata.js
features/step_definitions/secrets.js

Add cucumber test for metadata.feature.
Repository for testing is [here](https://github.com/wahapo/functional-metadata). I hope it will be relocated to screwdriver-cd-test Organization.

feat: Add cucumber test for metadata

---

features/templates.feature

- Feature file for templates
Related: https://github.com/screwdriver-cd/screwdriver/issues/470

feat(470): Add feature file for templates

---

features/step_definitions/metadata.js

feat: Fill in repoOrg in metacucumber

---

features/metadata.feature

I forgot to include it in the previous fix.

feat: respect cucumber test for metadata

---

features/sd-step.feature

There is no functional test for shared steps. At first, this PR adds feature file for shared steps.
Related: https://github.com/screwdriver-cd/screwdriver/issues/300

feat(300): add feature file for shared steps

---

test/plugins/data/validator.output.json

parser now automatically generates alwaysRun flag

fix: validator test now includes alwaysRun

---

test/plugins/data/validator.output.json

Revert alwaysRun feature
Related: https://github.com/screwdriver-cd/screwdriver/issues/473

fix: rollback alwaysRun

---

config/default.yaml

- Add Ian Fox
- Remove inactive contributors

fix: Add Ian Fox to whitelist, remove some people

---

bin/server
lib/server.js
package.json
plugins/auth/index.js
test/plugins/auth.test.js

* Users can trade their access token for a 12h JWT
Related to https://github.com/screwdriver-cd/screwdriver/issues/524

feat: Authenticate with API tokens

---

README.md
lib/registerPlugins.js
package.json
plugins/tokens/README.md
plugins/tokens/create.js
plugins/tokens/index.js
test/lib/registerPlugins.test.js
test/plugins/data/token.json
test/plugins/tokens.test.js

* `POST`ing to /tokens will create a new token for the logged in user.

feat: Add token CREATE route

---

plugins/tokens/README.md
plugins/tokens/index.js
plugins/tokens/list.js
test/plugins/tokens.test.js

* `GET /tokens` will return a list of all tokens belonging to the current user

User tokens

---

plugins/tokens/README.md
plugins/tokens/index.js
plugins/tokens/remove.js
test/plugins/tokens.test.js

* Deleting a token will revoke it, so that it can't be used to authenticate any more

feat(tokens): Add token DELETE route

---

plugins/tokens/README.md
plugins/tokens/index.js
plugins/tokens/update.js
test/plugins/tokens.test.js

* `POST` requests to `/tokens/{id}` will update the specified token
* Name can't be changed such that it conflicts with another token

feat(tokens): Add token UPDATE route

---

package.json

The bug is documented here: https://github.com/sequelize/sequelize/issues/7758

fix(545): partial revert of #586 which pulled in a buggy version of sequelize

---

features/api-token.feature
features/step_definitions/api-token.js

Adding the acceptance test for revoking a token.

test(tokens): Token DELETE acceptance test

---

features/api-token.feature
features/step_definitions/api-token.js
features/support/before-hook.js
features/support/sdapi.js
plugins/tokens/refresh.js
plugins/tokens/update.js

* fix some style mistakes
* calling the `refresh` returns things other than 500 now
* added acceptance test for `refresh` endpoint

test(tokens): Token refresh acceptance test

---

test/plugins/data/validator.output.json

Related to: https://github.com/screwdriver-cd/screwdriver/issues/580

fix(580): update api tests to check for annotations

---

config/default.yaml

I just started.
I want to add myself to the whitelist

fix: Add Joel Sequeira to whitelist

---

config/default.yaml

More teams want to pilot our hosted solution.
Add a few more users:
- [aressem](https://github.com/aressem)
- [gjoranv2](https://github.com/gjoranv2)
- [bjorncs](https://github.com/bjorncs)
Removed in-active contributors.  Cleaned-up admin list.

feat: Adding more pilots to whitelist

---

config/default.yaml

- Add [jithin1987](https://github.com/jithin1987)

fix(): Add Jithin to whitelist

---

test/plugins/data/pipeline.json
test/plugins/data/pipelines.json

Reverts screwdriver-cd/screwdriver#644
There are a lot more places need to be changed. So just wait for all scmContext works to be done to do this.

Revert "fix: fix the unit tests to have scmContext in pipelines"

---

CONTRIBUTING.md

I found contributiong documentation url is wrong :smile:

docs: url is wrong

---

plugins/collections/README.md
plugins/collections/index.js
plugins/collections/remove.js
test/plugins/collections.test.js

For collections, we need to be able to delete a collection.
This PR adds a REMOVE route for collections so that you can delete a collection.
Issue: #523

feat(523): Add REMOVE route for Collections

---

plugins/webhooks/index.js
test/plugins/webhooks/index.test.js

Reverts screwdriver-cd/screwdriver#673

fix:Revert "fix: Revert Skip builds when commit message includes [skip ci]"

---

features/scripts/create-test-user.js

Cucumber was running `createTestUser` as part of the setup for functional tests.
Move the script into a function so that cucumber doesn't run it.

fix(tests): move createTestUser into a function

---

package.json

fix: pull in new executor-queue

---

in-a-box.py

fix: SCM_SETTINGS env

---

features/collections.feature
features/step_definitions/collection.js
plugins/collections/create.js
test/plugins/collections.test.js

Add functional tests for collections
Issue: #523

test(collections): Add functional tests for collections

---

config/custom-environment-variables.yaml
config/default.yaml
lib/server.js
test/lib/server.test.js

Allows configuring CORS origins 
This will allow user to configure which all Origins can connect to SD API via Ajax.

feat: allow configuring cors origins

---

features/step_definitions/collection.js

Currently getting: `Error: function timed out after 5000 milliseconds`
We usually add longer timeouts since sometimes these can be quite slow

fix: add timeout to collections func tests

---

screwdriver.yaml

Related to https://github.com/screwdriver-cd/screwdriver/pull/749

fix: Update env var names

---

plugins/builds/create.js
test/plugins/builds.test.js

Should fix this: https://github.com/screwdriver-cd/screwdriver/issues/689

fix: restart PR from personal fork

---

config/default.yaml

docs: add andy wick

---

plugins/builds/update.js
test/plugins/builds.test.js

fix triggerFactory.list config format
https://github.com/screwdriver-cd/models/blob/master/lib/baseFactory.js#L109

fix: fix triggerFactory.list config format

---

lib/server.js
test/lib/server.test.js

add triggerFactory to server.app

fix: add triggerFactory to server

---

features/step_definitions/sd-step.js

remove space in checkoutUrl for sd-step test

fix: remove space in checkoutUrl for sd-step test

---

features/support/world.js

fix: bump maxAttempts to fix sd-step test

---

features/trigger.feature

Adds a feature for for trigger(rebuild_on) functionality 
https://github.com/screwdriver-cd/screwdriver/issues/768

feat: add feature for trigger

---

config/custom-environment-variables.yaml
config/default.yaml

Related to PR #828. This PR modifies config name added in PR #828 to reflect changes in related `executor-k8s-vm` PR https://github.com/screwdriver-cd/executor-k8s-vm/pull/19

fix(827) update config name

---

screwdriver.yaml

Use new workflow syntax and Also add dependency on executor-k8s-vm
Pull in new version of executor-k8s-vm and update workflow
Pulls in https://github.com/screwdriver-cd/executor-k8s-vm/pull/19

feat: Move to new workflow

---

config/custom-environment-variables.yaml
config/default.yaml

This provides a placeholder for setting sequalize connection pool config See http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor for options and default values

fix: add config for sequalize connection pool

---

plugins/auth/index.js

fix: change uuid to random instead of timestamp

---

features/step_definitions/git-flow.js

oops, update the wrong number in the previous PR

fix: update the wait time number

---

plugins/builds/steps/logs.js
test/plugins/builds.test.js

Addresses https://github.com/screwdriver-cd/screwdriver/issues/858

 fix(858): Put get logs behind auth and pass Bearer token to store

---

.gitignore
bin/server
plugins/builds/artifacts/get.js
plugins/builds/index.js
test/plugins/builds.test.js

Add a route which issues a redirect to store with a temporary JWT to fetch artifacts.
@petey @stjohnjohnson

fix: add route to fetch build artifact

---

config/default.yaml

fix: Whitelist manolama

---

config/default.yaml

This will not be set if not defined.

fix: remove default value for jwtEnv

---

config/default.yaml

per @awick's request. She is a member of his team.

fix: adding 31453 to whitelist

---

config/default.yaml

Fix(config): Add catto to whitelist

---

plugins/webhooks/index.js
test/plugins/webhooks.test.js

This will let pipeline owners restrict which PRs should be automatically
started.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/579

feat(579): Read pipeline-level annotation for auto-start

---

screwdriver.yaml

fix: Echo docker tag

---

features/step_definitions/authorization.js

bug introduced in this PR: https://github.com/screwdriver-cd/screwdriver/commit/d82f769d47a6fc2e71df8d82f14d2b6dffb300eb

fix: fix statusCode check for func tests

---

design/workflow.md
features/step_definitions/metadata.js
features/support/world.js

The order of jobs is not the same anymore, we need to find the id based on name.

fix: fix functional tests for metadata

---

config/custom-environment-variables.yaml

Related to https://github.com/screwdriver-cd/screwdriver/issues/545

fix: Add timeout env vars

---

lib/server.js
test/lib/server.test.js

Need to pass this in for buildPeriodically
Related: https://github.com/screwdriver-cd/screwdriver/issues/688

fix: pass apiuri

---

features/step_definitions/sd-step.js

To temporarily unblock pipeline

fix: increase timeout

---

features/step_definitions/git-flow.js

fix: wait longer before searching for new build

---

plugins/builds/token.js
test/plugins/builds.test.js

Need to allow `BLOCKED` build to proceed

fix: allow BLOCKED status to do exchange token

---

design/commands.md

Actual output and design doc's output are difference.
Fix to actual output on design doc.

fix(docs): update command publish output in design doc

---

plugins/builds/update.js
test/plugins/builds.test.js

fix: update status message

---

design/workflow.md

SCM Branch-specific design is updated based on https://github.com/screwdriver-cd/screwdriver/issues/1082
- Add `~pr:` pattern
- Rename section name to `Branch filtering` from `SCM Branch-specific jobs` with [this discussion](https://github.com/screwdriver-cd/guide/pull/206#discussion_r197592313)
- Add description about workflow configuration in Branch filtering section
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/1082
- Related PR: https://github.com/screwdriver-cd/guide/pull/206

doc(1082): [small] update Branch filtering

---

features/step_definitions/git-flow.js

In the gitflow test, we always wait few seconds before searchForBuild.
This has lengthened testing time.
In serchForBuild, it retry search if the search result is none.
https://github.com/screwdriver-cd/screwdriver/blob/master/features/support/sdapi.js#L123
Therefore, I added commit sha to search config to find exact build which is caused by that commit sha.
And retry serchForBuild until the build is created.
Remove promiseToWait before searchForBuild, add sha to search config.

fix: [small]Refactoring feature test

---

package.json

Will test this out in beta first.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1042

feat(1042): Pull in latest scm-github with octokit

---

package.json

update `scm-github` package.
includes the following fixes.
- https://github.com/screwdriver-cd/scm-github/pull/97
- https://github.com/screwdriver-cd/scm-github/pull/96
- https://www.npmjs.com/package/screwdriver-scm-github

fix: [small] update scm-github.

---

package.json

update `scm-github` package.
includes the following fixes.
- https://github.com/screwdriver-cd/scm-github/pull/99
- https://www.npmjs.com/package/screwdriver-scm-github

fix: [small] pull in the latest scm-github.

---

config/custom-environment-variables.yaml
config/default.yaml

When using active/active database cluster and do multi-node writing, dead lock will happen. 
So I want to make it possible to use retry.
Add retry settings to a config file.
- [Multi-node writing and Unexpected deadlocks](https://www.percona.com/blog/2012/08/17/percona-xtradb-cluster-multi-node-writing-and-unexpected-deadlocks/)

feat: [small] able to add sequelize retry

---

config/custom-environment-variables.yaml
config/default.yaml

Fixing indentation to be consistent for config yaml files
Related to https://github.com/screwdriver-cd/screwdriver/issues/1223

fix(1223): Make yaml indentation consistent for config folder

---

config/custom-environment-variables.yaml

Ran it through a yaml validator and missed this spot.
Related to https://github.com/screwdriver-cd/screwdriver/pull/1239

fix(1223): Fix yaml again

---

config/custom-environment-variables.yaml

Related to https://github.com/screwdriver-cd/screwdriver/issues/1223
Used http://yaml-online-parser.appspot.com/ to check contents of yaml this time

fix(1223): Update executor config yaml indentation

---

design/commands.md

It is better to promote command by assigning tags.
Fix command design.

fix: [small] command design

---

features/sd-cmd.feature

Add another command promote test step.
Check sd-cmd promote tag with tag.
1. https://github.com/screwdriver-cd/screwdriver/pull/1252
2. https://github.com/screwdriver-cd-test/functional-commands/pull/2

fix: [3] promote test

---

plugins/commands/README.md

Add explain of the new feature of the command tag API. 
Write about the feature which can add a tag by specifying tag.
https://github.com/screwdriver-cd/screwdriver/pull/1252#pullrequestreview-146541355

fix: commands readme

---

package.json

To pull in new version of data-schema, scm-github and models. 
issue: #1220 
data-schema: screwdriver-cd/data-schema#277
scm-github: screwdriver-cd/scm-github#102
models: screwdriver-cd/models#288

fix(1220): Pull in new components

---

package.json

add scm-gitlab to api since now we own and support it

fix: package scm-gitlab into api

---

bin/server
config/default.yaml
package.json

Reverts screwdriver-cd/screwdriver#1343

fix: Revert "fix: Initialize cache bookend"

---

bin/server
config/default.yaml
package.json

Reverts screwdriver-cd/screwdriver#1354

Revert "fix: Revert "fix: Initialize cache bookend""

---

bin/server
config/custom-environment-variables.yaml
config/default.yaml

- add feature flag for multi build cluster
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1319

fix: add feature flag for multi build cluster

---

config/custom-environment-variables.yaml
config/default.yaml

Adding comment in config yamls for bot token for PR commenting.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1355

fix(1355): Add bot token comment for scm PR comments

---

plugins/builds/update.js
test/plugins/builds.test.js

- update init step endTime when build starts
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1270

fix: update init step endTime when build starts [3]

---

plugins/pipelines/index.js
plugins/pipelines/metrics.js
test/plugins/pipelines.test.js

Related: https://github.com/screwdriver-cd/screwdriver/issues/1412
Blocked by:
- https://github.com/screwdriver-cd/datastore-sequelize/pull/41
- https://github.com/screwdriver-cd/models/pull/319

feat(1412): add pipeline metrics endpoint

---

package.json

sd api pods crashing due to index rebuilding. 
disable index creation via sequelize
incident# inc2296633

fix: remove index creation due to incident# inc2296633

---

plugins/webhooks/index.js

Currently there are many Promise (`then` and `catch`) and it makes nesting deep.
I rewrote `webhook` module with async/await so that the plugin would be easier to maintain. (49a51cb)
I also add small fixes that webhooks will contain a message for each action. (a4f8f99)

 fix: refactoring of webhook plugin

---

config/custom-environment-variables.yaml
config/default.yaml

- Add sd ui link to sonar config
Related to: https://github.com/screwdriver-cd/coverage-sonar/pull/15

fix: add sonar link config [2]

---

plugins/events/README.md

fix: update event docs for metrics

---

package.json
test/plugins/data/validator.output.json

test failed due to https://github.com/screwdriver-cd/config-parser/pull/86

fix: fix prchain in yaml

---

plugins/pipelines/update.js
test/plugins/pipelines.test.js

pipeline.admins is object instead of array

fix: pipeline.admins is object

---

plugins/webhooks/index.js
test/plugins/webhooks.test.js

Related: https://github.com/screwdriver-cd/screwdriver/issues/1562

fix: skip ci overrides ignore commit

---

plugins/webhooks/index.js

Currently we will catch the err and boomify it and return to user, after boomify, looks like the err only contains err message not the full stack trace. Let's log the whole err object out in our API logs for better debugging purpose.

fix: add more logging for webhook err

---

package.json

Related: https://github.com/screwdriver-cd/notifications-slack/pull/18

fix: update screwdriver-notifications-slack@2.2.1

---

plugins/webhooks/index.js
test/plugins/webhooks.test.js

- add webhook trigger for pipelines with rootDir
- do not create event at all if no changeFiles go under rootDir
- refactor the triggeredPipelines logic for branch filtering, instead of getting a list of branches from git and construct the `scmUris` accordingly, we will just search in the pipeline tables for anything starts with the same scm host and repoId,  e.g.`github.com:12345`
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1455

fix(1455): add webhook trigger for pipelines with rootDir

---

plugins/webhooks/index.js
test/plugins/webhooks.test.js

There are a couple issues with current webhook PR logic. This PR will fix these issues.
- duplicate calls to get `triggeredPipelines` to get relevant pipelines for a given webhook event
- PR restriction check, admin updates, abort running builds etc. only apply to a single pipeline not all the relevant ones
- unnecessary pipeline sync for all the PR events before event creation. when we create the event, we will do a pipeline sync over there.

fix: refactor webhook PR events handler

---

package.json

Update to meta message feature https://github.com/screwdriver-cd/notifications-slack/pull/19

feature: notifications-slack meta message

---

.github/PULL_REQUEST_TEMPLATE.md

This makes it clear that contributors are giving code to the project under the BSD license.
This ensures that contributions are protected under the terms of the BSD license and prevents the ability to revoke access to code that is contributed to this project.

Add license declaration

---

code-of-conduct.md

Updating CoC to reflect new operating business name.
Update text

Updating CoC from Oath to Verizon Media

---

screwdriver.yaml

fix: cp coverage folder to artifacts dir

---

package.json
plugins/jobs/index.js
plugins/jobs/latestBuild.js
test/plugins/jobs.test.js

user request a new endpoint to see the most recent build
add an end point that returns latest build
https://github.com/screwdriver-cd/screwdriver/issues/1717

feat(1717): latest build

---

plugins/templates/create.js

new template creation logic has a bug w/ old code
fix the bug so the logic is consistent

fix: correct new template create logic

---

design/auth.md
design/build-cache.md
design/build-clusters.md
design/director.md
design/sd-yaml.md

I found misspellings in the documentation
Corrected the spelling

fix(documentation): Corrected spelling errors

---

package.json

This PR is for taking the new version of `notifications-email` in screwdriver-api
Update version of `notifications-email` of screwdriver-api
https://github.com/screwdriver-cd/notifications-email/pull/19
https://github.com/screwdriver-cd/screwdriver/issues/1668
https://www.npmjs.com/package/screwdriver-notifications-email

feat(1668): update notifications-email version

---

features/step_definitions/git-flow.js
features/step_definitions/sd-step.js

https://github.com/screwdriver-cd/screwdriver/pull/1842 had some unexpected changes for feature tests :disappointed_relieved:
it may cause the test crash.
Restore these changes.
Let me know if other changes remain.

fix: refix some step definitions

---

bin/server
lib/server.js
package.json
plugins/builds/steps/logs.js
plugins/collections/get.js
plugins/helper.js
plugins/shutdown.js
plugins/webhooks/index.js
test/plugins/collections.test.js

Refactor logging
Use winston@3

fix: refactor logging

---

config/custom-environment-variables.yaml
config/default.yaml
package.json

Move cache strategy config under ecosystem and up executor-k8s-vm version
[1830]

fix(1830): update env var and up k8s-vm version

---

design/sd-local.md

Implementation of https://github.com/screwdriver-cd/screwdriver/issues/1866
One less thing to worry about when running jobs and expecting workspace containment

Support for SD_META_DIR environment variable

---

package.json

Pull latest datastore-sequelize.
https://github.com/screwdriver-cd/screwdriver/issues/1887
https://www.npmjs.com/package/screwdriver-datastore-sequelize
https://github.com/screwdriver-cd/datastore-sequelize/pull/63

fix(1857): pull latest datastore-sequelize

---

screwdriver.yaml

Previous commands are failing to run under shell.
fix functional test command execution.

fix: functional tests command

---

package.json

Reflect changes for "support name of branch with '#'".
https://github.com/screwdriver-cd/scm-github/pull/149
https://www.npmjs.com/package/screwdriver-scm-github/v/9.5.2

fix: update screwdriver-scm-github@9.5.2

---

plugins/builds/index.js
test/plugins/builds.test.js

Currently, if the workflow looks like the image below, each fork would be triggered as its own event. This can be confusing when some of the external forks are in the same pipeline.
This PR fixes the issue mentioned above by triggering one event for downstream jobs in the same pipeline.
Before:
After:

fix(1710): Downstream jobs should be triggered in single event when in the same pipeline

---

plugins/builds/index.js

Adjust error message to make context clear.
Add details to error message.
https://github.com/screwdriver-cd/screwdriver/pull/1999/files

fix: adjust error message

---

plugins/builds/index.js

Add another error handling. Still need to figure out what caused it.
https://github.com/screwdriver-cd/screwdriver/issues/1710

fix: more error handling

---

design/sd-local.md

Update sd-local config design by screwdriver-cd/screwdriver#2050. 
Update configuration that handles multiple cluster configs.
screwdriver-cd/screwdriver#2050

fix(2050) update sd-local config design to use multiple cluster

---

.gitignore
features/step_definitions/trigger.js
features/support/world.js
features/trigger.feature

This reverts commit 3ef606258615ab01e790191f8b2ac99ab43461a3.
revert "fix: Join acceptance tests (#2159)"
#2159 commit caused failure of beta functional test.

Revert "fix: Join acceptance tests (#2159)"

---

config/custom-environment-variables.yaml
config/default.yaml

add cache max go threads config
https://github.com/screwdriver-cd/store-cli/pull/61

fix: add cache max go threads config

---

plugins/auth/index.js

Functional tests fail login via api token.
This PR fixes auth bearer token response for the login issue

feat: fix auth issue

---

screwdriver.yaml

fix: use command version

---

test/plugins/pipelines.test.js

Couple of tests failing and blocking pipeline
This PR comments the tests temporarily to unblock pipeline

feat: skip 2 test temporarily until fixed

---

plugins/commands/updateTrusted.js
plugins/templates/updateTrusted.js

toggling trusted property should update latest template/command instead
toggling trusted property should update latest template/command instead
https://github.com/screwdriver-cd/screwdriver/issues/2350

fix(2350): update latest template/command

---

config/custom-environment-variables.yaml

change redlock custom env variable format
change redlock custom env variable format

fix: change redlock custom env variable format

---

plugins/builds/index.js
plugins/lock.js

fix: remote join data for parentBuilds is having wrong build info

---

plugins/pipelines/badge.js
plugins/pipelines/jobBadge.js

Fix the content type returned from badge api
Update the content-type header of response
https://github.com/screwdriver-cd/screwdriver/issues/2418

Fix badge content-type

---

plugins/builds/index.js
plugins/builds/metrics.js
plugins/events/metrics.js
plugins/jobs/metrics.js
plugins/pipelines/metrics.js

Build showing eslint error for import of lock.js 
Removed .js extension from import statement
N/A

fix: remove lock import file extension

---

plugins/users/settings/update.js
test/plugins/user.test.js

Updating user name of user settings fails to validate in backend
Fixing the validation
https://github.com/screwdriver-cd/screwdriver/issues/2479

fix(2479): display name length validation

---

plugins/helper.js
plugins/pipelines/get.js
plugins/pipelines/index.js
plugins/pipelines/update.js
test/plugins/pipelines.test.js

adding a guard against get pipeline for private repo
adding a guard against get pipeline for private repo

fix(466): add check to get pipeline

---

package.json
plugins/pipelines/list.js
test/plugins/data/privatePipelines.json
test/plugins/pipelines.test.js

hide private pipeline from list endpoint
hide private pipeline from list endpoint

fix(466): hide private pipeline from list endpoint

---

plugins/builds/update.js
test/plugins/builds.test.js

Build status notifications should better to be sent only status is changed.
Therefore, only emits notification event when update status is set.
Only emits build_status when status is passed.
#2096 

[1] fix(2096): Only emits build_status when status is passed.

---

screwdriver.yaml

https://github.com/screwdriver-cd/screwdriver/issues/2514

fix: use DIND for publishing Docker container

---

README.md

https://bestpractices.coreinfrastructure.org/en/projects/4689
Add the CII passing badge to README

[skip ci] Adding CII badge

---

features/step_definitions/templates.js
features/templates.feature

Add some functional tests for template.
This PR adds some functional tests for template.
To run these functional tests, please prepare the following repository and some templates.
The administrator of screwdriver should be ready please.
1. Create `functional-template` repository in [screwdriver-cd-test](https://github.com/screwdriver-cd-test).
2. Add `screwdriver.yaml` and `sd-*-template.yaml` to the `master` branch and `wrong-permission` branch.
3. Create pipelines for both branches.
4. Start pipeline from `init-test-template` and `init-test-trusted-template` jobs.
5. Switch trust of `screwdriver-cd-test/test-trusted-template` template to `trusted`.
6. Uncomment `use-template` and `custom-template` jobs in master branch's `screwdriver.yaml`.
`screwdriver.yaml`
```yaml
shared:
image: …
```

fix(1393): Add functional tests for template

---

features/step_definitions/templates.js

To make [this failed test](https://cd.screwdriver.cd/pipelines/1/builds/747467/steps/test) success. I fixed the functional test added by this [PR](https://github.com/screwdriver-cd/screwdriver/pull/2593)
- Fix request error handling
- Issue
- https://github.com/screwdriver-cd/screwdriver/issues/1393

fix(1393): fix request error handling in template functional test

---

.eslintrc.yaml
.prettierrc.yaml
features/artifacts.feature
features/step_definitions/artifacts.js
package.json

With the reimplementation of SD_ZIP_ARTIFACTS, we will add a functional test for artifacts.
Add a scenario when SD_ZIP_ARTIFACTS is disabled and enabled
#1500
https://github.com/screwdriver-cd-test/functional-artifacts/pull/1

[2] fix(1500): Add functional test about artifacts

---

test/plugins/pipelines.test.js

https://github.com/screwdriver-cd/screwdriver/issues/2605

fix: add new pipeline setting to test data

---

test/plugins/pipelines.test.js

fix: fix pipeline test

---

plugins/events/README.md
plugins/events/listBuilds.js
plugins/jobs/README.md
plugins/jobs/listBuilds.js
test/plugins/events.test.js
test/plugins/jobs.test.js

Reverts screwdriver-cd/screwdriver#2613
This is breaking UI in beta. Navigate to build details page from events https://beta.cd.screwdriver.cd/pipelines/7955
cc @tkyi

Revert "fix(1956): Do not get step info for event and job API"

---

package.json

This PR releases new API version with the latest schema

feat: release new api version with latest schema

---

plugins/builds/index.js
test/plugins/builds.test.js

Reverts screwdriver-cd/screwdriver#2629

Revert "fix(2526): Restart failed build in join workflow should trigger join job"

---

package.json

Import the following updates.
https://github.com/screwdriver-cd/workflow-parser/pull/41

fix: Update workflow-parser to 3.2.1

---

features/step_definitions/events.js
package.json
plugins/events/create.js
test/plugins/events.test.js

There is no eslint check in screwdriver-api
- Add eslint check
- Fix existing eslint errors.

fix: Add eslint check and fix existing lint errors.

---

features/step_definitions/trigger.js
features/support/world.js
features/trigger.feature

Add a functional test for the [Source Directory](https://docs.screwdriver.cd/user-guide/configuration/sourceDirectory.html)
This PR adds a functional test for the source directory.
The repository used for testing was created below:
https://github.com/screwdriver-cd-test/functional-sourceDirectory
https://github.com/screwdriver-cd/screwdriver/issues/1393

feat: Add functional-sourceDirectory

---

screwdriver.yaml

test out buildx
test out multi platforms build

fix: test out buildx

---

screwdriver.yaml

Reverts screwdriver-cd/screwdriver#2693

[skip ci] Revert "fix: test out buildx"

---

plugins/builds/index.js
test/plugins/builds.test.js

The redis lock does not unlock when some error occurs during triggering next job. Thus we should wait that the lock expired.
Fix to unlock redis lock when some error occurs in `triggerNextJobInSamePipeline`, `triggerJobsInExternalPipeline`.

fix: unlock redlock when fail to trigger next job

---

plugins/coverage/token.js
test/plugins/coverage.test.js

Implement as follows issue comments.
https://github.com/screwdriver-cd/screwdriver/issues/2709#issuecomment-1139297527
This PR uses the data submitted in the coverage-bookend step to allow coverage analysis in the self hosted SonarQube.
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/2709
- https://github.com/screwdriver-cd/coverage-sonar/pull/67

[2] feat(2709): Use self-hosted SonarQube server

---

test/plugins/user.test.js

user.setting test was broken with latest dataschema
fix test

fix: fix user.setting test

---

plugins/pipelines/startAll.js
test/plugins/pipelines.test.js

Improve the following Issue.
https://github.com/screwdriver-cd/screwdriver/issues/2712
Check permissions before executing child pipelines.
Pipelines with a permission are executed; otherwise, they are not.
If there is a pipeline that cannot be executed, a 403 error is returned.
Error messages are displayed in the UI, making it easy to notice the cause.
- https://github.com/screwdriver-cd/screwdriver/issues/2712

fix(2712): Permission checks are run when executing child pipelines

---

plugins/users/README.md
plugins/users/index.js
plugins/users/settings/delete.js
test/plugins/user.test.js

To Reset user settings. 
Implement delete method to reset user settings.

feat: Delete method for user settings

---

screwdriver.yaml

fix: use proper API token

---

screwdriver.yaml

fix: correct beta test incovation

---

package.json
test/lib/registerPlugins.test.js

completely remove mockery plugin from screwdriver repo

fix: remove mockery from registerplugin test

---

screwdriver.yaml

fix: overwrite cpu/ram annotation to high

---

bin/server

https://github.com/screwdriver-cd/screwdriver/pull/2825

fix: use hoek.clone for coverage config

---

package.json

https://github.com/screwdriver-cd/scm-bitbucket/pull/87
https://github.com/screwdriver-cd/screwdriver/issues/2858

fix(2858): Upgrade screwdriver-scm-bitbucket

---

test/plugins/data/buildCluster.json
test/plugins/data/buildClusters.json

fix: fix buildcluster test file

---

test/plugins/buildClusters.test.js

Update the build cluster create API tests
This PR updates  build cluster create tests
https://github.com/screwdriver-cd/data-schema/pull/517

fix: build cluster create tests

---

plugins/buildClusters/create.js
plugins/buildClusters/update.js
test/plugins/buildClusters.test.js

Fix build cluster logic for managed and non manged clusters
Fix build cluster logic for managed and non manged clusters

fix build cluster create/update logic

---

features/step_definitions/api-token.js
features/step_definitions/artifacts.js
features/step_definitions/authorization.js
features/step_definitions/build-cache.js
features/step_definitions/collection.js
features/step_definitions/environments.js
features/step_definitions/events.js
features/step_definitions/git-flow.js
features/step_definitions/metadata.js
features/step_definitions/restrict-pr.js
features/step_definitions/sd-cmd.js
features/step_definitions/sd-step.js
features/step_definitions/secrets.js
features/step_definitions/server.js
features/step_definitions/templates.js
features/step_definitions/trigger.js
features/step_definitions/user-teardown-step.js
features/step_definitions/workflow.js
features/support/world.js
package.json

The version of `cucumber`, which is used for functional test, is old.
We update the version of cucumber.
cucumber: https://github.com/cucumber/cucumber-js/tree/main/docs

fix: update cucumber version

---

features/step_definitions/templates.js
features/support/world.js
plugins/banners/create.js
plugins/buildClusters/create.js
plugins/builds/create.js
plugins/collections/create.js
plugins/commands/create.js
plugins/commands/createTag.js
plugins/events/create.js
plugins/events/stopBuilds.js
plugins/pipelines/create.js
plugins/pipelines/listStages.js
plugins/pipelines/tokens/create.js
plugins/secrets/create.js
plugins/templates/create.js
plugins/templates/createTag.js
plugins/tokens/create.js
plugins/versions.js
test/plugins/auth.test.js
test/plugins/buildClusters.test.js
test/plugins/builds.test.js
test/plugins/collections.test.js
test/plugins/commands.test.js
test/plugins/data/stages.json
test/plugins/events.test.js
test/plugins/pipelines.test.js
test/plugins/secrets.test.js
test/plugins/templates.test.js
test/plugins/tokens.test.js
test/plugins/versions.test.js

Pipeline stage tests are broken with latest stage data-schema changes. 
This PR fixes test to unblock pipeline. Also changes order of requires to comply with lint.
Related to https://github.com/screwdriver-cd/data-schema/pull/510

fix(2767): Pipeline stage tests

---

config/default.yaml

chore: correct typos in default.yaml

---

config/default.yaml
package.json

**BREAKING CHANGE: Slack notification config is changed. It must be changed to the new configuration format.**
This PR is the implementation of this.
https://github.com/screwdriver-cd/screwdriver/issues/2505#issuecomment-1668815410
Change the example of slack notification setting to the new format.
Issues
- https://github.com/screwdriver-cd/screwdriver/issues/2505

[2] feat(2505): multi workspace slack notification setting

---

plugins/status.js

Health check does not include checking for queue and store
This PR adds a check for queue and store health if request has exhaustive in query params

feat: add exhaustive health check

---

package.json

fix: pull latest coverage sonar

---

package.json

fix: pull latest data-schema

---

package.json
test/plugins/data/validator.output.json

This PR will bump up workflow-parser version and fix tests.
Pull the following PR.
https://github.com/screwdriver-cd/workflow-parser/pull/45

feat: pull latest workflow-parser

---

plugins/coverage/token.js
test/plugins/coverage.test.js

1) Use `{ projectUrl }` instead
2) Only update `projectUrl` if not using self host sonar
3) Add more logs to track which lines of code are failing

fix: update projectUrl and add more logs

---

plugins/pipelines/update.js

Follow up of https://github.com/screwdriver-cd/screwdriver/pull/2959
Use object instead array

fix: use object instead of array

---

test/plugins/data/validator.output.json

Revert https://github.com/screwdriver-cd/screwdriver/pull/2950
To address https://github.com/screwdriver-cd/screwdriver/issues/2980

fix: reverts #2950

---

Dockerfile

fix: increase npm install timeout

---

Dockerfile
Dockerfile.local

Reverts screwdriver-cd/screwdriver#2999

[skip ci] Revert "fix: use node:20 for docker build"

---

Dockerfile

Increase npm install timeout to publish build
Increase npm install timeout to publish build

feat: Increase npm install timeout

---

bin/server
lib/server.js

Fix issues with pipelineTemplateTagFactory instantiation
Fix issues with pipelineTemplateTagFactory instantiation

feat: instantiate pipelineTemplateTagFactory correctly

---

Dockerfile

Update npm and add npm cache clean to fix npm install timeout
Update npm and add npm cache clean

feat: update npm and add npm cache clean

---

features/data/invalid-pipeline-template.yaml
features/data/valid-pipeline-template.yaml
features/pipeline-templates.feature
features/step_definitions/pipeline-template.js
package.json
plugins/pipelines/templates/get.js

add function test for pipeline template
add function test

feat(3005): add functional test for pipeline template

---

package.json
plugins/auth/login.js
test/plugins/auth.test.js

`gheCloud` configuration is under SCM object, we need to select it appropriately
This PR updates login route to check `gheCloud` from scm configuration

feat: update config for login route

---

package.json

Add missing angle bracket

---

features/metadata.feature
features/pipeline-templates.feature
features/restrict-pr.feature
features/sd-cmd.feature
features/sd-step.feature
features/secrets.feature
features/stages.feature
features/step_definitions/restrict-pr.js
features/subscribe.feature
package.json

Functional tests are slow so would like to run some scenarios in parallel. 
Add more features to be run in parallel. 

fix: add more tests for parallel execution

---

features/metadata.feature
features/pipeline-templates.feature
features/restrict-pr.feature
features/sd-cmd.feature
features/sd-step.feature
features/secrets.feature
features/stages.feature
features/step_definitions/restrict-pr.js
features/subscribe.feature

Reverts screwdriver-cd/screwdriver#3150

Revert "fix: add more tests for parallel execution"

---

features/api-token.feature
features/artifacts.feature
features/authorization.feature
features/build-cache.feature
features/collections.feature
features/environments.feature
features/step_definitions/collection.js
package.json

Reverts screwdriver-cd/screwdriver#3149

[skip ci] Revert "fix: changed api-token and collections func tests to allow parallel"

---

features/sd-setup-scm.feature
features/step_definitions/sd-setup-scm.js

Make that the test to be added in https://github.com/screwdriver-cd-test/functional-sd-setup-scm/pull/2 is executed as a functional test.

[2] fix: add tests for sd-setup-scm step

---

features/subscribe.feature

fix #3194
One beta-x1 scenario of subscribe was not executed due to forgetting to tag it.
Fix the scenarios so that they all run
https://github.com/screwdriver-cd/screwdriver/pull/3194
https://github.com/screwdriver-cd/screwdriver/issues/3182

fix: run all scenarios in functest

---

features/metadata.feature
features/step_definitions/events.js
features/step_definitions/metadata.js

The set of functional tests that are available right now to test metadata behavior is very limited. 
This PR adds more functional tests to ensure the metadata behavior is working as expected. 
https://github.com/screwdriver-cd/screwdriver/issues/3234

feat(3234): Improve metadata functional tests

---

config/custom-environment-variables.yaml
config/default.yaml
lib/server.js

When payloads are logged, it can result in a large volume of logs, which might not always be desirable.
So I implement a feature flag to control the logging of payloads.
Add feature flag for control log payload.

fix: Add feature flag for control log payload

---

features/stages.feature
features/step_definitions/stage.js
features/support/world.js
plugins/pipelines/listStages.js
test/plugins/pipelines.test.js

PR stages is already supported.
This PR make feature tests for PR stages.
I made PRs to prepare the functional tests.
- https://github.com/screwdriver-cd-test/functional-stage/pull/8
- https://github.com/screwdriver-cd-test/functional-stage/pull/9
Please prepare the [functional-stage](https://github.com/screwdriver-cd-test/functional-stage) repository before merging this PR.
1. Create "master" branch (Not "main" branch)
2. Create "prStage" branch from master and put the following `screwdriver.yaml`
3. Create "chainPRStage" branch from master and put the following `screwdriver.yaml` with `chainPR: true`
```yaml
shared:
image: node:20
steps:
- hello: echo 'world'
annotations:
screwdriver.cd/virtualJob: true
jobs:
main:
requires: [ ~pr ]
a:
requires: []
b:
requires: []
c:
requires: [a]
d: …
```

feat(3043): create feature tests for pr stage

---

plugins/builds/steps/logs.js
test/plugins/builds.test.js

Allows timestamps to be added to downloaded logs on `GET /v4/builds/{id}/steps/{name}/logs`
See the added test for the output of each Timestamp format
The releated PR
- https://github.com/screwdriver-cd/data-schema/pull/605 
- https://github.com/screwdriver-cd/ui/pull/1436
Until the data-schema is updated, all requests with timestamp parameters will fail, so the test will fail
Allows user to select.
- Whether to include a timestamp 
- Timestamp format 
- Timestamp time zone (Only affects full-time and simple-time format)
https://github.com/screwdriver-cd/screwdriver/issues/2856

feat(2856): Add timestamp in downloaded logs [2]

---

plugins/webhooks/index.js
test/plugins/webhooks.test.js

fix issue with webhook configuration and scmcontext selection
This PR fixes issue with webhook configuration and scmcontext selection

fix: select current scmcontext

---

plugins/builds/helper/updateBuild.js

Follow up https://github.com/screwdriver-cd/screwdriver/pull/3385 .
- Update `stageBuild.status` to SUCCESS when the stage teardown job is virtual in PR workflow.
- PR - https://github.com/screwdriver-cd/screwdriver/pull/3385

fix: update stageBuild.status when PR teardown job is virtual
