screwdriver-cd/screwdriver

- README.md
- bin/server
- features/step_definitions/server.js
- index.js
- lib/registerPlugins.js
- lib/server.js
- package.json
- test/lib/registerPlugins.test.js
- test/lib/server.test.js
Allow it to take in a config object that looks like:
```
config: {
datastore: screwdriver-datastore-dynamo
}
```
And register the builds plugin with the configured datastore. 
(will squash after comments)
> Register resource plugins with configurable datastore

- lib/registerPlugins.js
- package.json
- test/lib/registerPlugins.test.js
Register the jobs plugin. 
Bump version so that we don't need to pin it in api-aws
> Register jobs plugin

- README.md
- bin/server
- kubernetes/api_deployment.yaml
- lib/registerPlugins.js
- package.json
- test/lib/registerPlugins.test.js
This PR adds in the screwdriver-plugin-login plugin for authorization
The login requires it's own config value so in order to pass that to the plugin this PR also makes it possible to override the config values passed to plugins being registered by specifying it directly in the interface
This PR also:
Changes the AWS volume mounted to a new one created (the old one had invalid data in the imdb)
Mounts secrets in a directory called /etc/secrets for use when starting up the server
> Add screwdriver-plugin-login

- Dockerfile
- wercker.yml
This PR upgrades the build and the runtime container to Node.js v6. (#25)
It seems that there is no incompatible api use. I confirmed that all the tests were successful with Node.js v6.3.0.
> Upgrade to Node.js v6

- README.md
- bin/server
- package.json
This PR brings in the new `screwdriver-plugin-builds` https://github.com/screwdriver-cd/plugin-builds/pull/29 which requires the Executor to be passed in
Updates the README to include the `plugin` field under executor which is required
Updates `bin/server` to read in the right config values
> Allow Executor to be Configurable

- lib/registerPlugins.js
- package.json
- plugins/validator.js
- test/lib/registerPlugins.test.js
- test/plugins/data/validator.input.json
- test/plugins/data/validator.output.json
- test/plugins/jobs.test.js
- test/plugins/validator.test.js
This adds a new route `/v3/validate` that passes a given yaml file through the [config-parser](https://github.com/screwdriver-cd/config-parser).  This way we don't need to install the config-parser locally in the launcher AND we can start a validate page.
> Validation route to parse/translate screwdriver.yamls

- plugins/builds/list.js
- plugins/jobs/list.js
- plugins/pipelines/list.js
- plugins/platforms/list.js
According to http://bigstickcarpet.com/swagger-parser/www/index.html, our validation failed because all the `list` APIs had a schema with a `null` title.
Adding `label` fixes this title.
Before:
```
"responses": {
"200": {
"schema": {
"$ref": "#/definitions/Model 4",
"title": null
},
"description": "Successful"
}
}
```
After:
```
"responses": {
"200": {
"schema": {
"$ref": "#/definitions/List of Builds",
"title": "List of Builds"
},
"description": "Successful"
}
}
```
> Fixing label for list responses (fixes Swagger validation)

- bin/server
- plugins/pipelines/create.js
- test/plugins/pipelines.test.js
This pull request will check if a user has admin access to a given repo and run pipeline create if they do; requires `getPermissions` to be added to Models first
Waiting on https://github.com/screwdriver-cd/models/pull/23
> Check user permissions, attach user during pipeline creation

- plugins/github.js
- test/plugins/github.test.js
When Github sends a webhook, it includes the SHA1 in the payload. This change is to include the specific SHA1 that triggered the hook, so that we can build on that particular commit.
> use sha to start a build

- plugins/github.js
- test/plugins/github.test.js
Lookup a valid admin as a delegate for the `build.create` method. The admin is needed for updating a PR's status (i.e., "pending").
> lookup admin and pass to build.create

- plugins/github.js
- plugins/login/login.js
Both bind and async.apply produce anonymous functions. Function.prototype.apply normally takes a context, but async.apply uses `null` for this context, thus requiring a class method to be bound. We don't need to do any of this since we can create a simple ES6 style anonymous function that executes the original function properly, without needing to insert a context at all, while being just as readable.
I've also fixed the caps on the "instanceOf" variables so they don't look like their respective classes.
> Remove overuse of bind/apply in waterfalls.

- plugins/webhooks/github.js
- test/plugins/webhooks/github.test.js
This PR is tying together the `buildModel.stop` function into the github sync webhook
Dependent on: https://github.com/screwdriver-cd/models/pull/34
One thing I'm wondering is if we should refactor the `getBuildsByJobId` and `buildModel.stop` into a `jobModel.stop` method
Feature: https://github.com/screwdriver-cd/screwdriver/issues/79
> Stop build on PR sync

- bin/server
- lib/registerPlugins.js
- test/lib/registerPlugins.test.js
`npm start` is not working because the plugin is called `webhooks`, not `github`
@stjohnjohnson
> Register webhooks correctly

- config/default.yaml
- package.json
[Feature](https://github.com/screwdriver-cd/screwdriver/issues/77)
Passing:
- buildId - Build Identifier (to look up stuff)
- container - Container to start in
- apiUri - URI to hit our API
- token - Token to be able to read/write from the API
executor `version` is the job-tools version to be used here https://github.com/screwdriver-cd/executor-k8s/blob/master/config/job.yaml.tim#L17
> [F1] Using new Executor Format (with tokens and API URI) (5th)

- lib/server.js
Hard to debug errors when 500 as there is no stack trace in the logs. This PR aims to fix that.
> Add stack trace on 500

- bin/server
- config/custom-environment-variables.yaml
- config/default.yaml
- plugins/webhooks/github.js
- test/plugins/webhooks/github.test.js
Aimed at fixing `500` errors when doing github notifications.
> Add configurable API_URI to github webhook

- bin/server
- lib/registerPlugins.js
- plugins/stats.js
- test/lib/registerPlugins.test.js
- test/plugins/stats.test.js
Creating a new plugin that can be used for exposing statistics about the entire system. 
Right now there are only executor statistics but eventually there could be a plethora of statistics we want to expose about the system
> Route for returning statistics

- plugins/webhooks/github.js
- test/plugins/webhooks/github.test.js
getBuildsForJobId expects a config object, instead of just the jobId.
> Fix signature for getBuildsForJobId

- kubernetes/api_deployment.yaml
Created a `secrets.yaml` file in Kubernetes to include all secrets used in the deployment instead of having them scattered in separate files. This change was done to make the environment variable section in the `api_deployment.yaml` more clear for users.
This pull request covers the changes made in the `api_deployment.yaml` to use the new secrets in `secrets.yaml`.
> Simplify secret environment variables in Kubernetes deployment YAML

- config/default.yaml
- kubernetes/api_deployment.yaml
Also setting the API_URI in the kubernetes deployment config. We should
change this to the CNAME ASAP
> Defaulting to the latest job-tools image instead of 1.0.3

- plugins/webhooks/github.js
- test/plugins/webhooks/github.test.js
Resolves https://github.com/screwdriver-cd/screwdriver/issues/109
Sync is not passing in apiUri and tokenGen. 
Error from the screwdriver build log comes from launcher problems, not this PR.
> Pass in apiUri and tokenGen for sync event

- bin/server
- config/custom-environment-variables.yaml
- config/default.yaml
- kubernetes/api_deployment.yaml
- lib/server.js
- plugins/webhooks/github.js
- test/plugins/webhooks/github.test.js
Now `server.info.uri` will be correct.
> Fixing the externally routable URI so it can be used easily

- kubernetes/api_deployment.yaml
This uses the new token and launcher version (also bumps to 2 instances)
> Fixing K8s configuration

- bin/server
- plugins/stats.js
- test/plugins/stats.test.js
This PR is adding the scmPlugin to the /stats plugin
This will make it possible to have a look into how the scm plugin is performing
> Outputting stats for the scm plugin (merge #3)

- plugins/webhooks/github.js
- test/plugins/webhooks/github.test.js
Right now, everytime we send a sync event (updating a PR), the current API will use the SHA from the master branch instead of the PR.  This corrects that.
> Send the new SHA to the build create for a PR sync event

- plugins/webhooks/github.js
- test/plugins/data/github.parsedyaml.json
- test/plugins/webhooks/github.test.js
When creating a PR, we need to look up the screwdriver.yaml in the PR for the main job, in case the images have changed.
> Look up images when creating PR job

- plugins/builds/create.js
- plugins/pipelines/create.js
- plugins/swagger.js
This adds securityDefinition and security token authentication requirements in the generated swagger spec.
> Security swagger

- lib/server.js
- package.json
- plugins/webhooks/github.js
- test/lib/server.test.js
- test/plugins/webhooks/github.test.js
Depends on models-10.0.0
Sets global apiUri and tokenGen functions on server's buildFactory instance, so these values do not need to be retrieved and passed around to all build models later in multiple places.
> Set common data in build factory

- plugins/webhooks/github.js
- test/plugins/webhooks/github.test.js
Apparently we create Jobs in the GitHub PR event as well as in pipeline.sync, we should centralize this sooner rather then later
> Fixes Job creation during PR open

- lib/server.js
This means `/v3/builds/` and `/v3/builds` are equivalent. Applies to all routes.
> Allow trailing slashes

- package.json
Forgot to pull in new version of k8s after removing streaming (https://github.com/screwdriver-cd/executor-k8s/pull/35)
> Bump k8s version

- plugins/builds/steps/update.js
- test/plugins/builds.test.js
When a build updates the step status with code 0, it was not writing the end time.  This fixes that bug.
Required for https://github.com/screwdriver-cd/launcher/pull/63 to work
> Fix a bug with writing exit code 0

- .editorconfig
- bin/server
- config/default.yaml
Need to pass ui url to build models for target_url configs.
Also add editor config to define how editors should behave:
http://editorconfig.org/
https://atom.io/packages/editorconfig
> Add settings for ecosystem

- plugins/pipelines/index.js
- plugins/pipelines/listJobs.js
- test/plugins/pipelines.test.js
This PR adds in a route to get all jobs for a given pipeline.
It will return 404 when the pipeline does not exist, and will return an array of all jobs.
There isn't any pagination for the route which should be added, but pipeline.jobs only will return 25 jobs (including those that are disabled). 
We need to find a way to filter out all disabled jobs
> Get jobs for pipeline

- plugins/builds/update.js
- test/plugins/builds.test.js
This combines the /webhook/build feature directly into the PUT of /builds/:id
> Move build updating into the PUT /builds/:id

- package.json
- plugins/secrets/README.md
- plugins/secrets/create.js
- plugins/secrets/get.js
- plugins/secrets/index.js
- test/plugins/data/secret.json
- test/plugins/secrets.test.js
- Add /GET secrets/{id} route
- Only users with write permissions can GET all properties of the secret except the value
- Add helper.js with helper functions `userPermission` and `buildPermission`
- The `buildPermission` will be needed later for list
#148 feature
> Add /GET secrets/{id} route

- plugins/auth/index.js
Without this, bell tries to read the server protocol (which is http because we have https on the ingress).  And we end up with this error:
> Authentication failed due to: Invalid setting  - isSecure must be set to false for non-https server
> Fixing HTTPS with OAuth flow by passing another flag

- lib/server.js
Specifically this field: `Access-Control-Allow-Credentials`
So the UI can pass the logged in cookie to the API.
> Enabling credentials to be passed (like cookies + stuff)

- plugins/auth/login.js
- test/plugins/auth.test.js
CORS does not handle redirects well, and javascript is unable to talk to child windows easily. This adds an optional parameter to /auth/login to cause the api to send code to close the window instead of redirecting to /auth/token. The UI can watch for the child window to close, then make an ajax call to /auth/token to get the jwt.
> Add auth/login/web route

- ci/publish
Currently, the `ci/publish` script is unable to use the correct tag as the source.
This PR is to fix this by re-defining the `--data` option.
> Fix git tag for docker publish

- Dockerfile
- hooks/build
- package.json
This uses the undocumented hook feature of Docker Hub to install from a specific version.
Hint here: https://github.com/docker/hub-feedback/issues/508#issuecomment-240616319
This will give us the correct version number when starting these containers.
> Attempting to build docker using tags instead of source code

- plugins/builds/update.js
- test/plugins/builds.test.js
The bug @petey reported #189 is caused by not checking if the completed build is actually a PR or not.  This resolves that by checking for missing from workflow.
> Fixes #189 by skipping workflow trigger if in PR

- config/custom-environment-variables.yaml
- config/default.yaml
- lib/server.js
- package.json
- plugins/pipelines/badge.js
- plugins/pipelines/index.js
- test/plugins/data/jobs.json
- test/plugins/pipelines.test.js
This adds simple badges per pipeline.  It will only show the last build from the `main` job right now.
Looks something like this ![](https://img.shields.io/badge/build-success-green.svg) and can use alternative badge services other than shields.io.
> Adding support for badges per pipeline

- plugins/webhooks/github.js
- test/plugins/webhooks/github.test.js
This fixes the constant error state that the webhooks are in:
> No longer return 404 if pipeline doesn't exist

- bin/server
- plugins/pipelines/create.js
- plugins/pipelines/index.js
- test/plugins/pipelines.test.js
This PR implements the main feature described in #160, blocked by screwdriver-cd/scm-github#8.
Needs to change [this](https://github.com/screwdriver-cd/data-schema/blob/master/models/pipeline.js#L88) if this PR works.
> Store scmId additionally when creating pipelines

- bin/server
- package.json
- plugins/pipelines/create.js
- plugins/pipelines/index.js
- plugins/pipelines/update.js
- plugins/webhooks/github.js
- test/plugins/pipelines.test.js
- test/plugins/webhooks/github.test.js
This enables scmRepo to be updated from the model on `sync` instead of only on create. Also migrates stop to `update` instead.
Depends on https://github.com/screwdriver-cd/models/pull/106
> [stop:2] Using new build.stop feature and migrating scmRepo to models

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
- plugins/auth/index.js
- plugins/auth/token.js
- test/plugins/auth.test.js
Enable an alternative to the OAuth flow for acquiring a valid JWT. This PR is a start, where there is only a single `access_token`. Ideally, we want to allocate `access token`s per user.
Looking for feedback on the direction of the work. This is a frankenstein of a couple of PoCs, so it's rough on a few details.
> Allow auth_token login alternative

- features/support/before-hook.js
- package.json
- screwdriver.yaml
We have parallel tasks happening with integrating our cucumber-js tests in our pipeline. Since not all the tests are defined and some are being re-written, it introduces a lot of risk with integrating them into the pipeline at the end.
This PR aims to hook in the most simple of cucumber tests to sanity check our release flow. As more features are defined, we'll slowly expand the `npm run functional` command to target them.
> Integrate E2E cucumber tests in prod job

- .gitignore
- features/secrets.feature
- features/step_definitions/authorization.js
- features/step_definitions/git-flow.js
- features/step_definitions/secrets.js
- features/support/before-hook.js
- package.json
- Add cucumber test for secrets.feature scenario 1 and 4 (need more users for other scenarios)
- In scenario 1, remove `And the build succeeded` since it is already checked in `Then the "foo" secret should be available in the build`
- PipelineId is hardcoded until we find a better way to do it
- [Repo used for testing](https://github.com/screwdriver-cd-test/functional-secrets)
issue [#148](https://github.com/screwdriver-cd/screwdriver/issues/148)
> Add functional test for secrets scenario 1 and 4

- config/custom-environment-variables.yaml
- config/default.yaml
This allows us to use `beta_` for our beta environment
> Support overriding the dynamodb prefix via environment variables

- screwdriver.yaml
This ensures we test beta environment first and don't accidentally break production
> Deploy to beta first, then production

- plugins/builds/listSecrets.js
- plugins/pipelines/listSecrets.js
- plugins/secrets/README.md
- plugins/secrets/get.js
- plugins/secrets/index.js
- plugins/secrets/update.js
- test/plugins/secrets.test.js
- Add `update` route for secrets
- Only user can `update` a secret
- Modify `canAccess` helper function to take in required permission
- Update README
Issue #232
>  Add update secret route

- package.json
- plugins/webhooks/github.js
- test/plugins/webhooks/github.test.js
- This allows synchronize event to read from PR ref instead of master. 
- Remove `getBuildsForJobsId` and replace with `job.getRunningBuilds()`
- Still need to keep this check: https://github.com/screwdriver-cd/screwdriver/blob/da6cf99d835bc8750fe4e6e6792f1b176cd944d8/plugins/webhooks/github.js#L14-L16 just in case the build finishes in between the time it gets the running builds and time stopRunningBuild is called. 
- Blocked by https://github.com/screwdriver-cd/models/pull/113
- Relates to https://github.com/screwdriver-cd/screwdriver/issues/241
> PR sync reads from its branch

- plugins/builds/steps/logs.js
- test/plugins/builds.test.js
- test/plugins/data/build.json
This fixes log requests returning a header indicating that there are more logs for a step that never started.
> Don't say there are more logs when the step hasn't started.

- .gitignore
- bin/server
- config/default.yaml
- index.js
- lib/registerPlugins.js
- lib/server.js
- package.json
- plugins/builds/steps/logs.js
- plugins/stats.js
- test/lib/registerPlugins.test.js
- test/lib/server.test.js
- test/plugins/builds.test.js
- test/plugins/pipelines.test.js
- test/plugins/stats.test.js
Uses the new `setup` from Datastore, removes the `Plugin` in `scmPlugin`, refactors some internal callbacks as promises, and migrates away from the custom log url into ecosystem.
This requires:
- https://github.com/screwdriver-cd/models/pull/118
- https://github.com/screwdriver-cd/datastore-dynamodb/pull/29
- https://github.com/screwdriver-cd/datastore-base/pull/17
> Use new Datastore setup as well as no `plugin`

- features/support/github.js
- package.json
Reverts screwdriver-cd/screwdriver#271
This is breaking functional tests. Will reopen after fixing functional tests and after `scm-github` is also updated.
The change was also incomplete: https://github.com/screwdriver-cd/screwdriver/pull/290/files?diff=split#diff-7f1dbea8150406f3ab171515f38879b7L133
> Revert "Update github to version 5.2.1 🚀"

- README.md
- plugins/auth/README.md
Documenting the different authentication routes:
- `GET /auth/login` or `POST /auth/login`
- `GET /auth/token`
- `GET /auth/key`
- `POST /auth/logout`
> Add README for authentication routes

- screwdriver.yaml
The previous command only worked if there was 1 tag per commit. This is not always the case.
> Use new git-latest command to get the current git tag

- plugins/builds/steps/logs.js
- test/plugins/builds.test.js
With the new paging, log loading is a little slower from the UI as it polls every second.  This would load ALL the logs that are available after line X for each poll.
> Pull all logs that are available at a given time

- bin/server
- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
- plugins/auth/index.js
- plugins/auth/login.js
- test/plugins/auth.test.js
- test/plugins/webhooks/github.test.js
Blocked on https://github.com/screwdriver-cd/scm-github/pull/25
- Can configure to use GitHub Enterprise
- Can configure to use another SCM other than GitHub
- Split password up into its two forms (encryption and cookie signing)
_note I tried to keep the environment variables backwards compatible, but `local.yaml` is no longer the same_
> Switching to pluggable auth

- plugins/auth/index.js
- test/plugins/auth.test.js
Without this, OAuth flow fails due to trying to redirect to HTTP not HTTPS
> Forgot required flag about HTTPS

- package.json
- test/plugins/webhooks/github.test.js
Trying to reduce the load on this test.  This might fix #308
> Removing long-timeout and removing auth registration in Webhook test

- plugins/builds/update.js
- test/plugins/builds.test.js
The UI already has the ability to disable jobs. This PR makes this actually have an effect on the workflow by stopping the line.
> Disabled jobs should not be triggered in workflow

- README.md
the description of the two SCM options had an extra space that indented it...
---------
old:
---------
Two (2) options for executor:
- Kubernetes (`k8s`)
- Docker (`docker`)
Two (2) options for SCM:
- Github (`github`)
- Bitbucket (`bitbucket`)
---------
vs. new
---------
Two (2) options for executor:
- Kubernetes (`k8s`)
- Docker (`docker`)
Two (2) options for SCM:
- Github (`github`)
- Bitbucket (`bitbucket`)
> minor readme formatting fix

- features/step_definitions/authorization.js
- plugins/pipelines/create.js
- test/plugins/pipelines.test.js
- Add `pipelineId` to 409 error message
- Use error message to get `pipelineId` in functional test
Fixes https://github.com/screwdriver-cd/screwdriver/issues/289
> Add pipelineId to 409 error message

- plugins/builds/create.js
- test/plugins/builds.test.js
Caught a bug in event creation: the workflow job for a PR should be the `job.name` (eg: PR-15)
> Bugfix: job for PR workflow should be named PR-

- plugins/webhooks/index.js
- test/plugins/webhooks/github.test.js
The Github API has request-threshold quotas in place. Requests are tracked by either IP or API token. During the PR job creation, Screwdriver uses the PR users's access token to communicate with the Github API. If a user is not registered in Screwdriver, this operation will fail and the job will not run.
This PR proposes a solution that fixes #335 . If a PR user does not have an API token registered in Screwdriver, then it will use a default, generic user's API token instead.
> pr jobs can be started by non-screwdriver users

- plugins/webhooks/index.js
- test/plugins/webhooks/index.test.js
- Renamed the webhook id from `eventId` to `hookId`
- Events are also created when a pull_request or push event webhook is sent
Follow up to https://github.com/screwdriver-cd/screwdriver/pull/337
> Create events when starting builds because of webhooks

- config/default.yaml
Same fix as this PR: https://github.com/screwdriver-cd/executor-k8s/pull/48
> Setting the default K8S_HOST to `service.namespace` instead of `service`

- package.json
Currently failing:
```
/sd/workspace/src/github.com/screwdriver-cd/screwdriver/node_modules/eslint-config-airbnb-base/rules/imports.js:
Configuration for rule "import/no-unresolved" is invalid:
Value "data["0"].caseSensitive" has additional properties.
Referenced from: airbnb-base
Referenced from: screwdriver
Referenced from: /sd/workspace/src/github.com/screwdriver-cd/screwdriver/.eslintrc.yaml
Error: /sd/workspace/src/github.com/screwdriver-cd/screwdriver/node_modules/eslint-config-airbnb-base/rules/imports.js:
Configuration for rule "import/no-unresolved" is invalid:
Value "data["0"].caseSensitive" has additional properties.
Referenced from: airbnb-base
Referenced from: screwdriver
Referenced from: /sd/workspace/src/github.com/screwdriver-cd/screwdriver/.eslintrc.yaml
at …
```
> Remove eslint-plugin-import package

- CHANGELOG.md
- README.md
- lib/registerPlugins.js
- plugins/events/README.md
- plugins/events/get.js
- plugins/events/index.js
- plugins/events/listBuilds.js
- test/lib/registerPlugins.test.js
- test/plugins/events.test.js
- test/plugins/jobs.test.js
- Add `GET event/:id/builds` and `GET event/:id` endpoints
- So that the UI can query all builds associated with a event
> Add GET event/:id/builds endpoint

- bin/server
This is causing a startup failure on beta.sd
> fix: Removing extra comma from Bookend instantiation

- package.json
We recently bumped the major versions on each of the executors.  This catches us up.
> fix: Upgrading executor versions

- config/custom-environment-variables.yaml
So you can do something like:
```
HTTPD_TLS='{"key":"`cat ./cert.key`","cert":"`cat ./cert.cert`"}'
```
More options are here: https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener
> Allow users to customize TLS settings via a JSON stringified environment variable `HTTPD_TLS`

- CONTRIBUTING.md
Add commit message format. 
Relates to: https://github.com/screwdriver-cd/screwdriver/issues/373
> docs: add commit message format

- plugins/auth/index.js
- Allow https to be 'true' or 'false' as string
- Because when we set IS_HTTPS in k8s deployment, we set it as string "true"
Related to recent update on joi  https://github.com/screwdriver-cd/screwdriver/pull/382
> fix: update joi.boolean() validation for auth

- plugins/auth/crumb.js
- plugins/auth/key.js
- plugins/auth/login.js
- plugins/auth/logout.js
- plugins/auth/token.js
- plugins/builds/create.js
- plugins/builds/update.js
- plugins/pipelines/README.md
- Add documentation for pipeline endpoints
- Fix descriptions to make them consistent and clear when showing up in the swagger page
> docs: make api documentation more clear and consistent

- plugins/webhooks/index.js
- test/plugins/webhooks/index.test.js
- jobId does not exist yet when PR is open (that job hasn't been created!) 
- Archive after stopping job. This line https://github.com/screwdriver-cd/screwdriver/blob/aa33dff74ee523b214d2fb734d41a8b01f2086b5/plugins/webhooks/index.js#L70
causes problems now. For sequelize, it creates a new job with a new id for `pullRequestSync` but the job already exists.
> fix: job does not exist yet for openPR

- features/step_definitions/git-flow.js
Trying to unblock the API pipeline. Seeing timeout failures in git-flow tests without seeing any other significant errors in the beta API logs. Increasing the timeout x2 just to see if the build will pass
Related to https://github.com/screwdriver-cd/screwdriver/issues/399
> fix: Increase git-flow func test timeout

- plugins/pipelines/README.md
- plugins/pipelines/create.js
- plugins/pipelines/index.js
- plugins/pipelines/syncWebhooks.js
- test/plugins/pipelines.test.js
- Since we [moved addWebhook out of sync](https://github.com/screwdriver-cd/models/pull/146), we should now call it inside the `POST /pipelines`. 
- Also added a new endpoint to sync webhooks if it's not correct. We can add a button for it in UI later.
Blocked by: https://github.com/screwdriver-cd/screwdriver/pull/401
Related: https://github.com/screwdriver-cd/screwdriver/issues/379
> feat(379) Add webhook during pipeline recreation

- package.json
Screwdriver is really still at version 0 (we don't have our 1.0 release yet).  I've already gone and corrected our git tags to be correct.  This will ensure our Docker and NPM packages will be shipped accordingly.
> Rolling back to v0

- README.md
The `README.md` refers to the wrong docker image. It's referring to `screwdrivercd/api` when it should be `screwdrivercd/screwdriver`.
Reference: https://news.ycombinator.com/item?id=13424592
Docker Image: https://hub.docker.com/r/screwdrivercd/screwdriver/
> docs: refer to the correct docker image

- Dockerfile
This makes it easy for people to insert their own local configuration.
We already do it in the store: https://github.com/screwdriver-cd/store/blob/master/Dockerfile#L14-L15
> fix: Allow users to mount local.yaml files into /config/local.yaml

- in-a-box.py
This allows users who create docker-machines as virtual machines.  These machines have IPs that are created on virtualized networks on the host.
> fix: Obtain IP for Docker-Machine users

- .npmignore
- bin/server
- config/custom-environment-variables.yaml
- config/default.yaml
BREAKING CHANGE: Users who previously overrode bookend will need to fix `sd-scm` and config location in local.yaml
- Moving `bookend` config to it's own top-level config instead of flooding `ecosystem`
- Renamed `sd-scm` to `scm` as it already adds `sd-` in all bookeneds
- Preventing local.* from going into NPM
> fix: Cleaning up Bookend Definition

- config/custom-environment-variables.yaml
- config/default.yaml
Adds environment variables to specify if GitHub should ask for elevated privileges to read private repositories.
Related:
https://github.com/screwdriver-cd/scm-github/pull/51
https://github.com/screwdriver-cd/screwdriver/issues/436
> feat: allow configuration for Github private repo support

- plugins/builds/update.js
- test/plugins/builds.test.js
I found that triggered builds don't have `parentBuildId` parameter set.
I fixed that issue and remove the mock which seems to be unused around its test.
> fix: Set parentBuildId for triggered builds

- bin/server
- config/custom-environment-variables.yaml
- config/default.yaml
- plugins/webhooks/index.js
- test/plugins/webhooks/index.test.js
Add environment variables `SCM_USERNAME` and `SCM_EMAIL` with use custom user for checkout.
https://github.com/screwdriver-cd/scm-github/pull/52
https://github.com/screwdriver-cd/scm-bitbucket/pull/34
As a further modification, if a user does not have a valid SCM token registered with Screwdriver, `SCM_USERNAME` will use this user's token instead.
> fix: can settings username and email for checkout

- in-a-box.py
Looks like the [Python2/3 change](https://github.com/screwdriver-cd/screwdriver/pull/451) broke how secrets are set in the template.  It's adding an extra newline before and after the JWT keys.
> fix: Correct padding of JWT secrets

- in-a-box.py
I added a feature for supporting bitbucket addressed in #321.
```
🎁   Boxing up Screwdriver
👀   Checking prerequisites
🔐   Generating signing secrets
📤   Which SCM provider would you like to use? (github/bitbucket) a
📤   Which SCM provider would you like to use? (github/bitbucket) bitbucket
📦   Generating OAuth credentials
Please create a new OAuth application on Bitbucket.com
Go to https://bitbucket.org/account/user/<your username>/oauth-consumers/new to start the process
For 'URL' put http://192.168.1.16:9000
For 'Callback URL' put http://192.168.1.16:9001/v4/auth/login
for 'Permissions' enable Read checkbox for Repositories, Account and Pull requests
When done, please provide the following values:
Key: thisiskey
Secret:
💾   Writing Docker Compose file
🚀   Screwdriver is ready to …
```
> fix: Add SCM selector to in-a-box

- plugins/pipelines/badge.js
- test/plugins/data/events.json
- test/plugins/pipelines.test.js
- Previously the badge only reflect the build status for main job
- Change it to get the last build status of the latest event
related to https://github.com/screwdriver-cd/screwdriver/issues/460
> Fix: make the badge show status of the latest event

- package.json
`screwdriver-api` already has `request` module in dependencies, so it seems that the one in devDependencies isn't necessary.
> fix: Remove request module from devDependencies

- bin/server
- config/default.yaml
- package.json
Registers artifact bookend, which uploads artifacts to S3
Blocked by: https://github.com/screwdriver-cd/artifact-bookend/pull/1
Related: https://github.com/screwdriver-cd/screwdriver/issues/458
> feat: register artifact bookend to upload artifacts

- config/default.yaml
We would like jpae to get access to the screwdriver cluster so he can run through our demo (https://github.com/screwdriver-cd/fuji-demo)
> fix: Whitelist jpae

- plugins/builds/update.js
- test/plugins/builds.test.js
Move build.update() before triggering next build, otherwise the next build won't be able to get the `meta` from previous build when it starts.
Related to https://github.com/screwdriver-cd/screwdriver/issues/293
> fix(293): update current build before triggering next build

- package.json
- plugins/templates/create.js
- test/plugins/data/templates.json
- test/plugins/templates.test.js
Auto bump version:
For example, if latest version is 1.7.3
If template.yaml says 1, it will create 1.7.4
If template.yaml says 1.7, it will create 1.7.4
If template.yaml says 1.7.3, it will create 1.7.4 (does not matter what the patch is)
If template.yaml says 1.8, it will create 1.8.0
If template.yaml says 2, it will create 2.0.0
Blocked by https://github.com/screwdriver-cd/models/pull/151
https://github.com/screwdriver-cd/models/pull/152
Related: https://github.com/screwdriver-cd/screwdriver/issues/470
> fix(470): autobump version

- plugins/validator.js
TemplateFactory should be passed to `config-parser`
https://github.com/screwdriver-cd/config-parser/blob/master/index.js#L26
> fix(470): Pass templateFactory to parser

- features/metadata.feature
This is [blocking](https://cd.screwdriver.cd/pipelines/1/build/2505) the pipeline, It is failing with 
```
@metadata
Scenario: Adding some data to metadata
/sd/workspace/src/github.com/screwdriver-cd/screwdriver/node_modules/cucumber/lib/cucumber/support_code/step_definition.js:63
var timeoutInMilliseconds = options.timeout || defaultTimeout;
TypeError: Cannot read property 'timeout' of undefined
```
I ran locally and found out when it matches the `an existing pipeline with the workflow:` on [this](https://github.com/screwdriver-cd/screwdriver/blob/master/features/step_definitions/events.js#L21-L22) line, the options `{timeout: TIMEOUT}` is not passed in. 
One possibility is that we are using `Scenario Outline` here, and event is using `Scenario`. However, I tried to simplify this test to …
> fix: ignore metadata feature test

- features/step_definitions/templates.js
- plugins/template-validator.js
- test/plugins/validator/template.test.js
I Modified it because test has getting failed. Does this modification would be the right decision?
Test failed reason is,
```
1) template validator plugin test POST /validator/template returns BAD REQUEST for template that cannot be parsed:
AssertError: expected value to match
expected = /YAMLException/
actual = incomplete explicit mapping pair; a key node is missed at line 1, column 8:
error: :
```
And modified a lint warning.
```
/Users/kkawahar/screwdriver/features/step_definitions/templates.js
8:18  warning  Unexpected unnamed function  func-names
✖ 1 problem (0 errors, 1 warning)
```
> feat: Modify validator/template test

- features/metadata.feature
- features/step_definitions/metadata.js
relay: https://github.com/screwdriver-cd/screwdriver/pull/499
Perhaps it was because timeout was required for `a metadata starts with an empty object`. I tried to fix it, the part of the problem seems to work.
```
@metadata
Scenario: Adding some data to metadata
✔ Given a metadata starts with an empty object
```
In addition, the table of `Example` was automatically expanded, and it turned out that the step was undefined. In order to fix this, I think that we need to modify matching pattern and remove some from the `Examples`.
```
- When the "main" job is started
? Then add the { "foo": "foobar" } to metadata in the "main" build container
- And the build succeeded
- And the "BAR" job is started
? Then in the build, the { "foo": "foobar" } is available from metadata
? And add the { "bar": …
```
> feat: Modify metadata cucumber

- plugins/templates/get.js
- plugins/templates/index.js
- test/plugins/templates.test.js
Adding `GET templates/name/version` endpoint
`version` can be:
- exact version (`1.2.3`)
- OR major minor (`1.2`) or major (`1`): in these cases, it will get the latest. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/470
> fix(470): Add get endpoint for templates

- features/metadata.feature
- plugins/templates/create.js
- test/plugins/templates.test.js
It looks through `config.params` in datastore scan:
https://github.com/screwdriver-cd/datastore-sequelize/blob/master/index.js#L319-L320
> fix: datastore scan requires params key

- .gitignore
- README.md
- in-a-box.py
I added a feature to support restarting in-a-box described in #321.
I confirmed that the database file is created when the first run and data still remains after restart.
> feat(321): Support restarting in-a-box service

- plugins/templates/index.js
- plugins/templates/listVersions.js
- test/plugins/data/templateVersions.json
- test/plugins/templates.test.js
Add a `GET /templates/name` endpoint to the templates plugin in the API. This returns all the template versions for a given template name.
For example, for `{API_ROOT}/v4/templates/node%2Ftest`, it will return an array of all versions in the datastore:
```
[{
"id": 9,
"labels": ["stable"],
"config": {
"image": "node:6",
"steps": [{
"install": "npm install"
}, {
"test": "npm test"
}]
},
"name": "node/test",
"version": "1.0.6",
"description": "this is a template for nodejs",
"maintainer": "daolam112@gmail.com",
"scmUri": "github.com:82863190:master"
}, {
"id": 8,
"labels": ["stable"],
"config": {
"steps": [{
"install": "npm install"
}, {
"test": "npm test"
}]
},
"name": "node/test",
"version": "1.0.5",
"description": "this is a template for nodejs",
"maintainer": "daolam112@gmail.com", …
```
> feat: Add endpoint to get versions for a template name

- plugins/builds/update.js
- test/plugins/builds.test.js
It's faster to load from `/pipelines/{pipelineId}/builds/{buildId}`
We are trying to deprecate the other endpoint.
> fix: update build link for notifications

- config/custom-environment-variables.yaml
- config/default.yaml
- in-a-box.py
- package.json
This PR allows users to use Gitlab as SCM. It also allows `in-a-box` script to take Gitlab as an option. 
This is blocked until @bdangit's  `scm-gitlab` is published: https://github.com/bdangit/scm-gitlab
> feat(453): support Gitlab

- package.json
- plugins/templates/create.js
- test/plugins/data/template.json
- test/plugins/data/templateVersions.json
- test/plugins/data/templates.json
- test/plugins/templates.test.js
We should tie template to `pipelineId` instead of pipeline's `scmUri` since `pipelineId` is the identifier. 
Related: https://github.com/screwdriver-cd/data-schema/pull/116
> fix: template ties to pipelineId instead of scmUri

- features/step_definitions/metadata.js
- features/step_definitions/secrets.js
I found that it need to give arguments when capturing with regular expressions.
https://cd.screwdriver.cd/pipelines/1/build/2781
So, I modified to not capture. By modifying this way, it seems that there is no problem without specifying arguments.
> feat: Fix not to capture unused string

- .func_config.json
- README.md
- features/step_definitions/authorization.js
- features/step_definitions/events.js
- features/step_definitions/git-flow.js
- features/step_definitions/metadata.js
- features/step_definitions/secrets.js
- features/support/before-hook.js
- screwdriver.yaml
In order to running locally functional test, I needed to fix some.
1. First of all we have to login local SD with `sd-buildbot` account to run functional test. But I can't login local SD with `sd-buildbot` account because I'm not owner of `sd-buildbot`. So, I need to use my own account to run functional test.
2. My own account can't access [screwdriver-cd-test Org](https://github.com/screwdriver-cd-test) with administrator privileges. So, I needed to fork `functional-*` repositories from [screwdriver-cd-test Org](https://github.com/screwdriver-cd-test) and use it.
> feat: Modify functional test for running locally

- plugins/templates/create.js
- test/plugins/data/template-create.input.json
- test/plugins/data/template.json
- test/plugins/templates.test.js
`POST /templates` is currently taking in the screwdriver config, and was validated based on `schema.models.template.create`: https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/templates/create.js#L69
This PR changes the payload to be the same as [`POST /validator/template`](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/template-validator.js). It takes in yaml string instead of the config. 
So payload looks like:
```
{"yaml":"{\"name\":\"template_namespace/nodejs_main\",\"version\":\"1.2\",\"description\":\"Template for building a NodeJS module\\nInstalls dependencies and runs tests\\n\",\"maintainer\":\"me@nowhere.com\",\"config\":{\"image\":\"node:6\",\"steps\":[{\"install\":\"npm install\"},{\"test\":\"npm …
```
> fix: POST/templates takes in yaml string instead of config

- features/sd-step.feature
- features/step_definitions/sd-step.js
There is no functional test for shared steps. This PR is implementing step definitions for shared steps.
The test passed locally.
Use this test-repo and need merge before  https://github.com/screwdriver-cd-test/functional-shared-steps/pull/1
> feat(300): add step definitions for shared steps

- lib/registerPlugins.js
- package.json
- test/lib/registerPlugins.test.js
Notification plugins are registered at [registerPlugins](https://github.com/screwdriver-cd/screwdriver/blob/master/lib/registerPlugins.js#L85) and called `notify`, then notification plugin returns a Promise but `registerPlugins` does not use the status of Promise. https://github.com/screwdriver-cd/notifications-base/pull/3 provides update about this.
And the registration logic can be also improved.
This PR provides to fix event registration logic. Notification plugins will have minimum parameters.
Related: https://github.com/screwdriver-cd/screwdriver/issues/517
> fix(517): improve notification plugin register

- features/step_definitions/authorization.js
- features/step_definitions/metadata.js
- features/step_definitions/sd-step.js
- features/step_definitions/secrets.js
Part of investigating the flaky functional tests. There are some assertions being made after the tests are searching for data in the payloads. 
This update reverses the logic, so that we can assert the request is sane before we try to parse the payload for the data we're looking for.
* Assists with #533
EDIT: Included the related issue
> fix: response assertions first

- features/api-token.feature
As an alternative to passwords, Screwdriver could allow access tokens to be exchanged for JWTs. This would enable another authentication workflow besides the standard web application flow. 
A feature file to represent the functionality behind #524 . 
* Relates to #532
> feat(524): add feature test for api token

- plugins/builds/steps/update.js
- plugins/builds/update.js
Due to some dependency changes (still investigating), `throw` boom error without return reply() will cause 500. This PR is to fix the current failing tests.
> fix: fix failing unit tests

- test/plugins/pipelines.test.js
One of the tests in pipeline.test.js was failing, but it wasn't showing up in the summary at the end because the test was using a callback instead of a `then` block.
I *think* this is what the test should be testing for, by looking at the code for pipelines and talking to @d2lam, but @d2lam please confirm this!
> fix(tests): Fix a pipelines test that was failing

- plugins/tokens/README.md
- plugins/tokens/index.js
- plugins/tokens/refresh.js
- test/plugins/tokens.test.js
* `PATCH` `/tokens/{id}/refresh` will refresh the token's value and return it while preserving the other fields of the token
> feat(tokens): Add token refresh route

- .func_config.json
- README.md
- features/support/before-hook.js
Since `.func_config.json` was already in the index, it being in the .gitignore did nothing. This made it easy to accidentally publish tokens on github.
* removed `.func_config.json` from git index
* updated `readme.md` to have instructions on creating `.func_config.json` rather than modifying it, as well as adding that you can set these with environment variables as well
> enhancement: remove .func_config.json

- .gitignore
- README.md
- features/support/before-hook.js
- package.json
It will throw an err during the `require('../../.func_config')` because we remove the `.func_config` file.
https://cd.screwdriver.cd/pipelines/1/builds/4770
> fix: do not throw err if func_config does not exist

- plugins/auth/README.md
Realized that this wasn't in the docs while talking to Bharwal about how to call the API.
> docs(tokens): Document ability to call GET /auth/token with access key

- features/api-token.feature
- features/step_definitions/api-token.js
- features/step_definitions/authorization.js
- features/step_definitions/events.js
- features/step_definitions/git-flow.js
- features/step_definitions/metadata.js
- features/step_definitions/sd-step.js
- features/step_definitions/secrets.js
- features/support/before-hook.js
* Add the acceptance test for the token `GET` route
* Remove the `eslint-ignore`s because that rule got amended to ignore `Before` and `After` in https://github.com/screwdriver-cd/eslint-config-screwdriver/pull/23
> User Tokens: Add test for GET route

- features/api-token.feature
- features/step_definitions/api-token.js
- plugins/tokens/README.md
- plugins/tokens/refresh.js
- plugins/tokens/update.js
- test/plugins/tokens.test.js
* Added a criterion to make sure `PUT`ting the token doesn't count as "using" it.
* Switch token update/refresh routes to use `PUT` instead of `PATCH`
> feat(tokens): Token PUT acceptance test

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Having templates for PRs helps maintain document the intentional changes that a PR introduces. This helps a lot with debugging features in the future, and for those who did not author the feature to determine a good remediation to related issues.
Issue templates help us by asking for the (usually missing) information that allows us to investigate issues more effeciently.
Create an initial version of templates for both issues & pull requests.
* https://github.com/blog/2111-issue-and-pull-request-templates
> chore: Created issue & PR templates

- plugins/auth/token.js
- plugins/tokens/refresh.js
- plugins/tokens/update.js
* the `GET /auth/token` endpoint is very important for anybody wanting to use API tokens to interact with screwdriver, but is not listed in the api [swagger docs](api.screwdriver.cd/v4/documentation)
* removed an unnecessary statement in the tokens `refresh` and `update` endpoints
> docs(api): Add swagger documentation to GET /auth/token

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
*Why do we need this PR? What was the reason that led you to make this change?*
The original templates were inherited from the Kubernetes repository. They contained comments so that the reporter would better understand what each section was about. When the team implemented the Github issue templates, these comments were changed to always render. 
*What does this PR fix? What intentional changes will this PR make?*
Re-implement the template comments as comments so that the markdown does not render it.
*Links or resources that help clarify and support your intentions (e.g., Github issue)*
* https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md
* https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md
* #612
> chore: github issue template comments

- features/sd-step.feature
- features/step_definitions/sd-step.js
This PR is a modified functional test for the semver feature of sd-step.
I originally thought about running Scenario for each version (e.g. ~6.9.0, ^6.0.0),
but now it seems that all jobs are triggered by workflow, so I’ll add step in the main job　(screwdriver-cd-test/functional-shared-steps/pull/3)
Related to screwdriver-cd/sd-step#3, screwdriver-cd-test/functional-shared-steps/pull/3
> feat: modify sd-step functional test for semver

- bin/server
- config/custom-environment-variables.yaml
- config/default.yaml
Screwdriver uses the default Docker implementation of `node:4 => registry.hub.docker.com/r/library/node:4`. For companies that run their own private registry, it may be more beneficial for them to override that default behavior.
This change allows for a global configuration where an image with a name like `node:4` translates into `private.registry.com/_/node:4`.
* Resolves #472 
* Dependent on screwdriver-cd/models#175
> feat(472): alternative default docker registry

- package.json
Pulling in new executor-router version (https://github.com/screwdriver-cd/executor-router/pull/9)
Related to https://github.com/screwdriver-cd/screwdriver/pull/607
Original issue: #604
> fix(604): Pull in new executor-router version

- plugins/pipelines/README.md
- plugins/pipelines/create.js
- plugins/pipelines/helper.js
- plugins/pipelines/index.js
- plugins/pipelines/update.js
- test/plugins/data/updatedPipeline.json
- test/plugins/pipelines.test.js
Users would like the ability to update their checkout repo and branch without having to create a new pipeline.
This PR is a continuation of work done previously to allow users to update their checkoutUrls. This PR adds a `PUT` route for updating `checkoutUrl` and also has a minor refactor of the `formatCheckoutUrl` method into a separate helper file.
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/562
Other relevant PRs: [models](https://github.com/screwdriver-cd/models/pull/176), [data-schema](https://github.com/screwdriver-cd/data-schema/pull/148)
> feat(562): Add update path to pipelines

- package.json
New version of k8s-vm contains the fix for prestop hook
> fix: pull in newer version of k8s-vm

- features/authorization.feature
- features/step_definitions/authorization.js
- features/templates.feature
Users would like to be able to update the repo and branch on their pipeline without having to create a new pipeline (and lose their pipeline ID).
A previous PR has already added an update route. This PR will add a feature test scenario for updating a pipeline checkoutUrl. Also, it will rename "project" to "pipeline" in feature test files.
We will add a passing feature test in the future.
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/562
- Related PR: https://github.com/screwdriver-cd/screwdriver/pull/627
> fix(562): Add feature test scenario for updating a pipeline

- package.json
Habitat server is down. 
Roll scm-github version back  to not have habitat 
https://github.com/screwdriver-cd/scm-github/commit/625077368519cfe57769afe4f925d831f44ceab7
> Pin scm-github version to not have habitat

- package.json
roll forward scm-github version since habitat is up and running now.
> fix: roll forward scm-github version

- features/authorization.feature
- features/step_definitions/authorization.js
- features/support/world.js
For the support multiple SCMs, Screwdriver has to determine the user by not only `username` but also `scmContext`.
This PR add a functional test which check the user profile by `username` and `scmContext`.
issue: https://github.com/screwdriver-cd/screwdriver/issues/365
data-schema change: https://github.com/screwdriver-cd/data-schema/pull/152
> feat(365) Add functional test for multiple scms

- lib/server.js
- plugins/pipelines/create.js
- test/lib/server.test.js
As of today error responses are simply text description of the error, making it difficult for clients like UI to parse it and do meaningful action on the error. For example, for on duplicate pipeline error, users are better served if we can take them to the pipeline which is already setup for the given repo.
Send back existing pipeline id as part of JSON payload.
> Send conflicting pipeline ID on error

- test/plugins/data/pipeline.json
- test/plugins/data/pipelines.json
We merge https://github.com/screwdriver-cd/data-schema/pull/152 to make `scmContext` a required field. We have added the `scmContext` column in the database. But it failed the unit tests since `scmContext` is not in the pipeline mock data.
Fix the broken unit tests.
> fix: fix the unit tests to have scmContext in pipelines

- plugins/logging.js
- plugins/tokens/filter.js
- test/plugins/tokens.test.js
Currently if a user makes a GET request to `/v4/auth/token?api_token=(api token here)` while they have a session, the server logs will display the arguments that the path got called with, exposing the token.
This PR adds a transform stream to the `hapi/good` list of streams that filters out anything that looks like one of our API tokens from the logs.
https://github.com/hapijs/good/blob/master/API.md#options
I did a quick search, I don't think we had an issue for this.
> fix(tokens): don't show tokens in server logs

- package.json
- plugins/templates/README.md
- plugins/templates/get.js
- test/plugins/templates.test.js
Users should be able to get a template by using the endpoint `/templates/{name}/{version}` or `/templates/{name}/{tag}`.
This PR will modify the original `/templates/{name}/{version}` endpoint to also accept `{tag}` instead of `{version}`.
_Not sure if there's a better name for `versionOrTag`.._
- Original issue: https://github.com/screwdriver-cd/screwdriver/issues/616
- Blocked by: https://github.com/screwdriver-cd/models/pull/179
- Related to: https://github.com/screwdriver-cd/screwdriver/pull/647
> feat(616): Can get a template using template name and tag

- bin/server
- lib/server.js
- plugins/templates/README.md
- plugins/templates/createTag.js
- plugins/templates/index.js
- plugins/templates/removeTag.js
- test/plugins/templates.test.js
This PR allows tagging a template, similar to how docker tagging works.
- 1 tag can only map to 1 version
- 1 version can have multiple tags
Example:
| id | name | tag | version | 
|---|---|---|---|
| 1 | mytemplate | stable | 1.2.0 | 
| 2 | mytemplate | latest | 1.2.0 | 
Add 2 routes for template tagging: CREATE and DELETE. 
UPDATE uses the same route as CREATE: send a `PUT templates/{templateTag}/tags/{tagName}` with the payload as: `{version}` instead of the usual `/id`, since it doesn't make sense that users need to look up the `id` to update.
DELETE: `DELETE templates/{templateTag}/tags/{tagName}`
**Notes:**  This only allows `build` scope to tag template due to security reasons. It will check if the build belongs to the pipeline that publishes this template. If not, then the build …
> feat: Add create and remove template tag routes

- package.json
- plugins/collections/README.md
- plugins/collections/get.js
- plugins/collections/index.js
- plugins/collections/list.js
- test/plugins/collections.test.js
- test/plugins/data/collection.json
- test/plugins/data/collection.response.json
- test/plugins/data/collections.json
For collections, we need to be able to LIST all of a user's collections as well as be able to GET a particular collection from the id.
This PR adds the GET and LIST routes for collections
Issue: #523 
PR regarding schema discussion: [screwdriver-cd/data-schema#162](https://github.com/screwdriver-cd/data-schema/pull/162)
> feat(523): Add GET and LIST routes to collections

- plugins/tokens/filter.js
- test/plugins/tokens.test.js
In my [last pull request](https://github.com/screwdriver-cd/screwdriver/pull/642) I removed anything that looked like a token from the logging, but forgot that some tokens were the incorrect length because they were generated before [this PR](https://github.com/screwdriver-cd/models/pull/181)
Rather than looking for "things that look like tokens", the log will now just suppress any parameters that get passed to `GET /v4/auth/token`.
https://github.com/screwdriver-cd/screwdriver/pull/642
https://github.com/screwdriver-cd/models/pull/181
> fix(tokens): don't show params on GET /auth/token

- plugins/auth/login.js
- plugins/templates/get.js
- test/plugins/templates.test.js
Moving logic to `models`. Since the same logic needs to be used by `config-parser`. Related: https://github.com/screwdriver-cd/config-parser/pull/41
Change is blocked by the actual model change. 
Since `models` **will** have logic to check version and tag, it makes sense to just use it directly, instead of handling the logic here. 
https://github.com/screwdriver-cd/screwdriver/issues/616
> fix(616): refactor GET template, move logic to models [3]

- plugins/collections/README.md
- plugins/collections/get.js
- plugins/collections/index.js
- plugins/collections/update.js
- test/plugins/collections.test.js
- test/plugins/data/updatedCollection.json
This PR adds an UPDATE route for collections so that you can modify the name, description, or pipelineIds for the pipelines in the collection
Issue: #523
> feat(523): Add UPDATE route for collections

- plugins/webhooks/index.js
- test/plugins/webhooks/index.test.js
Reverts screwdriver-cd/screwdriver#649
It's breaking functional tests
> fix: Revert Skip builds when commit message includes [skip ci]

- plugins/collections/create.js
- plugins/collections/update.js
- test/plugins/collections.test.js
- test/plugins/data/collection.json
Currently, the CREATE and UPDATE routes still pass in pipelineIds in the payload even though the ids might be invalid.
This PR adds in checks to the CREATE and UDPATE routes for collections to ensure that only valid ids of pipelines will be passed in to the config to create / update the collection.
Issue: #523
> refactor(collections): Add checks for CREATE and UPDATE routes

- plugins/collections/create.js
- plugins/collections/update.js
- test/plugins/collections.test.js
Currently, when the API route is calling the `pipelineFactory.get` method, the calling object is the map function which causes an error:
This PR makes sure that the calling object for the `pipelineFactory.get` method is `pipelineFactory`
Issue: #523
> fix(collections): Fix bug in CREATE and UPDATE collections

- README.md
As a result of a user observation, it was noted that users should be able to get to the homepage, documentation, and contributing guide from the Screwdriver repository.
> fix: Update README with links to docs and contributing

- config/custom-environment-variables.yaml
- config/default.yaml
The executor queue needs to be able to talk to redis in order to put jobs where the workers can see them.
This PR adds configuration options to pass in information about redis.
[Executor Queue](https://github.com/screwdriver-cd/executor-queue)
https://github.com/screwdriver-cd/screwdriver/issues/431
[ioredis (package we're using to connect to redis)](https://github.com/luin/ioredis/blob/master/API.md#new_Redis_new)
> feat(queue): add config for queue

- features/collections.feature
The team started working on the [homepage favorites](https://github.com/screwdriver-cd/screwdriver/issues/523) prior to creating a cucumber-js feature file. This feature file helps define scenarios that a user is expected to interact with the Screwdriver API and assert that the results are sane.
Create a feature file for collections, asserting that the user can use the API in order to create, list, update, and delete collections.
* Issue #523 
EDIT1: fixed link
> [523]fix: define feature scenarios for collections

- bin/server
- package.json
After taking a security workshop, I learned that sha256 is not a secure way to store passwords. PBKDF2 is much better, as it takes longer (making it harder to crack).
This new algorithm will invalidate all previously generated tokens, of which there are about 5 on cd.screwdriver.cd (all of which belong to us).
This PR pulls in the new `models` package to make use of the more secure password hashing algorithm for tokens.
https://github.com/screwdriver-cd/models/pull/185
> fix(tokens): use pbkdf2 to store tokens

- bin/server
- package.json
Missed one change in the `models` that didn't get caught because I also forgot to modify the tests for it. Reverting https://github.com/screwdriver-cd/screwdriver/pull/697 so that the pipeline isn't blocked while I fix things.
Tokens will still be functional after this revert, but will not use the new hashing algorithm yet.
Reverts https://github.com/screwdriver-cd/screwdriver/pull/697
> Revert "fix(tokens): use pbkdf2 to store tokens"

- config/custom-environment-variables.yaml
We need scms config as json, so that when user wants to have multiple scms, they are not tied to the `github` one we currently have.
They can have multiple scms defined in SCM_SETTINGS.
I have updated beta and prod to have SCM_SETTINGS secret.
> fix: read scms config as json

- config/default.yaml
When a user specifies a different yaml, the default is merged with theirs. This can lead to issues if users have scm preferences that don't involve the default (Github).
This PR comments out the default Github scm so that users are not forced to have it.
Related to multiple SCMs.
> fix: Remove Github scm from default yaml

- config/custom-environment-variables.yaml
The example configuration given for node-redis is incorrect, `password` needs to be inside an `options` object.
https://github.com/screwdriver-cd/queue-worker/pull/14/files
> Fix redis connection

- config/default.yaml
Seeing error after merging https://github.com/screwdriver-cd/screwdriver/pull/704:
```
Error: Configuration property "scms" is not defined
```
This PR is trying to fix that error.
> fix: Put empty object as default scms

- config/default.yaml
It seems somehow a space got into the whitelist, which was preventing drewfish from logging in.
> fix(config): fix drewfish entry on whitelist

- bin/server
- features/scripts/create-test-user.js
- package.json
Tokens were previously hashed with SHA256, which is too fast to be resilient to brute force attacks.
`screwdriver-models@26.0.0` changes how tokens are stored to use PBKDF2, a more secure algorithm. It also takes in a server-side salt.
Use PBKDF2 to hash tokens in a more secure manner.
https://github.com/screwdriver-cd/models/pull/191
> feat(tokens): use pbkdf2 to securely store tokens

- features/step_definitions/collection.js
In my last PR for functional tests, I had changed the error message generated when a user tries to create a duplicate collection but forgot to update the functional test for it.
This PR fixes the functional test that checks to make sure a user cannot create a duplicate collection with the same name.
Previous PR: #731 
Issue: #523
> fix(collections): Fix error in collections functional test

- features/step_definitions/collection.js
In the step_definitions of collection, a request method does not be returned in 'they update the collection "myCollection" with that pipeline' step. Therefore, sometimes this step finishes before the request method is finished.
Because of this, Update Existing Collection test failed sometimes. (Like [this](https://cd.screwdriver.cd/pipelines/1/builds/10145))
I fixed to return the request method.
> fix: Fix collection step_definitions

- package.json
- plugins/auth/index.js
- test/plugins/auth.test.js
Context:
========
`hapi-auth-jwt` requires an old version of jsonwebtoken (5.x), which depends on ms which has a ReDoS vulnerability.
Objective:
----------
Replace `hapi-auth-jwt` with `hapi-auth-jwt2` which is being actively maintained.
> fix: regexp dos with hapi-auth-jwt

- bin/server
- config/custom-environment-variables.yaml
- config/default.yaml
- in-a-box.py
Context:
=========
Running screwdriver api locally via sd-in-a-box or `npm start` will result in errors like the following:
```
api_1    | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:9999
api_1    |     at Object.exports._errnoException (util.js:1020:11)
api_1    |     at exports._exceptionWithHostPort (util.js:1043:20)
api_1    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
```
Objective:
----------
Allow executors to not be loaded by providing an environment variable for each executor. When the value of the env variable is false, the executor will not be loaded.
Example:
```
export EXECUTOR_QUEUE_ENABLED="false"
```
This allows the queue configuration to be easily disabled even in the docker container.
Addresses: …
> fix(718): Add ENV variables to disable executor mechanisms

- plugins/templates/listVersions.js
Need param of `name` on [API Documentation](https://api.screwdriver.cd/v4/documentation#!/v4/getV4TemplatesName), isn't it?
> fix: Update listVersions.js

- .github/ISSUE_TEMPLATE.md
This is too long and users usually just delete & ignore them. Making this simpler.
> fix: simplify issue template

- config/custom-environment-variables.yaml
- config/default.yaml
- plugins/webhooks/index.js
- test/plugins/webhooks/index.test.js
Some projects would have bots commit back to the repo, for example, to update a package.json, etc. This will cause builds to run indefinitely. 
This PR allows ignoring commits made by certain users
> feat: ignore commits made by certain users (bots)

- README.md
- features/support/world.js
The README was missing a couple environment variables needed for local functional testing. The environment variable names were also kind of vague.
This PR updates the README with functional testing changes and modifies the environment variables to be a little more easy to understand.
> fix: Fix up functional test README and var names

- bin/server
Context:
========
We want the queue workers to be reponsible for routing to the correct executor instead of the API.
Objective:
----------
Make the api executor configuration setup the default executor directly and remove the executor router. This will cause the job's executor annotations to be ignored until they are processed by queue workers. This should not have any effect on api installations that are using a default executor that is not queue, e.g. sd-in-a-box.
> feat(725): remove executor router from api

- test/plugins/data/validator.output.json
Fix broken tests:
Now we generate `workflowGraph` in the parsed config.
> fix: fix validator tests with workflowGraph

- plugins/webhooks/index.js
- test/plugins/auth.test.js
- test/plugins/webhooks/index.test.js
Support new workflow in `push` event:
If the pipeline has `workflow: undefined` then it's using the new workflow:
- Create new event with `workflow` field as `undefined` for now, will do `source, destination` later
- Start all jobs with `requires: '~commit' `
Added a test for `auth/token.js` to make coveralls happy!
Related to https://github.com/screwdriver-cd/screwdriver/issues/723
Blocked by: https://github.com/screwdriver-cd/models/pull/195
> feat: support new workflow in push event

- package.json
- plugins/webhooks/index.js
- test/plugins/webhooks/index.test.js
For PR opened event, start all the jobs that has `~pr`, create them as `[PR-1:jobName]` (For example: PR-1:main, PR-1:component). Update if the jobs already exist. 
The change should be backward compatible for the old workflow design. Hence, no test change required.
Related: https://github.com/screwdriver-cd/screwdriver/issues/723
> feat(723): support new workflow for PR events

- features/support/sdapi.js
The current functional git flow tests are failing because they are hardcoded to look for job name `PR-number`. 
This PR changes the function to look for job names that start with `PR-number`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/723
> fix: Update functional test with new PR job name

- package.json
- plugins/builds/update.js
- test/plugins/builds.test.js
- Trigger next job using workflowGraph instead of workflow
When a build tries to update its status with `PUT /builds`, the pipeline must synced already and has the `workflowGraph` field. So this change is backward compatible and will work for both legacy and new config.
Will switch to user `pub-sub` to handle triggers in next pass.
Related to ttps://github.com/screwdriver-cd/screwdriver/issues/723
> feat: trigger next job using workflow parser

- bin/server
Context:
========
The docker executor (and likely others) require data from the api ecosystem when setting up
Objective:
----------
Properly pass ecosystem config object into executor.
> fix: pass ecosystem vars properly to executors

- plugins/events/create.js
- test/plugins/events.test.js
`sha` is needed no matter is PR or not.
https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/create.js#L81
> fix:need to pass in sha for both pr and commit

- lib/registerPlugins.js
- test/lib/registerPlugins.test.js
Now we can't use scoped notification package.
Due to this change user can use scoped notification package by setting "scope" in config file.
Change how to require notification packages.
If you set "scope" at notifications config, you can use scoped notifications package. Also you can set scope value both "@xxx" and "xxx".
> feat: support notification scoped package

- plugins/webhooks/index.js
- test/plugins/webhooks/index.test.js
There was a bug introduced when we made changes to the workflow that sets a closed PR to DISABLED when a PR is closed. Since we never explicitly set the PR back to `ENABLED`, subsequently run PRs will fail if they are reopened.
This PR does not set the PR job to `DISABLED` when a PR is closed.
Related to https://github.com/screwdriver-cd/screwdriver/pull/756
> fix: Do not set PR to DISABLED when PR is closed

- plugins/builds/update.js
- test/plugins/builds.test.js
- Group jobs in same pipeline that triggered by external trigger into a single event
Blocked by https://github.com/screwdriver-cd/models/pull/204
Related to https://github.com/screwdriver-cd/screwdriver/issues/770
> fix: group jobs triggered externally by pipeline

- plugins/builds/index.js
- plugins/builds/update.js
- test/plugins/builds.test.js
Support Join Trigger
Example:
```
A: 
requires: [~B, C,D]
```
joinList of A = [C,D]
- When B is successful, trigger A (since B is not in the joinList)
- When C is successful, check if D is successful. If yes, trigger A. If no, do nothing. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/700
> feat(700): support join trigger

- features/step_definitions/sd-step.js
The build actually passed https://beta.cd.screwdriver.cd/pipelines/375 but it just took a bit longer.
Bump the timeout to make the pipeline pass.
https://cd.screwdriver.cd/pipelines/1/builds/12495
> fix: increase timeout for sd-step functional test

- features/support/github.js
In addition https://github.com/screwdriver-cd/screwdriver/pull/784, [node-github](https://github.com/octokit/node-github) should be also set configuration for using GHE.
This PR adds configurations when create Github constractor. If `TEST_SCM_HOSTNAME` is not set, default values are used.
https://github.com/octokit/node-github
> fix: use environment variable on github.js

- lib/registerPlugins.js
- test/lib/registerPlugins.test.js
https://github.com/screwdriver-cd/screwdriver/pull/772 enabled to use scoped packages for notification modules. But when scope is set, validation error is happened. 
I think we should not fix all notification modules. So this PR changes notifications schema.
New notifications schema is like below:
```
email:
config:
host: foo
port: bar
from: baz
scopedPackage: '@module/package'
```
If "scopedPackage" is set, the "module" is required. If "config" is set, the contents of "config" is passed to a notification module.
The previous schema is also accepted for backward compatibility.
Related: https://github.com/screwdriver-cd/screwdriver/issues/775
> fix(775): add module field to notification modules.

- config/custom-environment-variables.yaml
- config/default.yaml
Although the Redis server may have a TLS proxy in front of it, the clients must also be configured to communicate to it via TLS. This change allows a configuration flag to be available for cluster maintainers to enable this feature.
This feature does _NOT_ support self-signed certificates.
Allow a flag for configuring the Redis client to communicate with the Redis server via TLS.
> feat: configuration flag for enabling Redis TLS communication

- package.json
- plugins/builds/update.js
- test/plugins/builds.test.js
save statusMessage to build during update if there is one
Related to https://github.com/screwdriver-cd/screwdriver/issues/694
https://github.com/screwdriver-cd/data-schema/pull/194 merged
> fix(694): save statusMessage to build during update

- config/custom-environment-variables.yaml
- config/default.yaml
The NPM module `sequelize` allows a configuration object to be passed to the underlying constructor. Assuming the library/dialect we're using supports SSL/TLS connections, this means we can also enable settings for SSL/TLS. For example, Postgres uses the NPM module `pg` which uses SSL configurations passed in.
Allow the ability to set SSL/TLS configurations for the database connection.
* https://node-postgres.com/features/ssl
* `sequelize` references to passing SSL configurations
* https://github.com/sequelize/sequelize/blob/3f5927f5bb47db85f5e0401d5a876f652fef1cd3/docs/migrations.md#dynamic-configuration
* https://github.com/sequelize/sequelize/blob/4660d0c1c9396624a4799959432c43f9eb1c7ad4/docs/usage.md#options
> feat: allow SSL/TLS configuration for datastore connection

- features/sd-cmd.feature
Currently we can't share binaries or scripts across multiple containers to use some commands in all containers. We need a single interface for executing a versioned command during a build.
This PR adds feature file for sd-cmd functional testing.
https://github.com/screwdriver-cd/screwdriver/blob/master/design/commands.md
> add sd-cmd feature.

- plugins/pipelines/update.js
- test/plugins/data/updatedPipeline.json
- test/plugins/pipelines.test.js
Fixing this bug: https://github.com/screwdriver-cd/screwdriver/issues/780
**Notes:**
I deleted an assertion because it seems useless:
- `updatedPipeline` is read from `./data/updatedPipeline.json`
- We mock `pipeline.toJson` to return `updatedPipeline`
- We assert `reply.result` (which is what got returned from `pipeline.toJson`) to equal `updatedPipeline`. 
This assertion will always pass since we basically mock and then assert if it's equal to the mock. I'm opened to suggestions on how to test this better.
> fix: update scmContext and scmRepo when update pipeline

- plugins/builds/index.js
- plugins/builds/update.js
- test/plugins/builds.test.js
To allow meta to be passed when triggered by an external pipeline
When create an event, also pass in the current build id, this will be the `parentBuildId` to create builds with. 
https://github.com/screwdriver-cd/screwdriver/issues/771
> fix(771): allow meta to be passed for external triggered

- config/default.yaml
Hoping to experiment with cd.screwdriver.cd for Vespa open source builds.
Preparing to run Vespa open source builds on cd.screwdriver.cd.
@stjohnjohnson : FYI
> Adding Vespa team members for pilot

- features/support/sdapi.js
Now Screwdriver uses new workflow and not to need to use main. But in tests we can't find builds without main. 
Sometime this make it difficult to create new acceptance tests.
Add jobName option to searchForBuild and allow user to find any job.
> fix: allow to search any build

- config/custom-environment-variables.yaml
- config/default.yaml
Pass in resources config in executor config.
That way we can override the hard coded default value inside the executor plugin.
Waiting for: https://github.com/screwdriver-cd/executor-k8s/pull/68
> fix: add resources config in executor config

- design/commands.md
I am implementing commands data-schemas now.
https://github.com/screwdriver-cd/data-schema/pull/195
I think we should add `command` optional key  to the Docker format that allows users not to set an extra executable (knife, ...).
And we should rename `binary` key of the Habitat format to `command`.
Please review it.
https://github.com/screwdriver-cd/data-schema/pull/195#discussion_r157115519
> fix: improve command format spec.

- package.json
- plugins/auth/index.js
We would like to issue one time use build JWT tokens for improved security.
This PR adds a guid to the JWT token and changes the timeout from 12h to 2h.
Design doc: https://github.com/screwdriver-cd/screwdriver/blob/master/design/auth.md
Related to: https://github.com/screwdriver-cd/hapi-auth-dynamic-jwt/blob/master/index.js#L163
jsonwebtoken npm: https://www.npmjs.com/package/jsonwebtoken
uuid npm: https://www.npmjs.com/package/uuid
> fix: Adding guid to JWT and changing timeout to 2h

- config/custom-environment-variables.yaml
- config/default.yaml
We intend to support k8s toleration when creating pods so that k8s admins can specify taints on k8s nodes where they want the builds to be scheduled 
This adds config for toleration to be used in `executor-k8s-vm`
#827
> feat(827): add config for tolerations

- design/commands.md
`command` key of a `command` object/configuration seems to provoke bugs easily.
e.g. `command.command` key reference.
We should rename  `command`  key to `name`.
Please review it.
> fix: rename `command`  key to `name`.

- plugins/pipelines/list.js
- test/plugins/data/pipelinesFromGitlab.json
- test/plugins/pipelines.test.js
Sometimes a DB might be shared by multiple clusters. It's confusing when pipelines with scmContexts that are not configured for that specific cluster show up on the UI. 
This PR changes the pipeline `/pipelines` endpoint to only return pipelines that match the cluster's configured scmContexts.
> fix: Only return pipelines that match the cluster's scmContexts

- features/step_definitions/sd-step.js
I checked the functional build. It actually passed, but for some reason took a long time. So the functional test failed. Temporarily changing this value to unblock the pipeline.
> fix: bumping timeout for sd-step

- config/default.yaml
I'm not whitelisted for https://cd.screwdriver.cd.
This PR will whitelist me, so I can use https://cd.screwdriver.cd
> Fix username for ScottyFillups (Philip Scott)

- plugins/templates/index.js
- plugins/templates/listTags.js
- test/plugins/data/templateTags.json
- test/plugins/templates.test.js
It's hard for users to figure out what tags are available for each template and what versions they correspond to. It would be nice to have an endpoint where we could list the available tags for a specific template name.
Create an endpoint, GET `/templates/{name}/tags`, which returns template tags.
> feat(842): Add route for getting template tags

- features/step_definitions/git-flow.js
currently it's getting the status for the old PR builds and that's failing the function tests. Wait longer to get the right status
> fix: bump the wait time

- config/default.yaml
add an example for slack config
Related to https://github.com/screwdriver-cd/screwdriver/issues/687
> fix: add an example for slack config

- bin/server
- lib/server.js
Sharing Commands feature.
This PR add missing command factories (`commandFactory`, `commandTagFactory`) registration.
none.
> fix: add missing command factories registration.

- plugins/commands/create.js
- test/plugins/commands.test.js
- test/plugins/data/command.json
Like `template`, to limit a pipeline which updates the command only a pipeline which created the command, I add a `pipelineId` to the `command`. Then, I use `pipelineId` in API to deny publishing command from unauthorized pipeline.
Like `plugins/templates/create.js`, it compares request's pipelineId and command's pipelineId to deny publishing command from unauthorized pipeline.
Related PRs
- data-schema https://github.com/screwdriver-cd/data-schema/pull/199
- models https://github.com/screwdriver-cd/models/pull/211
Unit tests will fail for the moment, because it requires new `command` data-schema.
https://github.com/screwdriver-cd/data-schema/pull/199
> feat: limit pipeline that can update command

- plugins/builds/steps/logs.js
Session strategy is interfering with token strategy and proxy requests to store are failing. Trying to see if removing session strategy will make hapi to populate headers.
> fix: use only token strategy for auth

- plugins/commands/create.js
- plugins/templates/create.js
Currently, create APIs of commands and templates do not return useful error messages to a malformatted request like the following example.
- POST data sample
```
{"yaml":"{\"namespace\":\"foo\",\"invalid name\":\"bar\",\"version\":\"1.1.2\",\"description\":\"Command for habitat git\\nExecutes git commands\\n\",\"maintainer\":\"foo@bar.com\",\"format\":\"habitat\",\"habitat\":{\"mode\":\"remote\",\"package\":\"core/git/2.14.1\",\"command\":\"git\"}}"}
```
- Response body
```
{
"statusCode": 400,
"error": "Bad Request",
"message": "Command has invalid format: ",
"data": "[object Object],[object Object]"
}
```
This PR enables APIs to return the following response to the same request.
```
{
"statusCode": 400,
"error": "Bad Request",
"message": "Command has invalid format: 2 error(s).", …
```
> fix: Create APIs of commands & templates not return useful error message

- plugins/auth/index.js
- plugins/auth/login.js
- plugins/auth/token.js
- test/plugins/auth.test.js
Currently, if you have an existing JWT you can renew it by hitting `/auth/tokens`.  This defeats the expiration that was put into place.
Give back the single JWT that was generated.  Don't give out new tokens.
> fix: Preventing users from renewing their existing JWTs

- plugins/commands/README.md
- plugins/commands/index.js
- plugins/commands/list.js
- test/plugins/commands.test.js
- test/plugins/data/commands.json
Like `template`, we need an endpoint that can get all commands to show all commands in UI.
Like `GET /templates` endpoint, I added an endpoint that gets all commands.
Related #677
> feat(677): Add list command endpoint

- config/custom-environment-variables.yaml
- config/default.yaml
- plugins/auth/index.js
- test/plugins/auth.test.js
Generate an additional field `jwtEnvironment` to indicates what environment this jwt should be generated for. By default it is `''`. We can set this to `test` or `beta` for our beta environment.
> feat: add jwtEnv

- plugins/auth/index.js
- test/plugins/auth.test.js
Only generate this field if the value is not empty
> fix: do not generate jwt with empty environment

- Dockerfile
- Dockerfile.local
- screwdriver.yaml
We are having security vulnerabilities in some of our packages. But some of the latest pkgs require node:8.
> fix: use node:8 as image

- plugins/commands/README.md
- plugins/commands/index.js
- plugins/commands/listVersions.js
- test/plugins/commands.test.js
- test/plugins/data/commandVersions.json
Like `template`, we need an endpoint that can get all versions of commands to show all versions of commands in UI.
Like `GET /templates/{name}` endpoint, I added an endpoint that gets all versions of commands.
Related #677
> feat(677): Add listVersion command endpoint

- design/commands.md
We had discussed about filename of sd-cmd.
As a result, we'd like to use ```sd-command.yaml``` as a default filename.
Defining ```sd-command.yaml``` as the default filename of sd-cmd.
https://screwdriver-cd.slack.com/messages/C8F6DMR7W/
> fix: change default filename like sd-template.yaml

- package.json
- plugins/events/create.js
- plugins/pipelines/badge.js
- test/plugins/data/events.json
- test/plugins/events.test.js
We want to support user to restart from any event. To allow that, we need to pass in `sha` and `workflowGraph` from the `parentEvent` so that model can use those info to recreate the event.
Related to https://github.com/screwdriver-cd/screwdriver/issues/806
Blcoked by: https://github.com/screwdriver-cd/models/pull/224
> fix: pass info from parentEvent when create new event

- config/default.yaml
I would just like to have read access to Screwdriver's Screwdriver.
This reverts the unnecessary removal of my api read access
https://github.com/screwdriver-cd/screwdriver/commit/fff6300043d940e5ff0fd6bd9bed2f54a522d62a#diff-fe7044f2ecd69c76ce484ad03fabc12fL35
> Whitelisting a really impressive-sounding user

- config/default.yaml
per @stjohnjohnson's request. 
This is specific to our cluster (cd.screwdriver.cd) and shouldn't be configured by default. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/901
~~Blocked by: I need to set some configurations first before merging this~~
> fix: remove default whitelist/admins

- package-lock.json
- plugins/builds/update.js
- test/plugins/builds.test.js
This PR updates the event meta data when updating a build. 
The new meta should be merged into the event meta. If they have the same key, the new meta will override the old one. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/904
Blocked by: https://github.com/screwdriver-cd/data-schema/pull/209
> feat(904): support event meta

- plugins/commands/README.md
- plugins/commands/createTag.js
- plugins/commands/index.js
- test/plugins/commands.test.js
- test/plugins/data/commandTags.json
Like `template`, we need an endpoint that can create or update command tag.
Like `PUT /templates/{name}/tags/{tagName}` endpoint, I added an endpoint that create or update command tag.
related #677
> feat(677): Add create or update command tag endpoint

- .gitignore
- plugins/builds/index.js
- test/plugins/builds.test.js
- fix a bug when the dfs function cannot end if there is a job has no build in parent event
- add package-lock.json to gitignore so that we can rerun pipelines to pull in new dependencies and not locked
> fix: fix dfs join trigger

- plugins/auth/index.js
- plugins/auth/login.js
When trying to login with Guest mode, we get the following message:
```
[request,server,error] data: TypeError: Uncaught error: Cannot read property 'getDisplayName' of undefined
at ScmRouter.getDisplayName (/usr/src/app/node_modules/screwdriver-scm-router/index.js:353:45)
```
Allow users to login via Guest Mode.
- https://github.com/screwdriver-cd/screwdriver/issues/870
> fix: Don't check admin list when in guest mode

- plugins/builds/index.js
- test/plugins/builds.test.js
Currently, `nextBuild` is always `null`, so it doesn't go to `update` or `remove` at all. 
This PR fixes it to check if build exists based on `jobId` instead of `jobName`
> fix: find by jobId

- screwdriver.yaml
Currently, in beta and prod deployment jobs, we always get the latest tag and try to deploy that version. That way we cannot really roll back to a previous event.
This PR will save `docker_tag` in meta during publish job. Beta and prod will just read from that meta.
> fix: save docker_tag in meta

- plugins/builds/index.js
- test/plugins/builds.test.js
Update the build status to QUEUED before starting
Related: https://github.com/screwdriver-cd/screwdriver/issues/904
> fix: update build status

- plugins/builds/index.js
- test/plugins/builds.test.js
Sorry there was a bug. It's getting `jobId` instead of `buildId` since `joinList` actually contains only the job ids. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/904
> fix: get buildIds

- README.md
- package.json
Pull in the new `scm-router`, which has the new `scm-base`
Blocked by: https://github.com/screwdriver-cd/scm-router/pull/6
Related: https://github.com/screwdriver-cd/screwdriver/issues/911
> fix: pull in new scm-router

- plugins/webhooks/index.js
`scm-router` needs `scmContext` to figure out which `scm` it is to call `getChangedFiles`: https://github.com/screwdriver-cd/scm-router/blob/master/index.js#L285
Related: screwdriver-cd/screwdriver#911
> fix: pass in scmContext to changedFiles

- plugins/pipelines/badge.js
- test/plugins/data/events.json
I found that badges for recent builds are broken because of inappropriate access to `workflow` object.
https://api.screwdriver.cd/v4/pipelines/1/badge
Currently, `workflow` is undefined for recent builds.
https://api.screwdriver.cd/v4/events/13472
I fixed the badge feature by avoiding access to undefined object.
Also I removed `workflow` key from an event mock. I think it is time to remove `workflow` key due to deprecated config and there will be no development for that.
> fix: broken badge

- screwdriver.yaml
If you have multiple tags attached to same `sha`, `git describe --tags ` will give you the oldest one. That makes it impossible to re-run the pipeline and pull in dependencies without code change. 
This PR will use the latest npm tag instead. 
`npm dist-tag ls` will give you the latest tag like this `latest: 0.5.278`.
We will parse it and make it `v0.5.278` eventually
> fix: set docker_tag with latest npm tag

- config/custom-environment-variables.yaml
- config/default.yaml
`executor-k8s` does not support adding tolerations config.
This PR adds tolerations config.
Related: https://github.com/screwdriver-cd/screwdriver/issues/845
Similar Update: https://github.com/screwdriver-cd/screwdriver/pull/828
> feat(845): add config for tolerations to k8s

- package.json
I fixed artifact-bookend, so I updated package.json to use latest artifact-bookend package.
Related: https://github.com/screwdriver-cd/artifact-bookend/pull/13
> fix: bump artifact-bookend version

- config/custom-environment-variables.yaml
- config/default.yaml
Add an ability to configure preferred node affinity like https://github.com/screwdriver-cd/screwdriver/issues/827.
This PR adds `preferredNodeSelectors` to be able to use `preferredDuringSchedulingIgnoredDuringExecution` config in the pod execution.
- Related: https://github.com/screwdriver-cd/screwdriver/issues/972
- Similar PR: https://github.com/screwdriver-cd/screwdriver/pull/828
- [Node affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature)
> feat(972): add preferredNodeSelectors config to api

- package.json
datastore-sequelize 5.X introduces pagination change: https://github.com/screwdriver-cd/datastore-sequelize/blob/master/index.js#L326
But models is not ready for it, it's only returning partial results now. It's giving us this err since it's trying to recreate a job that already exists:
```
[request,server,error] data: SequelizeUniqueConstraintError: Validation error
```
> fix: pin datastore-sequelize to major 4.X.X

- plugins/auth/contexts.js
- plugins/auth/login.js
- plugins/auth/logout.js
- plugins/builds/steps/update.js
- plugins/stats.js
- plugins/status.js
- plugins/versions.js
- test/plugins/stats.test.js
There are response object schemas missing for several endpoints as detailed in screwdriver-cd/screwdriver#115
Pending merging of https://github.com/screwdriver-cd/data-schema/pull/222
Swagger documentation:
https://api.screwdriver.cd/v4/documentation
> fix(115): Add response schemas for versions, contexts, stats, and status

- config/custom-environment-variables.yaml
We cannot set other selectors if we want to use other selectors with multiple executors (i.e. k8s and k8s-vm).
This PR fixes this problem.
Related: https://github.com/screwdriver-cd/screwdriver/issues/996.
> feat(996): rename to K8S_VM_NODE_SELECTORS for api

- features/support/github.js
It was a pain deleting them: https://github.com/screwdriver-cd-test/functional-git/pull/3803
Now creating the files under `testfiles` directory so once in a while we just need to clean up the directory while keeping other necessary files.
> fix: functional-git create files inside testfiles

- features/step_definitions/authorization.js
- features/step_definitions/secrets.js
Currently, it's starting the wrong job:
the `/jobs` endpoint sorts by `workflow` if `workflow` is there, but since we don't have it anymore, the order is not guaranteed. We cannot get the first element and assume it's the `main` job. 
Instead, we can create a new event with `startFrom` as `main`, and it will create the `main` build.
> fix: fix functional tests for the new workflow

- package.json
Builds are currently failing due to a version mismatch with Joi; the `package-lock.json` file in the data-schema is set to `13.1.2`.
* Fix issues related to `screwdriver-data-schema` by pinning Joi version
> fix: Pin Joi version to 13.1.2

- .gitignore
- plugins/templates/create.js
- test/plugins/templates.test.js
We shouldn't allow PR to publish templates.
We store if the build JWT is from PR inside the field `isPR`.
https://github.com/screwdriver-cd/models/blob/0f8868e4645628429e2efd416dc25265db90aa4b/lib/build.js#L163
> fix: do not allow PR to publish templates

- config/default.yaml
Forgot to add default build timeout values
Related to https://github.com/screwdriver-cd/screwdriver/pull/1031, https://github.com/screwdriver-cd/screwdriver/issues/545
> fix(545): Add default build timeout settings

- package.json
Pull in new executor-k8s-vm.
Version 2 has been out for a while...
> fix: pull in new executor-k8s-vm

- config/default.yaml
- package.json
Need to pull in email notifications change to allow username and password in config.
Related to https://github.com/screwdriver-cd/notifications-email/pull/11
> fix: Email notifications allow username and password config

- plugins/pipelines/listEvents.js
- test/plugins/pipelines.test.js
so that we could identify what type of event we have, whether it's pipeline or pr
to allow us to have prs in the type property of event objects
https://github.com/screwdriver-cd/screwdriver/issues/796
> feat(796): add possibility of pr to type property of event objects

- features/step_definitions/collection.js
Delete a collection shouldn't need to check if pipeline exists. This is making the step flaky.
> fix: remove unnecessary check in functional tests

- features/collections.feature
- features/step_definitions/collection.js
We're only deleting the collection. No need to do the extra check for pipelines otherwise we need to always make sure that pipeline exists
> fix: remove unnecessary func test step

- plugins/events/create.js
- plugins/pipelines/remove.js
- plugins/pipelines/update.js
- test/plugins/events.test.js
- test/plugins/pipelines.test.js
- A child pipeline cannot update its checkoutUrl and delete the pipeline.
- Pass `configPipelineSha` for child pipeline restart event 
Related to https://github.com/screwdriver-cd/screwdriver/issues/937
> feat(937): restrict permissions for child pipelines

- design/commands.md
We should publish a sd-cmd with a tag for verifying commands and practical promote.
This PR updates design doc.
Related: https://github.com/screwdriver-cd/screwdriver/issues/677
> fix(677): update design/commands.md about publish with tag

- plugins/pipelines/README.md
- plugins/pipelines/index.js
- plugins/pipelines/list.js
- plugins/pipelines/startAll.js
- plugins/pipelines/update.js
- test/plugins/pipelines.test.js
- add start all child pipelines endpoint
- allow to list pipelines by `configPipelineId`
Related to: https://github.com/screwdriver-cd/screwdriver/issues/937
> fix(937): add start all child pipelines endpoint

- plugins/tokens/list.js
I added a pipelineId with [this PR](https://github.com/screwdriver-cd/data-schema/pull/250) to implement pipeline API token. 
But the functional test failed due to this change.
https://cd.screwdriver.cd/pipelines/1/builds/41213
This is an error because [getSchema](https://github.com/screwdriver-cd/data-schema/blob/master/models/token.js#L65-L72) does not allow pipelineId. 
In user token, pipelineId should be empty, but the property itself exists.
So the getSchema validation failed.
```
[request,server,error] data: Error: "value" at position 0 fails because ["pipelineId" is not allowed]
```
This PR guarantees to delete pipelineId in token list API so that error does not occur with validation of getSchema.
https://github.com/screwdriver-cd/screwdriver/issues/614 …
> feat(614): delete pipelineId before adding it to data-schema

- plugins/auth/index.js
- test/plugins/auth.test.js
Functional tests is broken with the last PR merged saying that `lastUsed` of accessToken is not updated: 
https://cd.screwdriver.cd/pipelines/1/builds/44534
PR: https://github.com/screwdriver-cd/screwdriver/pull/1123
Because in that PR, it switch from `userFactory.get({ accessToken: xxx })` to `userFactory.get(token.userId)`. But inside the model, we only update t`oken.lastUsed` field when you're getting the user with accessToken.
> fix: get user by access token

- plugins/builds/create.js
- plugins/events/create.js
- test/plugins/builds.test.js
- test/plugins/events.test.js
Allow users to specify `meta` when creating an `event` or `build`
`POST` endpoint for `builds` and `events` should pass in `meta` from `request.payload.meta` to their respective factories.
https://github.com/screwdriver-cd/screwdriver/issues/1113
Pending:
* https://github.com/screwdriver-cd/models/pull/265
* https://github.com/screwdriver-cd/data-schema/pull/259
> feat(1113): Pass in meta from payload for create event and build

- plugins/auth/index.js
- test/plugins/auth.test.js
Currently, the `lastUsed` of pipeline token never be updated even if the token is used.
The [PR](https://github.com/screwdriver-cd/models/pull/267) of models  fix to update it when the pipeline is fetched by accessToken just like user token is doing.
This PR fix to get the pipeline by `accessToken` to udpate `lastUsed`.
Please merge this PR after the PR https://github.com/screwdriver-cd/models/pull/267 is merged.
https://github.com/screwdriver-cd/screwdriver/issues/614#issuecomment-399249412
> fix(614): get pipeline by access token

- plugins/builds/update.js
- test/plugins/builds.test.js
status message is not allowed to be empty string: https://github.com/screwdriver-cd/data-schema/blob/9893b3b79838c0a67ed3455c4c64fd62052121cf/models/build.js#L124-L128
> fix: set statusMessage to null if not set

- plugins/pipelines/tokens/refresh.js
- test/plugins/pipelines.test.js
In pipeline token, it doesn't return the updated value  when the token is refreshed as below. 
This PR fix it.
> fix(614): fix pipeline token refresh to return value

- features/step_definitions/collection.js
In our environment, the delete collection test exceeds default timeout (5000ms).
This PR add timeout to delete collection test with configured value.
> fix: [small] add timeout to delete collection test

- package.json
- plugins/builds/token.js
- plugins/secrets/index.js
- test/plugins/builds.test.js
Currently, when checking access to build secrets, only the `pipelineId` is checked.
https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/secrets/index.js#L61-L63
This will not work in the case of child pipelines since they inherit their parent pipeline secrets. Therefore, we include the `configPipelineId` as part of the JWT in order to check for it.
Pass in the `configPipelineId` as part of the `generateProfile` function in the `/builds/{id}/token` endpoint.
Also check if `configPipelineId` matches `secret.pipeline.Id`.
https://github.com/screwdriver-cd/models/pull/269
https://github.com/screwdriver-cd/screwdriver/issues/1150
> fix(1150): Check if config pipeline can access build secret

- features/support/world.js
Functional tests are failing. Some builds might take quite long. Increasing these values to make it retry more times.
> fix: increase retry

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
Branch specific job feature has that bug:
> If you have pipeline configured to branch `master` and a job configured to branch `foo`, the issue is when you restart the `foo` branch job, it uses `foo` screwdriver.yaml file instead of `master` screwdriver.yaml
To fix the bug, this PR provides the feature which obtains latest sha and adds the sha to event as `configPipelineSha`.
Related: https://github.com/screwdriver-cd/screwdriver/issues/1082#issuecomment-397195121
> fix(1082): [2] [small] add latest sha as configPipelineSha to webhook event

- bin/server
- config/custom-environment-variables.yaml
- config/default.yaml
Currently, we're using the `encryptionPassword` for two different purposes.
- encrypt/decrypt pipeline secrets/user Oauth token
- as a one way hashing key for aceess token 
https://github.com/screwdriver-cd/models/blob/master/lib/tokenFactory.js#L54
This PR will split it into two to serve its own purpose and for better key management.
> fix: split encryptionPassword

- plugins/auth/index.js
- test/plugins/auth.test.js
Need to allow hashingPassword to be part of the auth config
> fix: allow hashing password in auth config

- plugins/collections/list.js
With out guest scope collections  API returns `404`
Fixes broken pipeline page for guest access
https://github.com/screwdriver-cd/screwdriver/issues/1194
> fix(1194): add guest scope to collections API

- plugins/builds/steps/update.js
- test/plugins/builds.test.js
We add a new field `lines` for step in data-schema.
https://github.com/screwdriver-cd/data-schema/blob/master/models/build.js#L32
This PR is to allow that field to be updated.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1114
> feat: allow update number of lines for build step

- plugins/pipelines/index.js
- plugins/pipelines/remove.js
- test/plugins/pipelines.test.js
Currently, pipelines cannot be removed if its underlying repository does not exist.
Allow pipeline to be removed if `getPermissions` returns a 404 and only if `privateRepo` is disabled.
Pending:
- https://github.com/screwdriver-cd/scm-bitbucket/pull/52
https://github.com/screwdriver-cd/screwdriver/issues/450
> fix(450): Allow pipeline to be removed if repository does not exist

- plugins/builds/steps/logs.js
- test/plugins/builds.test.js
Log loading randomly failed to load old logs with more than 100 lines. 
After investigation, i think the cause is maxLines is a global variable and can be shared by all requests. It's possible when trying to get big logs, it's set to 1000 and requests after that cannot get logs with 100 lines.
> fix: fix log fetching for old logs

- plugins/builds/steps/logs.js
- test/plugins/builds.test.js
Now UI is not loading logs with 1000 lines per file if it's more than 10000 lines. Because we don't know where to start to figure the lines per file if it's not requesting from line 0.
Adding an additional call to always fetch page 0 and set lines per file based on that.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1114
> fix: fix log loading with compatibility

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
We set the build status message when a user aborts a build in the UI. It would be nice if we had an equivalent status message when the build is aborted because a PR is closed.
This PR adds a status message for aborted PR builds.
Issue: https://github.com/screwdriver-cd/screwdriver/issues/1211
> fix(1211): Display build aborted reason when a PR is closed

- plugins/commands/createTag.js
- test/plugins/commands.test.js
Now sd-cmd cannot promote tag by tag. 
Be able to promote tag with tag.
(e.g. 
```
sd-cmd promote hoge/huga latest stable
```
todo:
> fix: [1] able to promote tag by tag

- plugins/webhooks/index.js
We added the wait to ensure we will get latest config.
https://github.com/screwdriver-cd/models/pull/208
However, it is enough to wait before getChangedFiles is called. When PR webhook is occured, processing will through this point for sure.
I added promiseToWait before getChangedFiles is called.
original issue https://github.com/screwdriver-cd/screwdriver/issues/1220#issuecomment-417989327
related PR
models: screwdriver-cd/models#289
> fix(1220): [2][small] Move waiting for changedFiles from pipeline model

- package.json
This fixes a bug of missing files with Docker 18.03.0-ce.
Change in executor-docker
- https://github.com/screwdriver-cd/executor-docker/blob/b511eedee2e01c22d7d401f186c00fbdae3aca15/index.js#L175
Related issue: https://github.com/screwdriver-cd/screwdriver/issues/979
> fix(979): pull in new executor-docker

- plugins/pipelines/README.md
- plugins/pipelines/list.js
- test/plugins/pipelines.test.js
Since we're adding pagination for pipelines, we can no longer have search functionality stored in the UI. 
This PR passes search field and term to the datastore from the `GET /pipelines` endpoint. It will search the `scmRepo` text field for a term matching `%name%{pipeline_name}%`.
scmRepo field example:
```
{"branch":"tkyi-patch-1","name":"tkyi/mytest","url":"https://git.ouroath.com/tkyi/mytest/tree/tkyi-patch-1"}
```
To do a search, it expects a param like this:
```
params: {
search: {
field: "scmRepo",
keyword: "%name%tkyi/mytest%"
}
}
```
Related to https://github.com/screwdriver-cd/screwdriver/issues/880
Blocked by https://github.com/screwdriver-cd/models/pull/290, https://github.com/screwdriver-cd/datastore-sequelize/pull/32, https://github.com/screwdriver-cd/data-schema/pull/278
> fix(880): Pass search field and term to datastore for pipeline list [4]

- plugins/builds/update.js
- test/plugins/builds.test.js
If payload contains only statusMsg, only updates that.
Blocked by: https://github.com/screwdriver-cd/data-schema/pull/281/files
> fix(757): allow update build status msg only

- plugins/pipelines/list.js
- plugins/pipelines/update.js
- test/plugins/pipelines.test.js
It's hard to do operations in the UI based on the pipeline name when it is stored in a JSON string in the DB under `scmRepo`.
This PR saves and updates the pipeline `name` field at the root level of a pipeline when `scmRepo` is saved/updated. Also searches pipelines by pipeline `name`.
_Note: After this PR is merged, we will need to migrate `scmRepo.name` information to the new `name` field in the DB so that search will work for all pipelines._
Blocked by https://github.com/screwdriver-cd/data-schema/pull/283, https://github.com/screwdriver-cd/models/pull/292
Related to https://github.com/screwdriver-cd/screwdriver/issues/880
> fix(880): Update, save, and search by pipeline name

- bin/server
The periodic build does not start in the case of the pipeline admin user was removed after periodic build made.
To fix this problem, executor-queue use pipelineFactory. Therefore, API fixed to pass pipelineFactory to executor when setup executor.
Fixed to pass pipelineFactory to executor when setup executor.
issue: #1117 
executor-queue PR: https://github.com/screwdriver-cd/executor-queue/pull/33
> [2]fix(1117): Pass pipelineFactory to executor when setup executor

- features/step_definitions/workflow.js
- features/support/sdapi.js
Functional tests of workflow frequently fails.
We have to wait for builds to start after triggering steps finished.
Add retry process in `findEventBuilds` function.
relates: https://github.com/screwdriver-cd/screwdriver/pull/1328
> [small] Fix workflow tests

- design/build-cache.md
Decided to put the cache settings in top-level because of these reasons:
- Cannot put in `shared` because it currently has the same format as `jobs` and we don't want to change that. 
- Cannot put in `jobs` because the cache config itself contains multiple scopes, and it also contains multiple job names in there. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/1257, https://github.com/screwdriver-cd/screwdriver/issues/1280
> fix(1257): config format for build cache

- features/step_definitions/workflow.js
Functional test of workflow still frequently fails after this PR #1345 .
To get build info certainly, I use `searchForBuild` instead of `findEventBuilds`.
Use `searchForBuild` instead of `findEventBuilds` in `the "(.*)" job is triggered` and `that "(.*)" build uses the same SHA as the "(.*)" build` steps.
relates: #1328 #1345
> fix: Fix workflow test

- config/custom-environment-variables.yaml
- plugins/auth/index.js
- test/plugins/auth.test.js
When `api` runs under a sub directory, e.g.http://myhost.com/api, the `redirect_uri` field constructed by `bell` will be wrong, it will miss the `/api` part. 
This PR will make`redirect_uri`  configurable so that user can actually pass in the actual value.
https://github.com/hapijs/bell/blob/master/API.md
> fix: make redirect_uri for oauth configurable

- plugins/builds/update.js
- test/plugins/builds.test.js
We want to enrich infomations of notifications.
Pass event, build, pipeline data to notification plugins.
relates:
https://github.com/screwdriver-cd/notifications-email/pull/16
https://github.com/screwdriver-cd/notifications-slack/pull/13
> [small] add event to emit data

- features/support/sdapi.js
- features/support/world.js
Functional tests are failing because some builds were "RUNNING" instead of "SUCCESS", and also some checks where it tries to find the builds, they are not created yet. 
However, when looked into the functional test pipelines, it looks like the builds passed. Increasing the wait time to see if it fixes.
> fix: increase wait time in feature tests

- plugins/builds/update.js
- test/plugins/builds.test.js
We found that the notification-plugins does not work.
In this line of [notifications-email plugin](https://github.com/screwdriver-cd/notifications-email/blob/ff85796a9ecd42d21edddf6463df056140efbbdc/index.js#L82) it seems to catch the `e`. When I tried out debug out `e`, I got the following result.
```
TypeError: Cannot set property admin of [object Object] which has only a getter
at internals.Object._base (/usr/src/app/node_modules/screwdriver-notifications-email/node_modules/joi/lib/types/object/index.js:85:38)
at internals.Object._validate (/usr/src/app/node_modules/screwdriver-notifications-email/node_modules/joi/lib/types/any/index.js:590:37)
at internals.Object._base (/usr/src/app/node_modules/screwdriver-notifications-email/node_modules/joi/lib/types/object/index.js:157:45)
at …
```
> fix: bug fix builds/update.js

- package.json
pin model version  to avoid pulling in buildCluster models. The API part for that is not ready.
https://github.com/screwdriver-cd/models/releases
> fix: pin model version

- features/sd-cmd.feature
The pipeline was broken yesterday. While debugging, I deleted the functional-commands pipeline. After recreating the pipeline, need to rename the steps since permission tie to the old pipelineId.
> fix: rename commands

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
- plugins/auth/index.js
- test/lib/server.test.js
- test/plugins/auth.test.js
`SameSite` cookie config provides strict CSRF protection, but it breaks CORS interaction for our internal usecases. Hence providing an option for cluster admins to set this value.
1. Upgrade `hapi-auth-cookie` to v7  which supports `isSameSite` setting.
2. Provide a config to set this value.
1. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Directives See `SameSite` section
> feat: expose SameSite Cookie option

- plugins/buildClusters/get.js
- plugins/buildClusters/remove.js
- plugins/buildClusters/update.js
- test/plugins/buildClusters.test.js
- test/plugins/data/updatedBuildCluster.json
Since we're calling a list() instead of a get(), it returns and array instead of a since build cluster.
This PR accounts for that array.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1319
> fix(1319): Fix build clusters endpoints

- lib/registerPlugins.js
- test/lib/registerPlugins.test.js
Getting `Unknown authentication strategy token in /v4/isAdmin`
Let's try to register this after `auth`
> fix: register auth before isadmin

- screwdriver.yaml
The beta deploy job keeps failing even though the deployment is successful. This is because the script we are using is grepping for `200 OK` in the response, which is compatible when using HTTP/1.1. However, HTTP/2 only returns `HTTP/2 200`, which fails the script.
This PR switches to using the toolbox script for deploying, which solves this issue already.
- Toolbox: https://github.com/screwdriver-cd/toolbox/blob/master/k8s-deploy.sh#L30
- Original script: https://gist.github.com/stjohnjohnson/3d2388b2a7ba658cdcdaffa8cd874e50#file-k8s-deploy-sh-L30
> fix: Use toolbox script for deploying

- features/sd-step.feature
- test/plugins/data/validator.output.json
Functional tests failing, possibly due to some hab API change. Skipping this test since it's blocking our pipeline to release other features. We haven't changed anything in sd-step. 
cc @sakka2
> fix: skip sd-step tests

- screwdriver.yaml
Our K8S_DEPLOY step is currently failing.
Previously we point `api.k8s.screwdriver.cd`  to the ips for `api.ossd.k8s.screwdriver.cd` in AWS route53. That means whenever we update the cluster, manual change is needed. Switch to the correct endpoint.
This PR updates to the correct host.
Related to https://github.com/screwdriver-cd/guide/pull/256
> fix: switch k8s api endpoint

- plugins/builds/token.js
- test/plugins/banner.test.js
- test/plugins/builds.test.js
Need to include `prParentJobId` in the jwt so we can do permission check inside store. 
Blocked by: https://github.com/screwdriver-cd/models/pull/304
Related: https://github.com/screwdriver-cd/screwdriver/issues/1382
> fix: includes prParentJobId in token

- features/sd-step.feature
sd-step feature is ignored in the [previous PR](https://github.com/screwdriver-cd/screwdriver/pull/1404)  since the options `pkg-version` doesn't works well.
And the problem is fixed by [this PR](https://github.com/screwdriver-cd/sd-step/pull/17) in launcher@v5.0.46.
This PR re-enables sd-step feature.
https://github.com/screwdriver-cd/sd-step/pull/17
https://github.com/screwdriver-cd/screwdriver/pull/1404
> fix: re-enable sd-step functest

- README.md
There were two entries in the list but shows three in the description.
Fix text.
> fix: Fix miscalculation of options in README

- features/step_definitions/metadata.js
- features/step_definitions/workflow.js
- features/support/sdapi.js
Functional tests often fail because of several reasons.
This PR fixes one of the cause of failures that workflow and metadata tests don't properly wait builds to start.
> fix: fix test of workflow and metadata

- package.json
In case the issue is this bug: https://github.com/screwdriver-cd/scm-github/pull/112/files
> fix: Try pinning scm-github package version

- plugins/pipelines/badge.js
- test/plugins/data/events.json
- test/plugins/data/eventsPr.json
- test/plugins/pipelines.test.js
https://github.com/screwdriver-cd/screwdriver/issues/1429
Badge generation is borked because it shows statuses for all workflow edges in the graph instead of just the one that was triggered.
PR computes statuses for workflow edges only in the current workflow, not for all nodes in the graph. For instance, if the current workflow is triggered by a commit, instead of computing statuses for all workflows (pr, commit etc), compute only for commit edges.
Issue: https://github.com/screwdriver-cd/screwdriver/issues/1429
> fix: Fix badge statuses

- plugins/events/create.js
- plugins/webhooks/index.js
- test/plugins/events.test.js
Events which doesn't trigger any jobs return error to github webhooks.
It would be better to return 204.
* filter null response from createEvents.
* https://github.com/screwdriver-cd/models/pull/316
> fix: fix no build event response

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
We want to add pr title to the event for using it in notification.
Add prTitle to the event when PREvent is created.
data-schema https://github.com/screwdriver-cd/data-schema/pull/310
models https://github.com/screwdriver-cd/models/pull/321
scm-github https://github.com/screwdriver-cd/scm-github/pull/120
> [4] feat: Add pr title to the event

- features/support/world.js
sd-step test is failing since status is seen as `RUNNING` when should be `SUCCESS`.
The actual total test takes 4 mins total but the `waitForBuild` method only waits for 3 mins.
This PR increases the timeout to 6 mins.
Actual sd-step build: https://beta.cd.screwdriver.cd/pipelines/2571/builds/36966
Functional test failure: https://cd.screwdriver.cd/pipelines/1/builds/88817
> fix: Increase retry delay and max number for feature test when waiting for build

- plugins/jobs/index.js
- plugins/jobs/lastSuccessfulMeta.js
- test/plugins/data/builds.json
- test/plugins/data/collection.response.json
- test/plugins/jobs.test.js
We need this endpoint to get last successful metadata for a given job
> fix: add endpoint for last successful meta of a job

- plugins/builds/update.js
- plugins/pipelines/update.js
- test/plugins/builds.test.js
- test/plugins/pipelines.test.js
Currently it looks like the build is stuck in the queue vs blocked since the blocked stat is updated each time the blocked status is set.
This PR skips setting the blocked stat if it's already set.
Also fixes bug when updating checkoutUrl. Should also check if user has admin permissions on old repo as well as new one.
Related to #1474
> fix(1474): Only update blocked stats once

- plugins/builds/index.js
- plugins/builds/metrics.js
- plugins/events/index.js
- plugins/events/metrics.js
- test/plugins/builds.test.js
- test/plugins/events.test.js
Add endpoints for metrics
Change some mock names in tests to be consistent with the `pipelines.test.js`
Related: https://github.com/screwdriver-cd/screwdriver/issues/1412
Blocked by: 
- https://github.com/screwdriver-cd/datastore-sequelize/pull/45
- https://github.com/screwdriver-cd/models/pull/324
> feat(1412): event & build metrics

- plugins/builds/artifacts/get.js
- test/plugins/builds.test.js
want artifact to be downloadable by the browser with mime type dictated by the extension of coz
pass along the download option to the store endpoint
related to: https://github.com/screwdriver-cd/screwdriver/issues/1476
related PRs:
- https://github.com/screwdriver-cd/store/pull/75
- https://github.com/screwdriver-cd/ui/pull/408
> fix: pass download flag to artifact endpoint

- config/default.yaml
Related: https://github.com/screwdriver-cd/screwdriver/issues/579
> fix: set default restrict PRs to none

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
Pass `skipMessage` to models if commit message includes `skip ci`
This only applies to push events, pull request events still work like normal
Related: https://github.com/screwdriver-cd/screwdriver/issues/1447
Blocked by: https://github.com/screwdriver-cd/models/pull/331
> feat(1447): skip ci creates empty event

- plugins/pipelines/listEvents.js
- plugins/pipelines/listJobs.js
- test/plugins/pipelines.test.js
Allow query by `jobName` and `pipelineId`
Related: https://github.com/screwdriver-cd/screwdriver/issues/1522
> feat(1522): allow easy way to get job with jobName

- plugins/jobs/stepMetrics.js
- test/plugins/jobs.test.js
- support get step metrics for all steps for a job
- make `stepName` an optional query param
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1412
> fix: support get step metrics for all steps for a job

- package.json
- plugins/webhooks/index.js
- screwdriver.yaml
- test/plugins/webhooks.test.js
Our users want to start jobs triggered release event same like ~pr or ~commit.
- https://github.com/screwdriver-cd/screwdriver/commit/c5fc1ff05d75346f534ba9dc024c359f77892bad : scm token is obtained twice. It's wasteful. And do a little refactor of the test.
- https://github.com/screwdriver-cd/screwdriver/commit/4baa8713e3ef73da6374c851e57346913f48e48d : 
- enable to parse `~release` and `~tag` with `determineStartFrom()`
- `sha` is empty when the event is `release` or `tag` so this PR provides to a function which gets `sha` after `parseHook()` with `scm.getCommitRefSha()`
It works locally like this:
- Related Issue: https://github.com/screwdriver-cd/screwdriver/issues/823
- Blocked by:
- https://github.com/screwdriver-cd/data-schema/pull/322
- …
>  feat(823): [6] release and tag trigger

- plugins/events/create.js
- test/plugins/events.test.js
Let user to kick start builds for restricted PR
PR build should be aware of `sourcePaths` as well
blocked by: https://github.com/screwdriver-cd/data-schema/pull/323
blocked by: https://github.com/screwdriver-cd/models/pull/345
related: https://github.com/screwdriver-cd/screwdriver/issues/1528
> fix: create events for restricted PR

- config/custom-environment-variables.yaml
- config/default.yaml
- lib/server.js
- package.json
- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
prChain flag is moved from top-level setting to pipeline-level annotation.
- Current
```
prChain: true
jobs:
main:
....
```
- After
```
annotations:
screwdriver.cd/chainPR: true 
jobs:
main:
....
```
This PR adds value resolution of the `screwdriver.cd/chainPR` annotation and the plugin-level setting, which is added for maintenance of similarity with `restrictPR`.
- https://github.com/screwdriver-cd/screwdriver/issues/1010#issuecomment-466188824
> fix(1010): [1][medium] add chainPR annotation.

- plugins/builds/index.js
- test/plugins/data/validator.output.json
Now, Jobs does not chain even if chainPR is true.
We need to pass `pipeline.prChain` flag to getNextJobs function, when checking `triggerNextJobs`.
`getNextJobs` function has fixed before.
https://github.com/screwdriver-cd/workflow-parser/blob/master/lib/getNextJobs.js
screwdriver-cd/screwdriver#1010 (comment)
> fix(1010): [small] add chainPR value to getNextJobs function

- plugins/pipelines/update.js
- test/plugins/pipelines.test.js
We may have some pipelines with deprecated scmContext in the DB, we won't be able to hit github api to check user permission against those repos since the API doesn't config that deprecated scmContext.
This PR will allow current admin to update pipeline's `checkoutUrl` with deprecated scmContext.
> fix: allow current admin to update pipeline with deprecated scmContext

- plugins/builds/index.js
- plugins/pipelines/badge.js
https://github.com/screwdriver-cd/screwdriver/issues/1521#issuecomment-472771605
When `[skip ci]` created an empty event, the badge was displayed as unknown. Fixed to create badges as far back as effective build.
■Before
■After
> fix(1521): badge use last effective event status

- features/step_definitions/sd-step.js
- plugins/pipelines/badge.js
lgtm.com pointed out an unused variable, and an extra parameter.
Fix the two alerted issues from lgtm.
[Superfluous argument](https://lgtm.com/projects/g/screwdriver-cd/screwdriver/snapshot/4161c466070043d98f1f81a772f806cc8c56133c/files/plugins/pipelines/badge.js#L129)
[Unused variable](https://lgtm.com/projects/g/screwdriver-cd/screwdriver/snapshot/4161c466070043d98f1f81a772f806cc8c56133c/files/features/step_definitions/sd-step.js?sort=name&dir=ASC&mode=heatmap#xa196417b2c5003c5:1)
> fix: remove unused variables, parameters

- config/default.yaml
- plugins/pipelines/badge.js
- plugins/pipelines/index.js
- plugins/pipelines/jobBadge.js
- test/plugins/pipelines.test.js
- add new endpoint for job badge and modify the pipeline badge keyword from `build` to `pipeline`
- the new endpoint will be `v4/pipelines/id/jobName/badge`
pipeline badge:
`deploy` job badge
Related to: 
https://github.com/screwdriver-cd/screwdriver/issues/1451
> fix: add new endpoint for job badge

- plugins/pipelines/badge.js
- plugins/pipelines/index.js
- plugins/pipelines/jobBadge.js
- test/plugins/pipelines.test.js
- Add new statuses mapping for badge
- modify the format a little bit, now it will have the pipeline name as prefix for both pipeline and job badge
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1451
> fix: add new statuses mapping for badge

- plugins/pipelines/badge.js
- plugins/pipelines/index.js
- plugins/pipelines/jobBadge.js
- test/plugins/pipelines.test.js
Different badge services may have different separators, e.g. https://shields.io/ uses `-` and internally we use `/`. This PR will properly encode the subject based on the specific separator.
current badge service:
https://github.com/screwdriver-cd/screwdriver/blob/master/config/default.yaml#L270
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1451
> fix: encode subject based on badge service separator

- plugins/jobs/lastSuccessfulMeta.js
Allow build scope to call this endpoint. No reason to restrict it since `build` can also call GET jobs or GET builds. 
@chestery
> fix: allow build to get meta

- plugins/pipelines/index.js
- plugins/pipelines/jobBadge.js
- test/plugins/pipelines.test.js
Currently, the job badge shows build status of the last build. This PR will show the state of the job if it is `DISABLED`.
> fix: display disabled state for job badge

- features/step_definitions/git-flow.js
- features/support/github.js
- to close a PR, we only need to change the `state`, `base` means want to update it to a new value which is not needed for us
https://octokit.github.io/rest.js/#api-Pulls-update
- we get timeout very often for test case `any existing builds should be stopped`, that's because we keep waiting until we get status `SUCCESS` or `ABORTED`, but the status sometimes can be `FAILURE` when git is slow and api cannot get `screwdriver.yaml` .
https://cd.screwdriver.cd/pipelines/2080/builds/95446
> fix: fix functional tests

- plugins/builds/index.js
- test/plugins/builds.test.js
Now, job error happens in PRs from forked repository, because `sd-scm-github` step tries to `git reset` with the commit SHA of forked repository which dose not exist in original one.
This is because there is no `config.prRef` value in argument below.
https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L316
In chainPR workflow, we should pass the `prRef` value to the buildFactory.create() method.
To achieve this, 
1. We need to set `prRef` into the events model  when event is created.
2. Then, we can get `prRef` from events model like `event.pr.ref`;
Issue:
https://github.com/screwdriver-cd/screwdriver/issues/1010#issuecomment-478911280
Other PRs:
[1]: data-schema: https://github.com/screwdriver-cd/data-schema/pull/327
[2]: models: …
> fix(1010): [3] Fix the error from forked repository

- plugins/pipelines/badge.js
- plugins/pipelines/index.js
- plugins/pipelines/jobBadge.js
- test/plugins/pipelines.test.js
If there is no builds, set the default `status` to `unknown`.
>  fix: set default unknow status for badge

- package.json
- plugins/events/create.js
- test/plugins/events.test.js
When an event is started by a periodic build, it can be hard for users to know if the build was started manually by a user, through a commit, or by Screwdriver automatically.
This PR allows `creator` and `causeMessage` to be passed into POST event endpoint.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1058
Blocked by https://github.com/screwdriver-cd/data-schema/pull/329, https://github.com/screwdriver-cd/models/pull/367
> fix(1058): Allow creator and cause message to be passed into event create (3)

- bin/server
This line `delete datastorePluginConfig.readOnly;` is giving problem:
```
TypeError: Cannot delete property 'readOnly' of #<Object>
```
Looks like `config.get` returns non-writable value. This PR will clone the Obj first before deleting.
> fix(1590): fix readonly

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
call pipeline.getJobs to get non-archived pr jobs instead of calling pipeline.jobs to get all the jobs
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1603
> fix: call pipeline.getJobs instead of pipeline.jobs

- plugins/builds/index.js
We're getting the following err in func test very often. Trace the code a little bit and found that this is caused by a race condition, when the two upstream builds finish around the same time, they will both try to create the downstream build which is setting the parentBuildId as a String. And eventually one of them won and the `parentBuildId` is the id of the last job instead of an array. 
This PR will fetch the upstreamBuildIds first before creating the build.
```
Step: Then the "JOIN" job is triggered from "PARALLEL1" and "PARALLEL2" - features/workflow.feature:68
12:11:57      Step Definition: features/step_definitions/workflow.js:124
12:11:57      Message:
12:11:57        AssertionError: expected 56372 to be an array
```
> fix: fix flaky join functional tests

- plugins/events/README.md
- plugins/pipelines/README.md
- plugins/pipelines/index.js
- plugins/pipelines/listTriggers.js
- test/plugins/data/triggers.json
- test/plugins/pipelines.test.js
It would be nice if users could see what pipelines/jobs run after jobs in their pipeline are done.
This PR adds an endpoint `GET /pipelines/{id}/triggers` that returns an object with jobName and destination trigger data.
Example output:
```
[{
jobName: 'main',
triggers: ['~sd@12345:main']
}, {
jobName: 'beta',
triggers: ['~sd@12345:test', '~sd@223344:test']
}, {
jobName: 'prod',
triggers: ['~sd@556677:deploy']
}]
```
Related to https://github.com/screwdriver-cd/screwdriver/issues/1333
> feat(1333): List pipeline triggers (2)

- bin/server
We set default cluster env as `SD_VERSION:4`
However, launcher expects environment to be type `string:string`
Converting here so that cluster admins don't need to remember to set it to string. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/1070
> fix: convert number to string

- features/step_definitions/sd-cmd.js
- plugins/commands/remove.js
- test/plugins/commands.test.js
- sd-cmd feature test has an error but it's not caught.
- https://cd.screwdriver.cd/pipelines/1/builds/112699/steps/test
- command DELETE api returns 500 because of checking invalid response code.
- [Store returns 204](https://github.com/screwdriver-cd/store/blob/1dda93eb2ddb07499561e001079ff37b9cbeb5a8/plugins/commands.js#L145) when deleting command but api expects 200.
- Command binaries are deleted from s3 (or compatible) but command metadata are not deleted from a datastore. 
- This PR enables to catch an error which is caused by DELETE api on sd-cmd feature test.
- This PR also fixes expected response code.
> fix: fix response code check for DELETE command api

- bin/server
Moved logic to buildFactory instead of eventFactory. 
Related: https://github.com/screwdriver-cd/models/pull/380
> fix: pass clusterEnv to buildFactory

- plugins/pipelines/listTriggers.js
- test/plugins/pipelines.test.js
Models already handles getTriggers result, so no need to do an additional `toJson` here.
This PR removes `toJson` from getTriggers result.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1333
> fix(1333): Remove toJson for triggers result

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
`triggeredPipelines`  gets triggered pipelines based on same SCM repo ID,
but it also get another pipelines based on different SCM repo IDs, which caused by incorrect search query.
Given scmRepoId `github:123:master`, current `triggeredPipelines` fetches also pipelines of `github:1237` and `github:123245`.
This fix `triggeredPipelines` to get correct pipelines.
> fix: fix search pattern to get triggered pipelines

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
`~tag` trigger is not triggered, if you use a pipeline that targets to the non master branch. Only these pipeline have `~tag:master`, the trigger will fire. 
When user creates a tag, all branch pipeline should trigger `~tag` trigger.
The same is the case with `~release` trigger
All branch pipeline job search jobs which trigger from `~tag` and `~release`, when tag or release trigger was fired.
#823 
On the second pass, tag and release trigger will have tag name filter function.
> fix: tag/release are triggered by every branch pipelines

- plugins/events/create.js
- test/plugins/events.test.js
make restart PR build always use latest sha on the PR
https://github.com/screwdriver-cd/screwdriver/issues/1634
> fix(1634): make restart PR build always use latest sha on the PR

- features/step_definitions/sd-cmd.js
Because we add piped `sd-cmd` execution test.
This PR allows piped `sd-cmd` execution.
e.g. `dd if=/dev/zero bs=65537 count=1 | sd-cmd exec screwdriver-cd-test/binary-func-test@1 foo bar`
- https://github.com/screwdriver-cd/sd-cmd/pull/35
- This blocks https://github.com/screwdriver-cd-test/functional-commands/pull/5
> fix: [1] allow piped sd-cmd execution.

- plugins/commands/index.js
- plugins/commands/updateTrusted.js
- plugins/templates/index.js
- plugins/templates/updateTrusted.js
- test/plugins/commands.test.js
- test/plugins/templates.test.js
To provide admins access to mark certain template & command as trusted
To add separate endpoints for template & command for marking trusted
https://github.com/screwdriver-cd/screwdriver/issues/1427
blocked by: 
https://github.com/screwdriver-cd/data-schema/pull/340
> fix: add admin only endpoint to mark "trusted"

- lib/server.js
- test/lib/server.test.js
It's reported that sometimes periodicBulids aren't fired.
And we found following errors in sdapi logs.
```
error: failed to post build event for job xxx: TypeError: this.userTokenGen is not a function
```
The executor-queue sets up `userTokenGen` in `_startPeriodic` method,
https://github.com/screwdriver-cd/executor-queue/blob/master/index.js#L287-L289
and which is called by `job.update` ( and which is called by pipeline.sync etc..).
So if sdapi is restarted, the `userTokenGen` is null until the sdapi is requested to update any jobs, and also periodicBuilds don't work.
https://github.com/screwdriver-cd/executor-queue/blob/master/index.js#L48
https://github.com/screwdriver-cd/executor-queue/blob/master/index.js#L190
tokenGen was splited for purposes in executor-queue, `tokenGen` is for …
> fix: setup tokengen to executor

- plugins/builds/index.js
- test/plugins/builds.test.js
Join job does not work when chainPR workflow.
PR jobs have `PR-{num}:` prefix, so jobs will not be found in `workflowGraph.nodes` objects.
We need to trim `PR-{num}:` prefix when searching jobs from workflowGraph objects in chainPR workflow.
For unit test, `workflow-parser` should be merged first.
worklfow-parser: https://github.com/screwdriver-cd/workflow-parser/pull/26
> fix: [2]Join job does not work when chainPR workflow

- package.json
After merged [this PR](https://github.com/screwdriver-cd/executor-queue/pull/68
), I ran screwdriver pipeline twice and create [0.718](https://github.com/screwdriver-cd/screwdriver/releases/tag/v0.5.718) and [0.719](https://github.com/screwdriver-cd/screwdriver/releases/tag/v0.5.719). 
However both v0.5.718 and v0.5.719 does not have new executor-queue(2.4.22). 
I update package.json to install new executor-queue.
Update executor-queue version.
[screwdriver-executor-queue - npm](https://www.npmjs.com/package/screwdriver-executor-queue)
> fix: update executor-queue version

- features/step_definitions/git-flow.js
- features/step_definitions/workflow.js
- features/support/github.js
- package.json
Github module is deprecated, but functest is used it.
Update github module to @octokit/rest for functest.
- Update `github.js` and related tests for functest.
- Add `@octokit/rest` and delete `github` to `package.json`.
> fix: update github to octokit for functional test

- plugins/builds/artifacts/get.js
- test/plugins/builds.test.js
Making necessary changes to implement artifacts for screwdriver backend.
Instead of receiving `download=true`, now query params will be receiving `type=preview` or `type=download`. 
Backend will forward its request from UI to Store with proper access authentication token setup. 
UI: https://github.com/screwdriver-cd/ui/pull/465
Backend: https://github.com/screwdriver-cd/screwdriver/pull/1703
Store: https://github.com/screwdriver-cd/store/pull/88
> feat: implement artifacts preview for screwdriver backend

- plugins/jobs/README.md
- plugins/jobs/listBuilds.js
- test/plugins/jobs.test.js
Sorting by build ID is slow. We want to sort by `createTime` to take advantage of the DB index.
This PR adds `createTime` as the sort key. Should work since models and datastore-sequelize already handle `sortBy` key: https://github.com/screwdriver-cd/models/blob/master/lib/job.js#L161-L163, https://github.com/screwdriver-cd/datastore-sequelize/blob/master/index.js#L444-L449
Related to https://github.com/screwdriver-cd/screwdriver/issues/1737
> fix(1737): Sort by createTime when getting builds for job

- README.md
Sometimes people will see out of memory issues when running `npm test` locally.
This PR updates the README with further `npm test` instructions to work around the out of memory issues.
Related to https://medium.com/@vuongtran/how-to-solve-process-out-of-memory-in-node-js-5f0de8f8464c
> fix: Update README [skip ci]

- package.json
- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
… build
sd incorrectly excludes commit from build when commit is made but is sent by user in ignoreUser
add a new condition to ci skip check to prevent SD from skipping legitimate build
https://github.com/screwdriver-cd/screwdriver/issues/1747
> fix(1747): add a new condition to skip ci check

- package.json
Don't think it's needed
Was added from here: https://github.com/screwdriver-cd/screwdriver/pull/985
Related: https://github.com/screwdriver-cd/screwdriver/pull/1761
> fix: remove sqlite3

- plugins/events/create.js
- test/plugins/events.test.js
PR author should not be allowed to restart PR if restrictPR annotation is turned on.
Add a check to enforce restrictPR before allowing PR author to restart builds
https://github.com/screwdriver-cd/screwdriver/issues/1701
> fix(1701): PR authors should not be able to restart builds if `restrictPR` is on

- config/custom-environment-variables.yaml
- config/default.yaml
When we use coverage-bookend, coverage scanning is executed all jobs, including jobs which is not necessary to scan.
It must be leads to longer build time, or surging database size.
- Add cluster level config of coverage plugin (`default`: `true` / `false`）
- Default value is `true`.
Issue: https://github.com/screwdriver-cd/screwdriver/issues/1754
Other PRs
[2] https://github.com/screwdriver-cd/coverage-bookend/pull/4
[3] https://github.com/screwdriver-cd/coverage-base/pull/11
> fix(1754): [1] Add cluster level coverage plugin setting (enable or not)

- plugins/builds/index.js
- plugins/events/create.js
- plugins/webhooks/index.js
- test/plugins/builds.test.js
- test/plugins/data/events.json
- test/plugins/data/eventsPr.json
- test/plugins/events.test.js
- test/plugins/webhooks.test.js
To use branch info in the restarted build and triggered build, I added branch info to event and build config when they are created. And use that info when creating new event.
PR build was failed because related PRs are not merged.
It may success after related PRs will be merged.
* Add branch info to event and build config when they are created.
* Use branch info when creating new event.
https://github.com/screwdriver-cd/screwdriver/issues/1755
https://github.com/screwdriver-cd/screwdriver/issues/1760
Related PRs:
https://github.com/screwdriver-cd/data-schema/pull/357
https://github.com/screwdriver-cd/models/pull/396
https://github.com/screwdriver-cd/scm-base/pull/72
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this …
> [4] fix(1755): Add baseBranch to event and build config

- plugins/builds/create.js
- test/plugins/builds.test.js
Currently we can created job's build with either POST /event or POST/builds, latter is causing some issue with UI because it's missing startFrom in event data.
Event created as part of POST /builds should have proper startFrom data
https://github.com/screwdriver-cd/screwdriver/issues/1741
> fix(1741): adding startFrom to event created by POST /builds

- plugins/builds/update.js
- test/plugins/builds.test.js
Administrators need to stop jobs which looks like running on the UI but actually failed, and show the reason of failure on the UI for the users.
Enable administrator to update build status to `FAILURE`.
> feat: Enable admin users to update build status failure

- plugins/builds/create.js
- test/plugins/builds.test.js
- test/plugins/data/validator.output.json
previous commit breaks an functional test where POST /build would actually create build twice
add a skipMessage when we create event so it would skip build creation
https://github.com/screwdriver-cd/screwdriver/pull/1773
> fix: post build api creating build twice

- plugins/jobs/README.md
- plugins/pipelines/README.md
- plugins/pipelines/index.js
- plugins/pipelines/latestBuild.js
- test/plugins/pipelines.test.js
Previously we added an endpoint for that returns latest build for a given job using job id, but user might not have job id so they would need to make a separate call to get job id. 
Add another endpoint that would retrieve latest build using job name and pipeline id
https://github.com/screwdriver-cd/screwdriver/issues/1717
> feat(1717): get latest build api for pipeline

- plugins/events/metrics.js
- plugins/jobs/metrics.js
Probably a copy/paste mistake from before
> fix: allow pipeline token to fetch metrics

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
When processing webhooks, there could be pipelines which do not have a valid workflow graph. For example child pipelines which does not have any events.
Webhook processing should be resilient to errors in pipelines on non commit branch.  
```
data: TypeError: Cannot read property 'edges' of undefined
at Object.getNextJobs (/usr/src/app/node_modules/screwdriver-workflow-parser/lib/getNextJobs.js:29:19)
at hasTriggeredJob (/usr/src/app/node_modules/screwdriver-api/plugins/webhooks/index.js:168:37)
at pipelinesOnOtherBranch.filter.p (/usr/src/app/node_modules/screwdriver-api/plugins/webhooks/index.js:272:9)
at Array.filter (<anonymous>)
at triggeredPipelines (/usr/src/app/node_modules/screwdriver-api/plugins/webhooks/index.js:271:53)
at <anonymous>
```
I confirm that this contribution is …
> fix: webhook error when finding pipelines to trigger

- plugins/builds/create.js
- test/plugins/builds.test.js
Functional tests are failing when calling build create API endpoint directly. This is because the new executor changes expect `causeMessage` to be passed in.
This PR always passes in causeMessage to build create.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1675
> fix(1675): Always pass in causeMessage to build create

- package.json
The unit tests have been failing with timeout.
This PR increases unit test timeout from 3000 to 4000.
Failing builds: https://cd.screwdriver.cd/pipelines/1/builds/152628/steps/test, https://cd.screwdriver.cd/pipelines/1/builds/152619/steps/test
> fix: Increase unit test timeout

- plugins/collections/update.js
- test/plugins/collections.test.js
Previously users are able to change their default collection, we have disabled this on ui. We should also add a guard on api level.
Add a check on POST /collection/id to prevent modification on `My pipelines`, which Collection type is `default`
https://github.com/screwdriver-cd/screwdriver/issues/1801
> fix(1801): Do not allow changes on default collection

- package.json
I want to import [coverage-sonar#30](https://github.com/screwdriver-cd/coverage-sonar/pull/30)
- `screwdriver-coverage-sonar` is version up 1.0.25 from 1.0.22
> Fix coverage-sonar version

- plugins/pipelines/metrics.js
- test/plugins/pipelines.test.js
Allow taking is `sort` as query param.
Collections card view needs information of latest page of data. Model has by default `ascending` as sort order.
https://github.com/screwdriver-cd/models/pull/404
> fix: enable taking sort param for pipeline metrics

- package.json
Because don't import breaking change about [#1816](https://github.com/screwdriver-cd/screwdriver/issues/1816)
- Pined version to `16.33.x`
- Support old API about request URL
https://github.com/screwdriver-cd/screwdriver/issues/1816
https://github.com/octokit/rest.js/commit/e891d4e31c41e7a6afe0c8257404bf1f51607f5e#diff-0071a9eb9e809c9aacfc547f7514add6L1066
> fix(1816): Fix package.json

- config/custom-environment-variables.yaml
- config/default.yaml
Screwdriver supports aws s3 cache strategy to store build cache. Need option / strategy to store build cache to disk.
- Add cluster-level configuration  for cache strategies (s3, disk)
- Default: s3
[1830](https://github.com/screwdriver-cd/screwdriver/issues/1830)
> feat(1830): add cluster level config for cache strategy

- lib/registerPlugins.js
env var
The env var from k8s is type string for terminationGracePeriodSceonds
This adds a parseInt to the env var
> feat(1610): Add parseInt to terminationgraceperiod

- features/step_definitions/api-token.js
- features/step_definitions/authorization.js
- features/step_definitions/collection.js
- features/step_definitions/events.js
- features/step_definitions/git-flow.js
- features/step_definitions/metadata.js
- features/step_definitions/sd-cmd.js
- features/step_definitions/sd-step.js
- features/step_definitions/secrets.js
- features/step_definitions/server.js
- features/step_definitions/templates.js
- features/step_definitions/workflow.js
- features/support/github.js
- features/support/world.js
- package.json
Current cucumber.js version is very old (2!) and some feature tests are flakey.
- Use the latest cucumber.js 6 to use `--retry` option
- Fix deprecation of cucumber,js 
- [cucumber-js/cli.md at master · cucumber/cucumber-js](https://github.com/cucumber/cucumber-js/blob/9518f1c46de28767d4e19f2faf5c3b5c29936c97/docs/cli.md#parallel-experimental)
- [cucumber-js/CHANGELOG.md at master · cucumber/cucumber-js](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md)
> fix: use cucumber 6

- bin/server
Pipeline level build cluster assignment not working as expected, the reason being multiBuildClusterEnabled flag not available in pipelineFactory
add multiBuildClusterEnabled flag to pipelineFactory
[1830](https://github.com/screwdriver-cd/screwdriver/issues/1830)
> feat(1830): add multibuildclusterenabled flag to pipeline factory init

- package.json
Test sometimes hang with retry
Add `--exit` option to prevent hanging.
- https://github.com/screwdriver-cd/screwdriver/pull/1852#issuecomment-557313286
- https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#exiting
> fix: add --exit option to cucumber

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
Now Screwdriver.cd wait 1.8s for getting changed files correctly.
This PR remove waiting `magic 1.8s`, and polling `mergeable` in `getChangedFiles` of `scm-github`(https://github.com/screwdriver-cd/scm-github/pull/145)
- Remove waiting `magic 1.8s`
- Use `prNum` and `scmUri` for `getChangedFiles`
https://github.com/screwdriver-cd/screwdriver/issues/1468
> fix(1468): [3] Remove magic 1.8s

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
Move cache environment variables under ecosystem and get latest executork8svm
[1830](https://github.com/screwdriver-cd/screwdriver/issues/1830)
> fix(1830): update cache env var path and latest executork8svm

- plugins/builds/listSecrets.js
- plugins/builds/metrics.js
- plugins/builds/token.js
- plugins/events/listBuilds.js
- plugins/events/metrics.js
- plugins/jobs/listBuilds.js
- plugins/jobs/metrics.js
- plugins/pipelines/listEvents.js
- plugins/pipelines/listJobs.js
- plugins/pipelines/listSecrets.js
- plugins/pipelines/listTriggers.js
- plugins/pipelines/metrics.js
- plugins/pipelines/tokens/create.js
- plugins/pipelines/tokens/list.js
- test/plugins/builds.test.js
- test/plugins/events.test.js
- test/plugins/jobs.test.js
- test/plugins/pipelines.test.js
There's inconsistency on our api, where some of them are missing validation on parameter.
For example on /pipelines/{id} there's validation on id but not on /pipelines/{id}/triggers.
This leads to inconsistent behavior when user incorrectly passing invalid parameter,
/pipelines/randomString would results in code 400 but /pipelines/string/triggers results in
code 500.
enforce validation on parameters on our api
https://github.com/screwdriver-cd/screwdriver/issues/1844
> fix(1844): enforce validation on parameters

- plugins/events/create.js
- test/plugins/events.test.js
currently on build restart, default parameters were used because parent event parameters were not passed on build restart.
pass parent event parameters on build restart
https://github.com/screwdriver-cd/screwdriver/issues/1339
> fix(1339): parent event parameters not passed on restart

- plugins/events/create.js
- test/plugins/events.test.js
In my previous fix for restarting event, I made all event inherit parent event's parameters. This is causing issues where user will not be able to set custom parameters for event with parent event.
Event won't inherit parent event parameters if custom parameters are supplied
https://github.com/screwdriver-cd/screwdriver/issues/1339
> fix(1339): event with parameters and parent event

- plugins/builds/steps/logs.js
We'd like to process logs using a teardown step in the build that created the logs.
This will permit a build to use the SD_TOKEN to read logs from any build, including itself.
> Allow log access for build scope

- screwdriver.yaml
Same git user is used for both prod and beta functional tests. This is causing rate limiting problems when running tests back to back.
Use a separate user for prod functional tests.
https://cd.screwdriver.cd/pipelines/1/builds/167329/steps/test
> fix: use a different git user for prod functional tests

- plugins/builds/index.js
- test/plugins/builds.test.js
Typo in code: `parentBuildIds` => `parentBuildId`.
This PR fixes a typo and removes `.only` on build unit tests.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1710
> fix(1710): Fix parentBuildId and tests

- screwdriver.yaml
Functional tests needs SD API token for the running. When new Git user was added, I missed updating SD API token for same user.
Point prod functional tests to use new SD API token.
> fix: use sd api token for sd-buildbot-functional user

- features/step_definitions/workflow.js
Workflow feature test does not cleanup created test pipelines. This results in re-using git user credentials from the already existing pipeline and can cause rate limiting errors. Rest of the feature tests uses a different approach to create the test pipeline, it deletes the pipeline if it exists. https://github.com/screwdriver-cd/screwdriver/blob/master/features/support/world.js#L42-L66
Delete workflow test pipelines after end of feature tests.
https://cd.screwdriver.cd/pipelines/1/builds/167762/steps/test
> fix: delete test pipeline after workflow tests

- features/sd-cmd.feature
- features/step_definitions/sd-cmd.js
- features/step_definitions/workflow.js
Shared command functional tests is broken. This happens when pipeline associated with the shared command is is deleted. When pipeline is deleted then test user is unable to delete the shared command. 
Delete shared command as part of functional test. This way future tests are not dependent on old data. 
https://cd.screwdriver.cd/pipelines/1/builds/167904/steps/test
> fix: fix command functional tests

- plugins/pipelines/listTriggers.js
- test/plugins/data/triggers.json
Should allow pipeline list triggers to return external join trigger.
This PR updates the trigger destination regex.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1710
> fix(1710): Allow join external trigger

- plugins/builds/index.js
- test/plugins/builds.test.js
Currently the external parallel fork join feature does not trigger the join build after both parallel builds complete. This is because the external build is not storing its information in the join build properly.
This PR creates the join build immediately after creating the external build so that the parentBuilds field is populated correctly.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1710
> fix(1710): Create join job and store external parentBuilds info [3]

- plugins/builds/index.js
- test/plugins/builds.test.js
The join job does not always update properly for external parallel fork join.
This PR passes in the correct value for checking if the job is external or not when creating the join build after creating the external build.
> fix(1710): Fix external check for join build

- plugins/jobs/update.js
- plugins/secrets/create.js
- test/plugins/jobs.test.js
- test/plugins/secrets.test.js
Currently only user token can change job state and create secrets. We should also allow pipeline token for more flexibility/
Allow pipeline token to create secrets and change job state.
https://github.com/screwdriver-cd/screwdriver/issues/1847
> fix(1847): allow pipeline token to create secret and change job state

- package.json
Currently there's no options in `package.json` to run `debug` and `profile`
This PR add `npm run debug` and `npm run profile` to `package.json`
> fix: add debug and profile options to package.json

- plugins/builds/index.js
- test/plugins/builds.test.js
fix #1785 
In getFinishedBuilds, it gets all parent event and merges parent build status data recursively.
#1785 
> fix(1785): Fix to get parent event builds recursively

- plugins/builds/index.js
- plugins/builds/update.js
- test/plugins/builds.test.js
Previously, external fork join was not working when the external job finished first.
This PR fixes logic to handle external fork join.
Notes:
- TODO in another PR: add logic for restarted build
> feat(1710): External join works no matter which fork finishes first

- Dockerfile
- package.json
- screwdriver.yaml
Screwdriver API is running on node:8 container which is no longer supported.
Upgrade to latest LTS of node. 
https://github.com/screwdriver-cd/screwdriver/issues/1722
> fix: use node:12 container

- plugins/builds/index.js
Should always pass in parentEventId.
This PR passed in parentEventId.
> fix(1710): Always pass in parentEventId

- plugins/builds/index.js
Previous change to pass in `parentEventId` breaks some regular start cases and restarts cases
revert the changes
https://github.com/screwdriver-cd/screwdriver/pull/1964
> fix: revert change to parent event id

- plugins/events/create.js
- test/plugins/events.test.js
Fix https://github.com/screwdriver-cd/screwdriver/issues/1937
This PR makes the error message easy to understand. This message is used UI to show SCM action link. I will make another PR to UI.
https://github.com/screwdriver-cd/ui/pull/530
> fix(1937): fix error message when SCM is different

- README.md
Screwdriver is already support Gitlab SCM now.
update the docs
none
> docs: add Gitlab option for SCM

- plugins/builds/index.js
- test/plugins/builds.test.js
Parallel triggers are not working when there are duplicate pipeline external downstream triggers. This is because the `handleDuplicatePipelines` function is not returning correctly.
This PR fixes the above issue.
> fix(1710): Parallel trigger

- plugins/builds/create.js
`POST /builds` was no longer actively maintain and does not support several new features. We should mark it as deprecated in swagger
We should mark `POST /builds` as deprecated in swagger.
> fix: mark POST /builds as depercated in swagger

- plugins/builds/index.js
- plugins/shutdown.js
We are noticing POST "/build/BUILD_ID" end point failing due to lack of proper error handling. 
While underlying issue is not fixed, this put's a band aid of API processing and causes it to complete without erroring out.
https://github.com/screwdriver-cd/screwdriver/issues/1710
> fix(1710): add error handling

- plugins/builds/index.js
- test/plugins/builds.test.js
The UI doesn't mark external triggers properly at the moment for the new remote join feature.
Before:
This PR passes in the startFrom properly as external triggers.
After:
> fix(1710): Pass in startFrom for external triggers

- plugins/builds/index.js
- test/plugins/builds.test.js
When the trigger circles back to a pipeline without a join case, it should still work. The code was failing trying to get the build ID in parent builds when it doesn't exist (since it is not a join case).
Pipeline 42:
Pipeline 43:
This PR handles the case where the parentBuilds does not contain desired buildId information; also passes in the correct eventId when creating the new build.
> fix(1710): Simple trigger should work

- plugins/webhooks/index.js
1. `ignoreUser` has a default value `[]`.
Therefore, L879 condition become true even if cluster admins don't set `IGNORE_COMMITS_BY`.
We should check `ignoreUser` has any user.
2. GitHub event push webhook sometimes returns `[]` as commits.
https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L1122
In that case, `parsed.commitAuthors` is `[]`.
Array.isArray([]) returns true, L880 commitAuthors become also `[]`. 
Then, `validCommitAuthors` become also `[]`, build is skipped.
We should correctly handle case that `parsed.commitAuthors` is `[]`.
1. Check if ignoreUser.length is not 0.
2. Check if parsed.commitAuthors.length is not 0.
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its …
> fix: Correctly handle ignore user case

- plugins/builds/index.js
Sometimes when the workflow continues in the original event, the sha is incorrect for the internal build.
It tries to use the SHA from the triggering pipeline.
Something like the following:
A:JobA > B:jobA> C:jobA-> B:JobB
b:jobB fails at SCM step because it uses wrong SHA from C:jobA
This PR passes in the event's original sha to the internal build config.
Before:
After:
> fix(1710): Fix sha for internal build

- design/sd-local.md
We implemented the `--env` and `--env-file` options in screwdriver-cd/sd-local#15.
But the behavior when both `--env` and `--env-file` options are used at the same time is not mentioned by the design doc.
This PR adds the details of env options.
screwdriver-cd/sd-local#15
#1314
> design(1314): Update sd-local design about env options

- design/sd-local.md
We are now developing `sd-local` and it always pulls build image each execution.
Therefore this PR suggests adding the option to disable that behaviour to make users run jobs on docker images in local machine.
- add `--always-pull-disable` option.
- #1314 
- screwdriver-cd/sd-local/pull/11
> design(1314): add `--disable-image-pull` option

- features/support/world.js
- plugins/events/create.js
- test/plugins/events.test.js
Should throw a more specific error when `startFrom` is missing.
`startFrom` is not required when `buildId` is passed in.
This PR adds a check for `startFrom`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2026
> fix(2026): Check for startFrom for event create [2]

- README.md
Some plugins are not in the docs,  so add them to the docs.
update the docs
https://github.com/screwdriver-cd/screwdriver/blob/master/lib/registerPlugins.js
> docs: [skip ci] update plugins

- plugins/builds/index.js
Eslint disable comment is not needed any more. 
Remove eslint disable section.
> fix: remove eslint disable comment

- plugins/secrets/index.js
- plugins/secrets/remove.js
- plugins/secrets/update.js
- test/plugins/secrets.test.js
Currently only user token can delete and update secrets. We should also allow pipeline token for more flexibility.
Allow pipeline token to delete and update secrets.
#1847 
> fix(1847): Allow pipeline token to remove and update secret

- design/sd-local.md
Update sd-local design docs for adding `--local` option.
https://github.com/screwdriver-cd/sd-local/pull/24
> design(1314): add description of `--local` option

- plugins/builds/index.js
- test/plugins/builds.test.js
When user has a pipeline like below, an extra event is getting triggered.
Pipeline 52:
Pipeline 53:
Pipeline 54:
This PR does a check to make sure the issue above does not happen by getting the workflowGraph and checking if the downstream external trigger has a join.
Related #1710 
> fix: When external downstream trigger is part of a join, should not be triggered by external event

- plugins/builds/index.js
Need pipeline and job data to find missing build. The build data is not available at all after it is deleted.
This PR adds pipelineId and jobName to the log.
> fix: Add more data to error message

- plugins/builds/index.js
- test/plugins/builds.test.js
It's possible join jobs are getting triggered for old events.
This PR adds logic to check if the eventId matches for nextBuild and current build if the next build is internal.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2070
> fix(2070): Add check for same event ID for internal join job

- config/custom-environment-variables.yaml
- config/default.yaml
Add runtime class config to support kata for kubernetes version v1.12.0 or above [kata-containers-as-a-runtimeclass](https://github.com/kata-containers/documentation/blob/master/how-to/containerd-kata.md#kata-containers-as-a-runtimeclass).
[Evaluate Kata Containers over HyperD](https://github.com/screwdriver-cd/screwdriver/issues/818)
[executor-k8s PR#121](https://github.com/screwdriver-cd/executor-k8s/pull/121)
> feat(818): add runtimeclass config for kata

- plugins/events/create.js
- test/plugins/events.test.js
When PR builds are restarted by API call, prSource information is disappear.
Because of this, restarted PR builds cannot trigger next Jobs.
Add prSource to payload when an event is created by API call.
#2029 
> fix(2029): [3] Get prSource from prInfo

- plugins/builds/index.js
- test/plugins/builds.test.js
Currently, we're seeing errors in our logs trying to get jobId info from the workflowGraph during triggerNextJobs function. This is because sometimes the node name saved in the graph is the full external trigger name, not just the shortened job name.
This PR
- adds additional logic to get the jobId information when triggering the next job; this should fix an issue where external pipelines with circular workflows don't trigger the later build
- adds try/catch logic around handling triggering external jobs with matching pipelines
- gets eventId info from the build itself for parentBuilds rather than just using the current build's event info
With three pipelines: 2, 3, and 4, imagine an overall workflow that works like this:
2 -> 3 -> 4 -> 2
Before: The workflow would work like this 2 -> 3 …
> fix: Add additional logic for getting jobId for trigger

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
Currently, even if we create a tag, it does not start to build unless it matches changedFiles. Tag/Release triggers need to start built without depending on the changedFiles.
Fixed to start build regardless of changedFile for tag/release triggers.
https://github.com/screwdriver-cd/models/pull/454
> fix: [2] Tag/Release trigger does not depend on changedFile

- plugins/webhooks/index.js
Before this PR, screwdriver.cd makes incomplete pipelines for the repository which has no `screwdriver.yaml` because `pipeline.sync` failed when no `screwdriver.yaml` is found and `pipeline.annotation` in DB become `NULL` value.
Therefore this PR makes it possible to handle the `NULL` value in `pipelines.annotations` and create PR events that add `screwdriver.yaml` at first time.
Assign empty objects to `pipelines.annotations` when it is undefined.
#2094 
> fix(2094): [2] workaround for NULL value in `pipeline.annotations`

- plugins/pipelines/openPr.js
currently openPr returns 500 because it passed null token to scm-base
pass real token instead
https://github.com/screwdriver-cd/screwdriver/issues/1922
> fix(1922): nil token

- plugins/pipelines/openPr.js
- test/plugins/pipelines.test.js
UI expects return value to be a String that can be parsed via `JSON.parse`, if it is plain String like `thisisaStingValue`, then it will throw errors.
Change return value from `String` to `Object`, so can be parsed by `JSON.parse`
> fix: openPR return object instead of plain string

- plugins/pipelines/caches/request.js
- test/plugins/caches.test.js
BuildCluster names are needed to push to rabbit queues
This PR fixes an issue with fetching the cluster names
> fix: get cluster names from list

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
https://github.com/screwdriver-cd/screwdriver/issues/2128
Pipelines are breaking when Github release is created without a name and if pipeline doesn't have a release trigger.
Release names can be empty string, but tag names must be present
> fix(2128): ignore empty release/tag trigger names

- plugins/jobs/listBuilds.js
Some users might want to list builds using a build token.
This PR adds build scope to listBuilds endpoint.
> fix: Add build scope to listBuilds endpoint

- plugins/builds/index.js
triggerNextBuild function could throw error because job was not found in workflowgraph
add null check and logging for further investigation
> fix: add null check to trigger next build

- config/custom-environment-variables.yaml
- config/default.yaml
Need a feature flag to support enterprise edition of SonarQube as well as open source edition.
This PR adds a feature flag `sonarEnterprise`.
Related to #2152 
> feat(2152): Add enterprise config for SonarQube

- plugins/builds/index.js
- test/plugins/builds.test.js
When creating externalBuild in childpipeline,  `configPipelineSha` is not set in the event.
However, `configPipelineSha` is needed to create child pipeline's event.
https://github.com/screwdriver-cd/models/blob/4f0d1f9b54927222f47840ae8ede18d815c4b66b/lib/eventFactory.js#L614-L626
Add configPipelineSha when creating childpipeline event.
screwdriver-cd/screwdriver#2148
> fix(2148): Add configPipelineSha when create childpipeline event

- package.json
- plugins/coverage/README.md
- plugins/coverage/info.js
- plugins/coverage/token.js
- test/plugins/coverage.test.js
It would be nice if users could configure projectKey/name scope based on an annotation. 
This PR fetches job annotations in the API so it can easily be passed to the coverage sonar plugin. Alternatively, if `scope` query param is passed in, the API will skip fetching.
Related to #2152 
> feat(2152): Support coverage scope param [3]

- .gitignore
- features/step_definitions/trigger.js
- features/support/world.js
- features/trigger.feature
- package.json
- screwdriver.yaml
(#2159) caused failure of beta functional test.
The reason was that functional test didn't work on beta.
So, I solved this problem.
this PR diff
https://github.com/screwdriver-cd/screwdriver/pull/2166/commits/969592a3f9529d826372cf928cb6a6396c5416de
- Remote join acceptance test enable work on beta
- Add required jobs in beta
- change test pipeline name (to clearly separate by beta functional test)
- remote1 -> remote_join1, beta-remote_join1
- remote2 -> remote_join2, beta-remote_join2
- remoteA -> external_trigger1
- remoteB -> external_trigger2
- Add remote join & external join accesptance test (#2159)
- Refactor trigger.js, world.js (#2159)
- functional-trigger test branch (example)
- https://github.com/screwdriver-cd-test/functional-trigger/tree/beta-remote_join1
I confirm that this …
> fix: support only beta jobs

- plugins/coverage/README.md
- plugins/coverage/index.js
- plugins/coverage/info.js
- plugins/coverage/token.js
- test/plugins/coverage.test.js
When users open PRs, we should take advantage of Sonar PR analysis so new projects are not created.
This PR adds logic to get scope, jobId, and jobName for PRs for Sonar coverage plugin.
Related to #2152 
> fix(2152): Support PR analysis for coverage info [3]

- lib/registerPlugins.js
- package.json
- plugins/metrics.js
- plugins/promster.js
- test/lib/registerPlugins.test.js
Screwdriver.cd has no application metrics, except build metrics, and cluster admins are hard to find what problems is happend on the application, for example, 500 error is happend or performances are degraded.
To detect these problems, This PR adds the [promster](https://github.com/tdeekens/promster) plugins to collect the metrics about nodejs and http.
- `plugins/promster.js` to collect http and nodejs metrics
- `plugins/metrics.js` to expose the collected metrics
It can collect the metrics like following
Please refer the documents for more details
https://github.com/tdeekens/promster#-documentation
https://github.com/screwdriver-cd/screwdriver/issues/2115
https://github.com/tdeekens/promster
I confirm that this contribution is made under a BSD license and that I have the authority …
> fix(2115): add metrics plugins

- plugins/auth/contexts.js
- plugins/pipelines/create.js
- test/plugins/auth.test.js
- test/plugins/pipelines.test.js
Fixes screwdriver-cd/screwdriver#1079
This PR adds functionality of handling of autoKeysGeneration visibility in the UI and its response to trigger it in the scm-github module. 
screwdriver-cd/screwdriver#1079
> feat(1079): integrate deploy keys features with auth and pipeline routes [5]

- features/trigger.feature
- package.json
Pipeline is broken because remote join fn test don't work in beta
https://cd.screwdriver.cd/pipelines/1/events
> fix: ignore remote join tests in beta to unblock pipeline

- features/trigger.feature
Disable another flaky test in beta
Tests are flaky and pipeline needs to be unblocked.
https://cd.screwdriver.cd/pipelines/1/builds/437199/steps/test
> fix: disable one more test in beta

- plugins/pipelines/create.js
- test/plugins/pipelines.test.js
Fixes screwdriver-cd/screwdriver#1079
This PR sets the allowInPr to true in create pipeline deploy key secret creation
screwdriver-cd/screwdriver#1079
> feat(1079): Set allowInPr to true in create pipeline deploy key secret

- plugins/pipelines/update.js
- test/plugins/pipelines.test.js
Fix for issue of https://github.com/screwdriver-cd/screwdriver/issues/1954.
When you change the repository from the options page, add a webhook to the new github repository.
https://github.com/screwdriver-cd/screwdriver/issues/1954
I fixed it in the same way as create.
https://github.com/screwdriver-cd/screwdriver/blob/9625f1477dd2402b03a901c6c42f25765d08afca/plugins/pipelines/create.js#L149-L163
> fix(1954): add webhook sync

- package.json
executor-base v7.6.0 has the latest version of data-schema with all the hapi changes, which breaks the duplicate step in screwdriver: https://cd.screwdriver.cd/pipelines/1/builds/474900/steps/duplicate
This PR temporarily pins executor-base to v7.5.0 while we wait for all the hapi changes to roll out.
Related to https://github.com/screwdriver-cd/executor-base/pull/65
> fix: Pin to executor-basev7.5.0 while we wait for hapi changes to roll out

- plugins/builds/update.js
Sometimes users might want to abort a build using a pipeline token.
This PR adds pipeline scope to the build update endpoint.
> fix: Add pipeline scope for build update

- features/trigger.feature
The feature test of remote join in beta has been ignored at https://github.com/screwdriver-cd/screwdriver/pull/2171 because the test was failed in only beta.
Now I run the test locally for beta and all tests are successful. I tried it several time and no failures.
```
$ npm run functional-beta
> screwdriver-api@0.5.0 functional-beta /Users/shoyoshi/repo/github/screwdriver
> cucumber-js --format=progress --tags '(not @ignore) and (not @prod)' --retry 2 --fail-fast --exit
.........................................................................................................................................................................................................................................................................................................................
42 …
```
> fix: enable remote join tests in beta

- package.json
SD API version needs a major version upgrade after Hapi upgrade
This PR upgrades to version 4.0.0 as API already published till version 3.4.71.
https://www.npmjs.com/package/screwdriver-api
https://github.com/screwdriver-cd/screwdriver/issues/1958
> feat(1958): Correct major version. BREAKING CHANGE: hapi v20

- config/custom-environment-variables.yaml
- config/default.yaml
- features/support/github.js
- plugins/coverage/README.md
- plugins/coverage/token.js
Users should be able to configure the name for their Github App for PR decoration with Sonar.
This PR
- adds configuration options and passes in projectName as param for getting Sonar token
- updates how we're calling Octokit in functional tests (related to https://github.com/screwdriver-cd/screwdriver/issues/2173)
Related to #2198 
> fix(2198): Add support for automated Sonar Git App PR decoration [2]

- features/data/invalid-template.yaml
Functional test template structure has an invalid maintainer field
This PR fixes the functional test template
> feat: fix template issue

- features/step_definitions/templates.js
Functional test template validation message is incorrect
This PR fixes the functional test template validation message
> feat: fix validation message

- package.json
`/v4/documentation` is broken with hapi update.
This PR updates hapi-swagger package to fix documentation.
Before:
After:
- Related to https://github.com/screwdriver-cd/screwdriver/issues/1958
- hapi-swagger compatibility: https://www.npmjs.com/package/hapi-swagger#compatibility
> feat(1958): Update hapi-swagger to v14

- plugins/commands/list.js
- plugins/templates/list.js
any.describe() fn on the models is scanning the entire model and returning a nested object while we are only interested in the keys in the object and don't need this processing.
This pr removes the unnecessary describe on schema and instead used fields which gives the keys
https://github.com/screwdriver-cd/screwdriver/issues/2216
> feat: remove describe() on schema and use available fields

- screwdriver.yaml
Now that we have bumped Screwdriver to a major version, we can use semantic release template to publish new versions.
This PR switches to using semantic-release template.
> fix: Use template

- screwdriver.yaml
Build expects GH_TOKEN. 
This PR adds GH_TOKEN.
> fix: Add expected GH_TOKEN key

- package.json
Missing semantic release script in package.json.
This PR adds semantic release script in package.json.
> fix: Add semantic release script

- plugins/builds/steps/logs.js
token expires before api fetch all logs from store, leading to incomplete log file
extend token expiration time
https://github.com/screwdriver-cd/screwdriver/issues/2068
> fix: extend token expiration time

- test/plugins/data/validator.output.json
[The test is failing](https://cd.screwdriver.cd/pipelines/1/builds/577299/steps/test) with the following error.
The following PR adds `subscribe` field.
https://github.com/screwdriver-cd/config-parser/pull/109
https://github.com/screwdriver-cd/screwdriver/issues/1415
> fix(1415): add subscribe

- package.json
- plugins/pipelines/create.js
- plugins/pipelines/syncWebhooks.js
- plugins/pipelines/update.js
- test/plugins/caches.test.js
- test/plugins/pipelines.test.js
I'm getting an error `data: TypeError: pipeline.addWebhook is not a function` when creating the pipeline.
Due to the following PR in [models@v23.3.0](https://github.com/screwdriver-cd/models/releases/tag/v28.3.0), `addWebhook` is now changed to `addWebhooks`.
https://github.com/screwdriver-cd/models/pull/472/files#diff-2977a16e13f278992ce964024e936111d8f1c3b68f5f698c7e06195258912721L383-R384
I want pass test step.
https://cd.screwdriver.cd/pipelines/1/builds/577559/steps/test
https://github.com/screwdriver-cd/models/pull/472
Related to https://github.com/screwdriver-cd/screwdriver/issues/1415
> fix(1415): models@v28.3.0

- screwdriver.yaml
Using the semantic template prevents us from publishing API with changes only in dependencies. 
Revert https://github.com/screwdriver-cd/screwdriver/pull/2226
> fix: revert template usage on publish

- config/custom-environment-variables.yaml
- config/default.yaml
- lib/registerPlugins.js
- package.json
- plugins/auth/contexts.js
- plugins/auth/crumb.js
- plugins/auth/key.js
- plugins/auth/login.js
- plugins/auth/token.js
- plugins/banners/get.js
- plugins/banners/list.js
- plugins/command-validator.js
- plugins/metrics.js
- plugins/pipelines/badge.js
- plugins/pipelines/jobBadge.js
- plugins/ratelimit.js
- plugins/stats.js
- plugins/status.js
- plugins/swagger.js
- plugins/template-validator.js
- plugins/validator.js
- plugins/versions.js
- plugins/webhooks/index.js
- test/lib/registerPlugins.test.js
Given large enough user base, API might be subject to unexpected intense usage pattern from users. Providing an optional protection mechanism in place to limit the number of API request from each authenticated request would be helpful to maintain a healthy API service.
- Add a rate limiting plugin behind a feature flag 
- Exclude rate limiting for paths which do not require authentication
- GET /v4/auth/contexts
- GET /v4/auth/crumb
- GET /v4/auth/key
- GET /v4/auth/login/guest/{web?}
- GET /v4/auth/token/{buildId?}
- This one is special because it takes in api_token (user/pipeline’s) and generates auth token whose jti field would be cache keyed if consumed on endpoints requiring authentication
- GET /v4/banners
- GET /v4/banners/{id}
- GET /v4/documentation
- GET /v4/metrics
- GET …
> feat(ratelimit): add rate limiting

- package.json
When API docker image is being built it's not pulling latest scm-base https://beta.api.screwdriver.cd/v4/versions
My guess is it's because upstream packages like scm-router were built with 7.1.0
> fix: bump up scm-base dependency to force new version

- package.json
API npm package version is updated by [npm-auto-version](https://www.npmjs.com/package/npm-auto-version).
This package updates tag based on version in package.json.
So new tag is `v4.0.X`.
https://github.com/screwdriver-cd/screwdriver/tags
However, we had already tagged `v4.1.0` by template in [this build](https://cd.screwdriver.cd/pipelines/1/builds/578833).
Therefore, we use `v4.1.0` as latest tag instead of `4.0.X`.
> fix: Bump up API npm version

- plugins/swagger.js
Allow user to add bear token on `http://localhost:9001/v4/documentation` or `https://api.screwdriver.cd/v4/documentation`
Before:
After:
https://github.com/glennjones/hapi-swagger/issues/602
> fix: allow Swagger to add Bear Token field

- plugins/pipelines/list.js
- test/plugins/pipelines.test.js
list pipelines may return enormous data given large enough cluster, and it's better to put default size limiting in place
default pagination for list pipelines without search query
> fix!: restrict list pipelines size

- config/default.yaml
- lib/server.js
- test/lib/server.test.js
Cookie timeout should be controlled via separate config 
This PR adds a cookie timeout in config
> feat: add cookie timeout config

- plugins/pipelines/create.js
This PR fixes the missing token error in the create pipeline endpoint of the API
> fix(): Fix missing token error in create endpoint

- plugins/collections/get.js
- test/plugins/collections.test.js
Currently we call pipelineFactory.get() multiple time to get all pipeline under a collection, it's time to move to one single call to pipelineFactory.list()
move to pipelineFactory.list()
https://github.com/screwdriver-cd/screwdriver/issues/2267
> feat(2267): use list instead calling get individually

- plugins/coverage/token.js
- test/plugins/coverage.test.js
Some job-scoped Sonar projects have `undefined:undefined` set as their Github bindings.
This PR sends `jobName` and `pipelineName` when creating Sonar projects and setting Github bindings.
Related to #2313 
> fix(2313): Send pipelineName and jobName when creating Sonar project [1]

- package.json
- plugins/commands/list.js
- plugins/templates/list.js
- test/plugins/commands.test.js
- test/plugins/templates.test.js
adding a new field `latest` to template and command
use `latest` to query compact mode instead of groupby
https://github.com/screwdriver-cd/screwdriver/issues/2312
> fix(2312): add latest to template and command

- lib/server.js
- package.json
- plugins/template-validator.js
- plugins/templates/create.js
- plugins/templates/createTag.js
Would be nice if template owners could base their templates on other templates.
This PR passes in the template factory to the template validator so the template can be fetched and flattened.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2319
Blocked by https://github.com/screwdriver-cd/template-validator/pull/23
> feat(2319): [3] Support template composition

- plugins/commands/README.md
- plugins/commands/list.js
- plugins/templates/README.md
- plugins/templates/list.js
- test/plugins/commands.test.js
- test/plugins/templates.test.js
It would be nice if we can get total count when paginating template/commands
add support to return count in addition to template/commands
https://github.com/screwdriver-cd/screwdriver/issues/2312
> fix(2312): allow fetching total count of template/command

- bin/server
- config/default.yaml
- lib/registerPlugins.js
- package.json
- plugins/stats.js
- plugins/validator.js
Would be nice if there was an option to not fail build if slack/email notifications are invalid.
This PR adds new flag under `notifications` config to determine if invalid notifications configs should throw error or return warning. Default `true` (throw error).
```
notifications:
options:
throwValidationErr: false
email:
...
slack:
...
```
Related to https://github.com/screwdriver-cd/screwdriver/issues/2339
Blocked by https://github.com/screwdriver-cd/models/pull/488
> feat(2339): [3] Add feature flag for throwing notifications validation errs

- plugins/users/settings/get.js
- plugins/users/settings/update.js
- test/plugins/user.test.js
userId is not exposed to UI easily, and I was able to find my userId by using the return value of creating a pipeline collection. 
Backend needs to find the user by using its username and scmContext
https://github.com/screwdriver-cd/ui/pull/671
> fix: remove user id from url param

- config/default.yaml
Should not throw error when starting with default.yaml.
This PR uncomments the `options` section under notifications to try to fix the start up error.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2354
> fix(2354): Should be able to start with default.yaml

- bin/server
To have local development work, pass executor name to build factory to choose token scope.
https://github.com/screwdriver-cd/screwdriver/issues/2356
> fix(2356): pass executor plugin name to build factory

- plugins/pipelines/latestCommitEvent.js
- test/plugins/pipelines.test.js
In order to highlight the latest commit in the event tab, /getLatestCommit should return latest commit of pipeline events (not including the pr event).
Add `type: pipeline` search parameter in order to list only pipeline events.
#2342 
> fix(2342): Search pipeline event for latest commit

- plugins/builds/index.js
- test/plugins/builds.test.js
1. getFinishedBuilds doesn't return build model
2. Prevent _.mergeWith from mutating sources and `null` values needs to be handled properly
https://github.com/screwdriver-cd/screwdriver/pull/2374
> fix: do proper merging of parent build data

- plugins/pipelines/helper.js
- test/plugins/pipelines.test.js
Gitlab requires the path to a file be URI encoded.
This PR URI encodes the rootDir path.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2398
> fix(2398): URI encode rootDir

- plugins/pipelines/helper.js
- test/plugins/pipelines.test.js
Reverts screwdriver-cd/screwdriver#2406
Don't need to encode here
> fix: Revert "fix(2398): URI encode rootDir"

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
- plugins/builds/index.js
- plugins/lock.js
multiple build could be created same job which splits parent build status and will never start
only one build should be created for same job
https://github.com/screwdriver-cd/screwdriver/issues/2071
> fix(2071): trigger next build could create duplicate build

- plugins/builds/update.js
- test/plugins/builds.test.js
Screwdriver needs a way to allow users to abort a build that has entered frozen state
This PR adds check to the update build api for frozen build  status and abort build it via build model
https://github.com/screwdriver-cd/screwdriver/issues/2410
> feat(#2410): Abort frozen build implementation

- plugins/builds/index.js
- test/plugins/builds.test.js
During restart flow, `parentBuilds` is taken from output of `buildFactory.getLatestBuilds` which is not a proper JSON object. This leads to `string` `parentBuilds` getting stored into DB which breaks events.
JSON parse `parentBuilds` explicitly 
https://github.com/screwdriver-cd/screwdriver/pull/2374
> fix: events are broken during restart flow

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
When a timeout occurs in CircuitBreaker, err.status becomes undefined.
Now the following code will be processed successfully.
https://github.com/screwdriver-cd/screwdriver/blob/f1b25fd35576310e9119393cb890ffbb625f1317/plugins/webhooks/index.js#L416-L421
This will cause problems in later processing, Add the case when a timeout occurs in CircuitBreaker.
It also adds information on which pipeline the error occurred.
In this PR, I will add error handling when CircuitBreaker times out in [getCommitSha()](https://github.com/screwdriver-cd/scm-github/blob/4c2a843ce5266a14b27d4788b3cd6d9b8f6e98a3/index.js#L860).
Circuitbreaker will output a log like the following when it times out.
```
Failed to getCommitSha:  CircuitBreaker timeout
```
~~Error handling is done with the `CircuitBreaker timeout` …
> [2] fix: Add error handling for CircuitBreaker timeout

- plugins/builds/index.js
- test/plugins/builds.test.js
Users can use external trigger syntax for same pipeline 🙄 
https://github.com/screwdriver-cd/screwdriver/issues/2432
> fix(2432): support external trigger format for same pipeline

- plugins/commands/removeTag.js
- test/plugins/commands.test.js
The APIs for commands return some kind of response body except for removeTag. In sd-cmd, the implementation assumes that the API for commands returns a response body. So we want to change the API for remove commad tags to return a response body.
- We modify the command removeTag API to return a response body.
- We change the status code returned in normal case from 204 to 200
https://github.com/screwdriver-cd/screwdriver/issues/2399
https://github.com/screwdriver-cd/sd-cmd/blob/master/screwdriver/api/api_test.go#L52-L57
> feat(2399): Change remove command tag API

- plugins/builds/artifacts/get.js
- plugins/builds/steps/logs.js
- plugins/pipelines/index.js
- test/plugins/builds.test.js
Step logs and artifacts should be protected for private pipeline
Add read protection for step logs and artifacts
> feat(466): add read protection against log and artifacts

- plugins/pipelines/listSecrets.js
- plugins/secrets/index.js
- test/plugins/pipelines.test.js
Pipeline tokens should have access to list pipeline secrets.
This PR adds `pipeline` scope to `GET pipelines/:id/secrets`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2462
> fix(2462): Allow pipeline scope for list secrets

- plugins/builds/index.js
- test/plugins/builds.test.js
In createInternalaBuild func, prInfo is not set properly.
I fixed the method creating pfInfo.
In createInternalBuild func, prInfo is set from event object.
However, event has no prInfo property on its data-schema.
https://github.com/screwdriver-cd/data-schema/blob/32d1ef39ca80fbdb3bfbe3d9ddc6dbfdcf94698a/models/event.js#L75
https://github.com/screwdriver-cd/data-schema/blob/32d1ef39ca80fbdb3bfbe3d9ddc6dbfdcf94698a/core/scm.js#L94-L127
prInfo is used in the buildFactory.create for adding url and prBranchName info to event data.
https://github.com/screwdriver-cd/models/blob/d107819e0aadcbb6b31344b32729148c0165ce2a/lib/eventFactory.js#L692-L700
So I add url and prBranchName as prInfo from event object.
#2404 
I confirm that this contribution is made under a BSD license and that I have the …
> fix(2404): Properly set prInfo.

- plugins/pipelines/index.js
- plugins/pipelines/update.js
- test/plugins/builds.test.js
- test/plugins/pipelines.test.js
there could be situation where user need pipeline to stay public despite having a private repo
allow user to set pipeline to public
> fix(466): allow user to set pipeline to public

- package.json
- plugins/webhooks/index.js
- screwdriver.yaml
- test/plugins/buildClusters.test.js
- test/plugins/builds.test.js
- test/plugins/caches.test.js
- test/plugins/events.test.js
- test/plugins/jobs.test.js
- test/plugins/pipelines.test.js
- test/plugins/secrets.test.js
Screwdriver tests are failing due to memory and performance issues 
This PR fixes some of the test functions which are constantly at the top of the stack and are slow by adding mocks wherever necessary.
https://github.com/screwdriver-cd/screwdriver/issues/2483
> fix: missing mocks for libs and perf issues

- plugins/pipelines/startAll.js
Username was not being passed as a string.
This PR fixes username param for event create in `POST pipelines/:id/startall` endpoint.
No longer need to worry about username here, as it will be handled in [scm-base](https://github.com/screwdriver-cd/scm-base/pull/88).
Related to https://github.com/screwdriver-cd/screwdriver/issues/2437, https://github.com/screwdriver-cd/screwdriver/pull/2460
> fix(2437): Pass in username to startAll [3]

- plugins/buildClusters/create.js
- plugins/buildClusters/update.js
- plugins/helper.js
- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
Should be able to pass in scmContext to buildcluster endpoints.
Also should not try to get user token for webhooks.
This PR:
- allows user to pass `scmContext` for `POST/PUT buildcluster`
- checks for read-only SCM and uses read-only token when appropriate
Related to https://github.com/screwdriver-cd/screwdriver/issues/2437
> fix(2437): Handle webhooks for read-only SCM [2]

- plugins/pipelines/list.js
- test/plugins/data/privatePipelines.json
- test/plugins/pipelines.test.js
guest login now throws 500 error when searching pipelines and pipeline admin should be able to search private pipeline
fix both 
> fix(466): allow search for pipeline admin and guest

- plugins/builds/update.js
Since #2485 is merged, QUEUED notifications are not sent. When a build is started in the executor [here](https://github.com/screwdriver-cd/queue-service/blob/491b969df61bd3d1c7070833c1f2b05368eae265/plugins/queue/scheduler.js#L394), queue-service calls `/builds/{id}` without `status`. Then `build.status` is set to `undefined` [here](https://github.com/screwdriver-cd/screwdriver/blob/bf1588e5195fa950c0cc0b9b62de55e35530359b/plugins/builds/update.js#L223). Because of this, `QUEUED` notifications are no longer sent to Slack. Originally, if `desiredStatus` was `undefined`, `build.status` was not changed because of [this](https://github.com/screwdriver-cd/screwdriver/blob/69e3d7c466b02363951f328f7458e2a9cce6d471/plugins/builds/update.js#L142-L148).
This PR changes `updateBuildStatus` of …
> fix(2507): fix QUEUED notification

- package.json
- plugins/builds/artifacts/get.js
- plugins/helper.js
- test/plugins/builds.test.js
previous logic for artifact endpoint did not return proper header
read header from store response instead
> fix: return property header for artifact endpoint

- features/step_definitions/workflow.js
- package.json
Existing chainPR functional tests will fail if the tests are run in parallel or if there is any PR left from the previous run.
The reason is that it uses a single branch.
Also, PR close is not stable because it uses the `--exit` option when starting `cucumber.js`.
This is deprecated and should be removed.
https://github.com/cucumber/cucumber-js/blob/main/docs/cli.md#exiting
In this PR, modify the test run to test on a unique branch. (ex branchName: testpr-12345678)
Specifically, it uses the [time](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime) as the postfix.
And fix the option when starting `cucumber.js`
Previous PRs
- https://github.com/screwdriver-cd/screwdriver/pull/2527
- https://github.com/screwdriver-cd/screwdriver/pull/2515
related: …
> fix: simple functional test of chainPR

- features/workflow.feature
- package.json
Related to  https://github.com/screwdriver-cd/screwdriver/issues/2534
In this PR, the `--exit` option will be enabled until the cause of the build timeout is known.
Also, if the `--exit` option is enabled, the chainPR function test will not work properly, so`@ignore` it.
Make sure that functional tests do not fail.
https://github.com/screwdriver-cd/screwdriver/issues/2534
https://github.com/screwdriver-cd/screwdriver/pull/2533
> fix:(2534) Enabling the --exit option in cucumber.js

- plugins/builds/artifacts/get.js
- test/plugins/builds.test.js
get artifact should default to preview due to store change
get artifact should default to preview due to store change
> fix: default get artifact request to preview

- features/step_definitions/server.js
- features/support/sdapi.js
Getting error with `cleanupToken()` in feature test:
```
16:05:38 1) Scenario: Generate New API Token (attempt 3) # features/api-token.feature:19
16:05:38    ✔ Before # features/step_definitions/api-token.js:9
16:05:38    ✔ Given "calvin" is logged in # features/step_definitions/authorization.js:19
16:05:38    ✖ Given "calvin" does not own a token named "tiger" # features/step_definitions/api-token.js:15
16:05:38        SyntaxError: Unexpected token o in JSON at position 1
16:05:38            at JSON.parse (<anonymous>)
16:05:38            at /sd/workspace/src/github.com/screwdriver-cd/screwdriver/features/support/sdapi.js:241:28
16:05:38            at processTicksAndRejections (internal/process/task_queues.js:97:5)
16:05:38    - When a new API token named "tiger" is generated # …
```
> fix(1961): Do not need to JSON parse response

- features/step_definitions/api-token.js
- features/step_definitions/authorization.js
- features/step_definitions/collection.js
- features/step_definitions/git-flow.js
- features/step_definitions/sd-step.js
- features/step_definitions/workflow.js
- features/support/constants.js
- features/support/world.js
409 throws error with new screwdriver-request package:
```
14:37:53 1) Scenario: List API Tokens (attempt 3) # features/api-token.feature:26
14:37:53    ✔ Before # features/step_definitions/api-token.js:9
14:37:53    ✔ Given "calvin" is logged in # features/step_definitions/authorization.js:19
14:37:53    ✖ Given "calvin" owns an existing API token named "tiger" # features/step_definitions/api-token.js:71
14:37:53        Error: 409 Reason "Token with name tiger already exists"
14:37:53            at throwError (/sd/workspace/src/github.com/screwdriver-cd/screwdriver/node_modules/screwdriver-request/index.js:14:17)
14:37:53            at /sd/workspace/src/github.com/screwdriver-cd/screwdriver/node_modules/screwdriver-request/index.js:56:28
14:37:53            at processTicksAndRejections …
```
> fix(1961): 409 will throw error

- plugins/builds/artifacts/get.js
- plugins/builds/steps/logs.js
- plugins/pipelines/create.js
- test/plugins/builds.test.js
Getting errors with [getMaxLines](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/steps/logs.js#L35) because got throws error for 404:
```
{"name":"HTTPError","timings":{"start":1631133820277,"socket":1631133820278,"lookup":1631133820313,"connect":1631133820316,"secureConnect":1631133820321,"upload":1631133820321,"response":1631133820379,"end":1631133820381,"phases":{"wait":1,"dns":35,"tcp":3,"tls":5,"request":0,"firstByte":58,"download":2,"total":104}},"level":"error","timestamp":"2021-09-08T20:43:40.382Z"}
210908/204340.383, (1631133820241:sdapi-beta-6f49c864b-hrmnd:18:ktbywcvt:10022) [request,server,error] data: Error: HTTPError: Response code 404 (Not Found)
at getMaxLines (/usr/src/app/node_modules/screwdriver-api/plugins/builds/steps/logs.js:72:15)
at …
```
> fix: Logs should not throw when store returns 404

- features/step_definitions/collection.js
- features/step_definitions/sd-cmd.js
- features/step_definitions/secrets.js
- features/step_definitions/server.js
- features/support/world.js
Functional tests still failing with new request package changes:
```
19:00:40 2) Scenario: Revoke API Token (attempt 1, retried) # features/api-token.feature:38
19:00:40    ✔ Before # features/step_definitions/api-token.js:9
19:00:40    ✔ Given "calvin" is logged in # features/step_definitions/authorization.js:20
19:00:40    ✔ Given "calvin" owns an existing API token named "tiger" # features/step_definitions/api-token.js:71
19:00:40    ✔ When he revokes the token # features/step_definitions/api-token.js:165
19:00:40    ✖ And the token is used to log in # features/step_definitions/api-token.js:45
19:00:40        Error: 401 Reason "Bad token"
19:00:40            at throwError (/sd/workspace/src/github.com/screwdriver-cd/screwdriver/node_modules/screwdriver-request/index.js:14:17)
19:00:40 …
```
> fix(1961): Catch errors and handle in func tests

- features/support/world.js
- features/workflow.feature
- plugins/pipelines/caches/request.js
Retry was not working as expected in functional tests.
```
21:29:18 1) Scenario: Create an event when user starts a job (attempt 3) # features/events.feature:34
21:29:18    ✔ Before # features/step_definitions/events.js:9
21:29:18    ✔ Given an existing pipeline with the workflow: # features/step_definitions/events.js:18
21:29:18        | job  | triggers |
21:29:18        | main | publish  |
21:29:18    ✔ And "calvin" has admin permission to the pipeline # features/step_definitions/events.js:22
21:29:18    ✔ And "calvin" is logged in # features/step_definitions/authorization.js:20
21:29:18    ✔ When the "main" job is started # features/step_definitions/secrets.js:48
21:29:18    ✔ Then an event is created # features/step_definitions/events.js:24
21:29:18    ✖ And the "main" build succeeds …
```
> fix(1961): Retry with new request package

- features/step_definitions/trigger.js
- features/support/github.js
- features/trigger.feature
This PR adds smallest functional tests to keep the quality  sourcePath.
This PR adds a new test for sourcePath. Details can be found in the feature file.
To run this functional test, please prepare the following repository and screwdriver.yaml.
The administrator of screwdriver should be ready.
1. Create a `functional-sourcePath` repository [here](https://github.com/screwdriver-cd-test)
2. Add `screwdriver.yaml` to the `master` branch of `functional-sourcePath`.
`screwdriver.yaml`:
```
shared:
image: node:14
jobs:
job1:
requires: [ ~commit ]
sourcePaths:
- directory1/
steps:
- echo: echo "this is build1"
job2:
requires: [ ~commit ]
sourcePaths:
- directory2/
steps:
- echo: echo "this is build2"
```
- Related Issue
- https://github.com/screwdriver-cd/screwdriver/issues/1393
I confirm that …
> fix(1393): Add sourcePath functional test

- features/step_definitions/templates.js
To make preparing template functional tests added by this [PR](https://github.com/screwdriver-cd/screwdriver/pull/2593) easier.
This PR will be mergeable after following PRs are merged.
- https://github.com/screwdriver-cd-test/functional-template/pull/1
- https://github.com/screwdriver-cd-test/functional-template/pull/2
I will move `use-template` and `custom-template` jobs from `master` branch to `wrong-permission` branch.
And rename `wrong-permission` branch to `second`.
Then we don't have to comment out and uncomment when [prepare pipelines](https://github.com/screwdriver-cd/screwdriver/pull/2593)
- PR
- https://github.com/screwdriver-cd-test/functional-template/pull/1
- https://github.com/screwdriver-cd-test/functional-template/pull/2
- Issue
- …
> fix(1393): Make it easier to prepare template functional tests

- features/artifacts.feature
- package.json
~The beta doesn't have aws lamda, so I can't unzip it.~
~However. I think it's expensive to add aws lamda to beta for functional test of artifacts, so I'll set beta to ignore functional test.~
OSSD does not have aws lamda, so ignore the SD_ZIP_ARTIFACTS function test.
Added a setting  to ignore functional tests in artifacts.
#1500 
> fix(1500): Ignore zip artifacts functional test

- features/step_definitions/user-teardown-step.js
- features/user-teardown-step.feature
Add some functional tests for [user teardown steps](https://docs.screwdriver.cd/user-guide/configuration/jobconfiguration.html#steps).
This PR adds some functional tests for user teardown steps.
To run these functional tests, please prepare the following repository.
The administrator of screwdriver should be ready please.
1. Create `functional-user-teardown-step` repository in [screwdriver-cd-test](https://github.com/screwdriver-cd-test).
2. Add following `screwdriver.yaml` to the `master` branch of `functional-user-teardown-step`.
`screwdriver.yaml`
```yaml
shared:
image: node:14
jobs:
success:
requires: [ ~commit ]
steps:
- main: echo "main step"
- teardown-when-succeed: echo "teardown-when-succeed step"
failure:
requires: [ ~commit ]
steps:
- main: exit 1
- not-executed: echo …
```
> fix(1393): Add functional tests for user teardown steps

- plugins/events/README.md
- plugins/events/listBuilds.js
- plugins/jobs/README.md
- plugins/jobs/listBuilds.js
- test/plugins/events.test.js
- test/plugins/jobs.test.js
Some endpoints don't need to fetch step info for builds.
This PR adds option to set query param `steps=true` if a user wants to fetch steps alongside build info for certain endpoints. Also uses readOnly DB to get build info.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1956
> fix(1956): Do not get step info for event and job API

- plugins/builds/index.js
- test/plugins/builds.test.js
Reverts screwdriver-cd/screwdriver#2611
Causing failures in trigger feature for functional test: https://cd.screwdriver.cd/pipelines/1/builds/757573/steps/test
> Revert "fix(2526): Restart failed build in join workflow should trigger join job"

- plugins/builds/artifacts/unzip.js
- plugins/builds/index.js
- test/plugins/builds.test.js
To implement SD_ZIP_ARTIFACTS feature by [new design](https://github.com/screwdriver-cd/screwdriver/blob/0962d20d251c0b7c03d40b7e4b10bb1ed009831d/design/sd-zip-artifacts.md)
Please refer the following for the progress of this feature.
https://github.com/screwdriver-cd/screwdriver/issues/1500#issuecomment-998382248
This PR adds a new endpoint for `/builds/{id}/artifacts/unzip` to accept the `unzip` request from `artifacts-bookend` step in a build and to request for queue-service to unzip.
In the picture of design doc, this fix apply to the following area.
This PR depends on following PRs.
- https://github.com/screwdriver-cd/executor-base/pull/75
- https://github.com/screwdriver-cd/executor-queue/pull/97
- https://github.com/screwdriver-cd/models/pull/520
[design …
> fix(1500): [4] add a new endpoint for POST /builds/{id}/artifacts/unzip

- plugins/builds/index.js
- test/plugins/builds.test.js
As reported in issue https://github.com/screwdriver-cd/screwdriver/issues/2612, a build that finished with SUCCESS status may be changed to QUEUED status.
Fix it so that it will not start building if the status is other than CREATED.
If build status is undefined, I leave the starting behavior for backward compatibility.
https://github.com/screwdriver-cd/screwdriver/issues/2612
> fix(2612): build to not start if it is not CREATED

- bin/server
- config/custom-environment-variables.yaml
- config/default.yaml
- lib/server.js
- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
This is the implementation that follows https://github.com/screwdriver-cd/screwdriver/pull/2622.
I modify the webhook plugin to POST the webhook received from SCM to the queue service endpoint `/v1/queue/message?type=webhook` when `queueWebhookEnabled` is true.
- Add `queueWebhookEnabled` to config so that users can choose whether or not to queue the webhook.
- Add an object `queueWebhook` to `server.app` so that the following items can be used from the plugins.
- Whether or not to use the queueWebhook set in config.
- An instance of the executor plugin.
- Make the `executor.enqueueWebhook` method to POST to `/v1/queue/message?type=webhook` to be executed according to the `queueWebhookEnabled` setting.
Please do not merge this PR until after the following PRs have been merged.
- …
> feat(1769): [3] Modify webhook plugin to use queue webhook

- plugins/builds/index.js
- test/plugins/builds.test.js
When a build fails in a join workflow, restarting that job should trigger join successfully. Note: need to test in beta
This PR removes duplicate logic to get latest builds.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2526
> fix(2526): Restart failed build in join workflow should trigger join job

- bin/server
- config/custom-environment-variables.yaml
- config/default.yaml
- lib/server.js
- plugins/builds/artifacts/unzip.js
- test/plugins/builds.test.js
To implement SD_ZIP_ARTIFACTS feature by [new design](https://github.com/screwdriver-cd/screwdriver/blob/0962d20d251c0b7c03d40b7e4b10bb1ed009831d/design/sd-zip-artifacts.md)
Enable the unzip function to be managed by the feature flag.
The bookend PR is [here](https://github.com/screwdriver-cd/artifact-bookend/pull/38).
- Add feature flag for unzip
- Add test
[design doc](https://github.com/screwdriver-cd/screwdriver/blob/0962d20d251c0b7c03d40b7e4b10bb1ed009831d/design/sd-zip-artifacts.md#sd-api-api)
[issue](https://github.com/screwdriver-cd/screwdriver/issues/1500)
> [1]  fix(1500): add feature flag for unzip artifacts

- plugins/webhooks/helper.js
- test/plugins/webhooks.test.js
Ensure that all individual event creations gets processed. `Promise.all` fails on first failure, however we do want to ensure that all events are processed. We might have to look and fix similar patterns across codebase. 
1. Use `Promise.allSettled` to ensure that all Promises are processed. 
2. Log errors for event creation failure
> fix(2640): errors in individual event processing should not affect rest of event creation

- plugins/pipelines/create.js
- plugins/pipelines/update.js
- test/plugins/pipelines.test.js
Screwdriver needs to support user configuration for using deploy keys for `git checkout`
This PR allows users to opt-in for using git deploy keys and creates them on pipeline creation /update
> feat: Add support for opt-in git deploy keys

- plugins/webhooks/helper.js
Wrong value was being logged on error
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled
> fix: correct logged value on create event error

- plugins/events/create.js
- test/plugins/events.test.js
When scm host that user logged in does not match pipeline's scm host, the 500 error is returned.
However, since this is an authorization error caused by users, the 403(or 404 when private) error should be returned.
- Add error handling for [this error](https://github.com/screwdriver-cd/scm-github/blob/a12f1e0bd9bd24b1d03c55cb6dbfe220d109f347/index.js#L254-L257).
- https://github.com/screwdriver-cd/scm-github/pull/202
> fix: return 403 or 404 error when mismatch scm host

- Dockerfile.local
- package.json
- plugins/builds/artifacts/unzip.js
- test/plugins/builds.test.js
Enable the admin user to unzip manually.
- Add `user` in scope
- Check if the sender has admin privileges when a request comes in with user scope
- Add test
- node version up 8 -> 12
- Because [this problem](https://github.com/outmoded/sntp/issues/37) occurred when I build with node8.
https://github.com/screwdriver-cd/screwdriver/pull/2616#discussion_r771112502
> fix(1500): Add admin user unzip

- features/events.feature
- features/step_definitions/events.js
The current feature test for events doesn't have the scenario for restarting job from the existing event, but this is the common use case.
This PR add a test scenario for the event that has a parentEventId into `event.feature` in functional-tests.
https://github.com/screwdriver-cd/screwdriver/issues/1393
> fix(1393) add a scenario into event.feature for the case of parent event

- plugins/pipelines/create.js
- test/plugins/pipelines.test.js
The error status of parseUrl when creating a pipeline is only 500.
The following is an example. It is an error when the checkout URL is different from the logged-in SCM host.
It is inappropriate for this error to have the code 500 (Internal Server Error).
The parseUrl error when creating the pipeline is correct.
- ex1: If creating a pipeline for a repository on a host different from the login SCM, 400 (Bad Request) is appropriate.
- Error log after fixed:
- <img width="1295" alt="checkoutUrlNotSupported" src="https://user-images.githubusercontent.com/32473622/156678092-e0e03df2-7150-484a-9e76-d6b6b63051e3.png">
- ex2: If trying to create a pipeline for a private repository that the user don't have permissions on, a 404 (Not Found) is appropriate.
- Error log after fixed:
- <img …
> fix: Error code when parseUrl failed

- features/step_definitions/git-flow.js
- features/step_definitions/workflow.js
- features/support/github.js
- features/workflow.feature
Add missing tests to check the functionality of branch specific jobs.
- Add assertion to ensure job is not triggered if regular expression does not match in the following scenarios.
- Branch filtering (the master branch is committed)
- Branch filtering (the staging branch is committed)
- Added two scenarios to ensure that branch specific jobs work correctly in PR builds.
- Branch filtering (a pull request is opened to the master branch)
- Branch filtering (a pull request is opened to the staging branch)
- Implement processes to check the added assertions.
- Add `When /^a pull request is opened to "(.*)" branch$/`.
- Add `Then /^the "(.*)" PR job is not triggered$/`.
- Modified `createPullRequest` function to allow specifying a target other than the master branch.
- Modify `After tags` to …
> feat: Add functional tests for branch specific job

- plugins/builds/index.js
- test/plugins/pipelines.test.js
If the Remote Join feature is used in an unsupported method, as shown in the following image, an error will occur.
`Error Message`:
```
Error in removeJoinBuilds:main from pipeline:<pipelineId>-event:<event> Cannot read property 'id' of undefined
```
Subsequent builds are not created, so no real harm is done, but it will result in a 500 error and noise for monitoring.
Verify that the key exists correctly for the event you want to remove.
- [Remote Join](https://docs.screwdriver.cd/user-guide/configuration/workflow#remote-join)
> fix: Error fix in removeJoinBuilds

- features/restrict-pr.feature
- features/step_definitions/restrict-pr.js
Add functional test for restrict pr since it was missing.
I have also submitted a PR to the `funtional-restrict-pr` repository of screwdriver-cd-test to get this test working.
https://github.com/screwdriver-cd-test/functional-restrict-pr/pull/1
- PR from the same repository to pipelines with restrict pr set
- PR from the forked repository to the source repository with restrict pr set
> feat: Add restrict pr test [2] 

- plugins/pipelines/helper.js
- test/plugins/pipelines.test.js
Fix https://github.com/screwdriver-cd/screwdriver/issues/2665
- This PR enables to create pipeline even if two characters or less top dir was set as rootDir like `aa/bb/cc`.
- This PR enables to change pipeline's rootDir even if two characters or less top dir was set.
- `/`, `./`, `../` are omitted as [originally intended](https://github.com/screwdriver-cd/screwdriver/issues/2665#issuecomment-1041982316).
https://github.com/screwdriver-cd/screwdriver/issues/2665
> fix(2665): Enables to set sourceDirectory even if top dir was two characters or less

- package.json
- plugins/builds/index.js
Seeing some `SequelizeUniqueConstraintError` as a result of `triggerNextJobInSamePipeline` for join logic in Screwdriver build index. This might be because the `readOnly` DB has a slight delay, causing `getLatestBuilds` call to not get the CREATED join job.
This PR explicitly sets `readOnly` flag to `false` for `getLatestBuilds` in join logic.
Blocked by https://github.com/screwdriver-cd/models/pull/530
> fix: Use non-readOnly DB to get latest build for join [2]

- plugins/webhooks/helper.js
- test/plugins/webhooks.helper.test.js
Fix the following issue.
- https://github.com/screwdriver-cd/screwdriver/issues/2671
This PR make `eventConfig.meta` instance independent for each event configs.
Currently, when multiple events triggered from a same webhook, we set same `meta` instance to `eventConfig` for each events.
Thus if we set `meta.parameters` in `eventFactory.create(eventConfig1)`, then `eventConfig2.meta.parameters` is set too.
Call `createMeta` function for each events.
In PR event, [`createMeta`](https://github.com/screwdriver-cd/screwdriver/blob/4a049770e8f25013761dcb07dc6c453842442e5e/plugins/webhooks/helper.js#L727-L760) always returns empty object since webhook action is not "tag" and "release".
On the other hand, default value of `eventConfig.meta` is empty object …
> fix(2671): The build parameter should not be polluted by another pipeline

- plugins/pipelines/openPr.js
- test/plugins/pipelines.test.js
In [previous PR](https://github.com/screwdriver-cd/screwdriver/pull/2691), 500 error of `openPr` could not be solved, because of the wrong position of catch statement.
Github API 404 error occurs in [this method](https://github.com/screwdriver-cd/screwdriver/blob/b8e783c271b4b60e5f0c7ad1754f32eb4aebc4e4/plugins/pipelines/openPr.js#L69).
Fix position of the catch statement.
Here is the log message of my local api component after fixed codes.
`POST /pipelines/{id}/openPr`
```
"status":404,"url":"https://yyy.xxxx/api/v3/repos/repoName/sd-tmp-test-6/branches/aaaaaaaa"},"stack":"HttpError: Branch not found\n    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:86:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections …
```
> fix: return 404 in openPr branch not found

- package.json
- plugins/metrics.js
Version 4.1.2 of `promster/hapi` contains minimist which contains a vulnerability.
We update `promster/hapi` to the 6.1 series which is not vulnerable and supports node 12.
https://github.com/tdeekens/promster/blob/main/packages/hapi/CHANGELOG.md
https://github.com/tdeekens/promster/tree/%40promster/hapi%406.1.3
https://sca.analysiscenter.veracode.com/vulnerability-database/vulnerabilities/34731
> fix: Update promster hapi version

- plugins/jobs/listBuilds.js
- test/plugins/jobs.test.js
Users might want to query the API to get a list of builds and filter by build status.
This PR adds query option to filter by build status for `GET jobs/:jobid/builds`.
NA
> fix: List builds for job should be able to query by build status

- lib/server.js
- plugins/builds/artifacts/unzip.js
- test/plugins/builds.test.js
The object structure of unzipArtifactsEnabled, which manages flags for the SD_ZIP_ARTIFACTS function on the API side, is stored in **server.app.feature**, while other flags are stored directly in **sever.app**. I have modified it because the object structure is different.
Changed structure from **server.app.feature.unzipArtifacts** to **server.app.unzipArtifacts**
None
> fix:Refactoring of the unzipArtifactsEnabled configuration part of api

- plugins/pipelines/create.js
- plugins/pipelines/remove.js
- plugins/pipelines/tokens/create.js
- plugins/pipelines/tokens/refresh.js
- plugins/pipelines/tokens/remove.js
- plugins/pipelines/update.js
- plugins/secrets/create.js
- plugins/secrets/remove.js
- plugins/secrets/update.js
There is no way to verify who performed the operations on the Options page.
Audit logs are outputted in such cases.
- Users Create/Delete pipeline
- Users Update checkout URL/Source Directory
- Users Create/Update/Delete Secrets
- Users Create/Refresh/Delete Pipeline token
Example output:
`{"level":"info","message":"[Audit] user foo:github:github.com creates the pipeline for github.com:12345:main.","timestamp":"2022-09-09T02:40:41.609Z"}`
[[Feature Request] Audit log of operations on the Options page #2700](https://github.com/screwdriver-cd/screwdriver/issues/2700)
> feat(2700): Add audit log of operations on the Options page

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
- plugins/lock.js
- test/plugins/lock.test.js
To support Redis Cluster integration
node-resque says it supports Redis Cluster since 7.1.0
https://github.com/actionhero/node-resque/releases/tag/v7.1.0
This PR updates node-resque to support Redis Cluster instead of single Redis.
For more information on this change, see also the PR description below.
https://github.com/screwdriver-cd/queue-service/pull/57
https://github.com/screwdriver-cd/screwdriver/issues/2667
> feat: [3] add redis cluster connection

- plugins/builds/update.js
- plugins/pipelines/latestBuild.js
Description for `id` says "Identifier of this Job", should say "Identifier of this Pipeline".
This PR uses the correct schema for the pipelineId.
NA
> fix: id schema for pipeline get latestBuild

- bin/server
- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
Different bookends can be executed on different build cluster.
This PR changes the config file structure to allows bookends to be switched for each build cluster.
And support the following PR change.
https://github.com/screwdriver-cd/build-bookend/pull/18
**NOTICE**
This PR has breaking changes. The message `BREAKING CHANGE: xxx` must be in the footer of the commit.
- Issues
- https://github.com/screwdriver-cd/screwdriver/issues/2763
> [3] feat(2763): enable to switch different bookends for each build cluster. BREAKING CHANGE: change config file structure

- package.json
- plugins/pipelines/README.md
- plugins/pipelines/list.js
- test/plugins/pipelines.test.js
Sometimes we might want to list specific pipelines by id.
This PR adds `ids[]` query param to GET /pipelines so users can list specific pipelines.
N/A
> feat: List pipelines by ID

- lib/server.js
When a user has not logged in yet, there is no scope.
Will get this error `{"statusCode":500,"error":"Internal Server Error","message":"Cannot read property 'includes' of undefined"}`.
This PR handles no scope case for audit logs.
Related to https://github.com/screwdriver-cd/screwdriver/pull/2784
> fix: Handle no scope case for audit logs

- plugins/commands/listTags.js
- plugins/commands/listVersions.js
- plugins/events/listBuilds.js
- plugins/jobs/listBuilds.js
- plugins/pipelines/listEvents.js
- plugins/pipelines/listJobs.js
- plugins/pipelines/listStages.js
- plugins/pipelines/metrics.js
- plugins/templates/listTags.js
- plugins/templates/listVersions.js
- plugins/templates/listVersionsWithMetric.js
Can be confusing for users to see `search` field in Swagger docs when it is not actually supported.
This PR removes `search` keyword from pagination schema when not in use.
NA
> fix: Remove search from pagination schema [skip ci]

- features/build-cache.feature
- features/sd-cmd.feature
- features/step_definitions/build-cache.js
- features/step_definitions/sd-cmd.js
- features/step_definitions/trigger.js
- features/support/sdapi.js
- features/trigger.feature
This PR adds minimal functional testing to maintain the quality of the following features. 
1. require-or
2. sd-cmd
3. build-cache
In this PR, add the feature file and code for each feature.
This test checks if the OR trigger is working.
Here are the repositories that actually work.
https://github.com/screwdriver-cd-test/functional-require-or
Testing cache functionality at the job, event, and pipeline levels.
Build log messages are used to determine the job level cache. 
Job-level scenarios are tested using build log messages. 
Here are the repositories that actually work.
https://github.com/screwdriver-cd-test/functional-build-cache
Add new Trusted command and validation functional tests.
The Trusted Command test is based on the [Trusted …
> feat: Add functional tests sd-cmd require-or build-cache

- features/build-cache.feature
Looks like build-cache feature test step definitions are missing and are failing the pipeline.
```
17:51:17 Warnings:
17:51:17 
17:51:17 1) Scenario: Success cache is correctly created and cache exists # features/build-cache.feature:9
17:51:17    ✔ Before # features/step_definitions/build-cache.js:10
17:51:17    ✔ Given an existing pipeline for build-cache # features/step_definitions/build-cache.js:23
17:51:17    ? When the pipeline starts "create-cache" job
17:51:17        Undefined. Implement with the following snippet:
17:51:17 
17:51:17          When('the pipeline starts {string} job', function (string) {
17:51:17            // Write code here that turns the phrase above into concrete actions
17:51:17            return 'pending';
17:51:17          });
17:51:17 
17:51:17    - And the …
```
> fix: Skip build-cache.feature tests

- features/sd-cmd.feature
- features/trigger.feature
Some functional tests are still failing. Skipping the recently added ones until we can revisit it.
```
19:35:35 Failures:
19:35:35 
19:35:35 1) Scenario: Validate a template (attempt 3) # features/sd-cmd.feature:47
19:35:35    ✔ Before # features/step_definitions/sd-cmd.js:9
19:35:35    ✔ Given an existing pipeline # features/step_definitions/git-flow.js:40
19:35:35    ✖ Then a pipeline "succeeds" to validate the command in "validate-valid" # features/step_definitions/sd-cmd.js:239
19:35:35        TypeError: this.startJob is not a function
19:35:35            at CustomWorld.step (/sd/workspace/src/github.com/screwdriver-cd/screwdriver/features/step_definitions/sd-cmd.js:245:21)
```
https://cd.screwdriver.cd/pipelines/1/builds/836923/steps/test
This PR adds `@ignore` to latest functional …
> fix: Skip failing functional tests

- plugins/pipelines/badge.js
Badge is not showing latest event with builds as expected. This is because events triggered by remote triggers or rerun have parentEventId.
This PR removes `parentEventId: null`, also specifies `sortBy` and `sort` for API calls, removes unnecessary badges `reverse()` call.
Related to https://github.com/screwdriver-cd/screwdriver/pull/2789
> fix: Remove parentEventId null for pipeline badges endpoint

- features/build-cache.feature
- features/sd-cmd.feature
- features/step_definitions/sd-cmd.js
- features/trigger.feature
The following PR will allow you to run skipped functional tests.
https://github.com/screwdriver-cd/screwdriver/pull/2799
https://github.com/screwdriver-cd/screwdriver/pull/2800
The cause was, in part, the omission of code necessary to execute the scenario.
I removed the @ignore pin while adding the necessary code
- https://github.com/screwdriver-cd/screwdriver/pull/2795
- https://github.com/screwdriver-cd/screwdriver/pull/2799
- https://github.com/screwdriver-cd/screwdriver/pull/2800
> fix: functionalt-test build-cache, sd-cmd, trigger

- screwdriver.yaml
Beta functional tests are running into GitHub API rate limiting issues.
```
20:13:51    ✖ After # features/step_definitions/workflow.js:468
20:13:51        Error: 403 Reason "API rate limit exceeded for user ID 20604138."
20:13:51            at throwError (/sd/workspace/src/github.com/screwdriver-cd/screwdriver/node_modules/screwdriver-request/index.js:14:17)
20:13:51            at /sd/workspace/src/github.com/screwdriver-cd/screwdriver/node_modules/screwdriver-request/index.js:56:28
20:13:51            at runMicrotasks (<anonymous>)
20:13:51            at processTicksAndRejections (internal/process/task_queues.js:97:5)
20:13:51    ✔ After # features/step_definitions/workflow.js:452
```
https://cd.screwdriver.cd/pipelines/1/builds/838655/steps/test
This PR swaps functional test user to …
> fix: Try different username for functional tests

- screwdriver.yaml
Fn tests are failing due to Github rate limiting
Added new secret GIT_TOKEN_BETA for usage in beta fn tests
> fix: use new token for user sd-buildbot-functional for beta testing

- bin/server
new `config` version prohibits modification of config objects
use deepClone copy for config object that needs to be modified
> fix: use hoek.clone for mutable config

- config/custom-environment-variables.yaml
- config/default.yaml
- lib/server.js
- plugins/auth/index.js
- plugins/auth/login.js
- plugins/auth/token.js
- plugins/builds/token.js
- plugins/pipelines/caches/request.js
- test/plugins/auth.test.js
- test/plugins/builds.test.js
Username (/login) in SCM (Ex: Github) is mutable. In screwdriver, admin privileges are configured and determined based on SCM username of the logged in user.
If a user is configured as admin in Screwdriver and the user changes the username in SCM, the user will lose admin privileges.
If a new account is created in the SCM with the old username, the new user will acquire admin privileges.
This PR deliver below changes
- Configure and grant admin privileges based on both SCM user ID and name
- Configure and authenticate allowed users based on both SCM user ID and name
**Old config (Now deprecated)**
```
whitelist: []
admins: []
```
**New config**
```
allowList: []
sdAdmins: []
```
**P.S.**
To continue to use old approach, you need set `authCheckById` to `false` in the config.
Support for …
> feat(2853): Configure and perform auth checks (admins, whitelist) based on both SCM user ID and name

- plugins/templates/README.md
- plugins/templates/index.js
- plugins/templates/removeVersion.js
- test/plugins/templates.test.js
The existing API to remove a template, removes all the versions of the specified template and their associated tags.
There could be an use case where template owner publish a new version and later realized that there are some issues with it and prevent any jobs from using it.
To support this, we need an API to just delete a specific version of the template and its associated tags.
Add a new API to delete the specified version of the template
`DELETE /templates/{name}/versions/{version}`
Example:
`DELETE /templates/nodejs%2Flib/versions/2.0.12` removes version `2.0.12` of template `lib` under the namespace `nodejs`.
**Note**
If the deleted version was the last published, the API would set the `latest` attribute of the previous version to `true`. …
> feat(2862): Add a new API to delete a specific version of a template

- package.json
- plugins/templates/listVersionsWithMetric.js
- test/plugins/templates.test.js
The API to fetch all the versions of a template along with their usage metrics, returns all time usage by builds for each version.
We need ability to compute build usage metric for each version within a specified date/time interval
Enhance the API to support an optional date/time filter while computing usage by builds for each version.
Related PR: https://github.com/screwdriver-cd/models/pull/575
**TODO:**
Need to update `screwdriver-models` version in `package.json` after PR https://github.com/screwdriver-cd/models/pull/575 is merged/published.
https://github.com/screwdriver-cd/screwdriver/issues/2862
> feat(2862): Template metrics - Support date/time filter while fetching build count

- plugins/builds/artifacts/get.js
Per user request, the artifacts currently only allow
```
https://screwdriver.cd/pipelines/1053865/builds/51147439/artifacts/storybook-static/index.html 
```
and does not allow, 
```
https://api.screwdriver.ouroath.com/v4/builds/51147439/artifacts/storybook-static/iframe.html?type=preview&viewMode=story&id=* 
```
```
query: joi.object({
type: typeSchema
}).options({ allowUnknown: true })
```
will check and validate existing query, while allow unknow parameters 
Sample from https://joi.dev/tester/:  
> fix: artifacts query to add allowUnknown

- plugins/auth/index.js
- plugins/banners/create.js
- plugins/banners/index.js
- plugins/banners/remove.js
- plugins/banners/update.js
- plugins/buildClusters/create.js
- plugins/buildClusters/remove.js
- plugins/buildClusters/update.js
- plugins/builds/artifacts/unzip.js
- plugins/builds/update.js
- plugins/events/stopBuilds.js
- plugins/pipelines/index.js
- plugins/pipelines/list.js
- plugins/pipelines/remove.js
- test/plugins/auth.test.js
- test/plugins/buildClusters.test.js
The new sd admins format was introduced by this PR.
https://github.com/screwdriver-cd/screwdriver/pull/2854
But it cannot authenticate API token has admin permission.
Fix to authenticate correctly even when using API tokens.
Please review the following PRs first.
- https://github.com/screwdriver-cd/data-schema/pull/518
- https://github.com/screwdriver-cd/scm-github/pull/216
Issue
- https://github.com/screwdriver-cd/screwdriver/issues/2892
> [3] fix(2892): API tokens are correctly authenticated with new sd admins format

- plugins/builds/index.js
- test/plugins/builds.test.js
In remote join case, an unintentional build was being executed twice.
When the two builds triggering Remote Join are completed almost simultaneously, `PUT /v4/builds/{id}` is processed at the same time.
The process in `PUT /v4/builds/{id}` determines whether the next build is triggered after the build status is updated, so if the process in `PUT /v4/builds/{id}` is performed at about the same time, the next build will be triggered at the time the previous build is processed. The next build will be triggered at the time of the earlier build, and the later build will be judged to be a Restart case because the next build has already been triggered. The later build is judged to be a Restart case, another Event is created and an unintentional build is executed.
In the case of Restart, the …
> fix: Fix Remote join restart case

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
The error status of parseUrl when `POST /webhook` is only 500.
The parseUrl even throws error when the webhook is correct.
ex1: If PR created from branch with long name (more than 128), parseUrl throws `ValidationError` and return 500 response.
ex2: If PR created from private repository, parseUrl throws 404 error. But 500 response returned.
> fix: webhook returns 4xx error code when parseUrl failed

- features/step_definitions/restrict-pr.js
- features/step_definitions/workflow.js
The PR used for the test will be closed after the test is completed.
However, if it fails at that time, the PR will remain unless it is manually closed.
Fix PR test to avoid them remaining.
https://github.com/screwdriver-cd-test/functional-restrict-pr/pulls
> fix: Fixed PR delete fails and PR remains unless manually closed

- plugins/builds/index.js
- test/plugins/builds.test.js
Reverts screwdriver-cd/screwdriver#2908
@yakanechi @itleigns We are noticing something weird, multiple builds are now being created in a join scenario with OR condition and they extra builds end up changing to Collapsed builds.
This event https://cd.screwdriver.cd/pipelines/10293/events/765417 has a COLLAPSED status. Because the join job `join` in the OR condition is getting created multiple times in same event.
> Revert "fix: Fix job triggers not working properly depending on conditions"

- plugins/builds/index.js
- test/plugins/builds.test.js
Reverts screwdriver-cd/screwdriver#2914
So the  revert was not needed, since the original change never made it to prod. and the duplicate collapsed builds is not caused by that.
> Revert "Revert "fix: Fix job triggers not working properly depending on conditions""

- plugins/templates/createTag.js
- test/plugins/templates.test.js
Schema changes made in PRs https://github.com/screwdriver-cd/data-schema/pull/521 and https://github.com/screwdriver-cd/data-schema/pull/528 added a new column `templateType` to `templateTags` table.
This new column is now included in the unique constraint along with `name`, `namespace` and `tag`.
This change has broken the API (`/templates/{templateName}/tags/{tagName}`) to add/update tags to a Job template.
[Factory implementation](https://github.com/screwdriver-cd/models/blob/master/lib/baseFactory.js#L76) includes all the fields that part of unique constraint as filter (`WHERE` clause) which resulted in below error
```
230823/151514.910, (1692803702779:C02ZM198LVDV:9912:llnvkqft:10188) [request,server,error] data: Error: WHERE parameter "templateType" has invalid "undefined" value
at …
```
> feat(2135): Set templateType filter while getting template tag from DB

- plugins/builds/index.js
Pipeline workflow graph and stage workflow graph were getting merged to generate unified workflow graph which was used by the API while processing an event.
Workflow parser has been modified to eliminate stage workflows and always generate unified workflow graph which include node/edges for all the jobs irrespective whether the job belongs to a stage or not.
https://github.com/screwdriver-cd/workflow-parser/pull/4
Update API to use unified workflow graph.
https://github.com/screwdriver-cd/screwdriver/issues/2767
> feat(2767): Remove 'workflowGraph' from stageBuilds

- plugins/builds/index.js
- test/plugins/builds.test.js
1. In the following Remote Join workflow, when the build of `a2` and the build of `a3` are finished almost simultaneously, the build of `a4` may be executed twice.
2. If there are jobs waiting for the same job with Remote Join and Remote Or triggers, both of them (`b4` and `b5`) will be executed twice, as follows.
1. In some cases, when jobs waiting for Remote Join finish almost simultaneously, the parentBuildId is not set correctly for the triggered build and [it becomes the target of Restart](https://github.com/screwdriver-cd/screwdriver/blob/cc915df162b3aa8117ad8f2294ced64c7f75513d/plugins/builds/index.js#L943-L953), resulting in double execution.
So, when a build is created by a remote trigger, modify parentBuildId to be set to all builds of the job that condition the Join.
2. Add to …
> fix: Remote Join double build

- plugins/builds/index.js
This is PR to follow up on https://github.com/screwdriver-cd/screwdriver/pull/2937.
`nextBuild.parentBuildId` could be int instead of Array, which would result in a `not iterable error`.
```
Error in triggerJobsInExternalPipeline:xxxxx from pipeline:xxxxx  (nextBuild.parentBuildId || []) is not iterable","stack":"TypeError: (nextBuild.parentBuildId || []) is not iterable\n    at updateParentBuilds (/usr/src/app/node_modules/screwdriver-api/plugins/builds/index.js:457:89)\n
```
Fix `nextBuild.parentBuildId` to be flattened after concatenating in Array so that it can handle both int and Array.
> fix: Support for cases when parentBuildId is not Array

- plugins/pipelines/update.js
- test/plugins/pipelines.test.js
Follow up of data-schema changes https://github.com/screwdriver-cd/data-schema/pull/531 
1) Add `badges: {}` to pipeline `GET` API
2) Add update `badges: {}` to pipeline `PUT` API 
This PR will make API to get and update badges information for given pipeline 
> feat: add badges to pipeline update PUT api

- package.json
- plugins/coverage/token.js
- plugins/pipelines/update.js
- test/plugins/coverage.test.js
1. Sonar Coverage will populate the sonar `projectUrl` only when the scope is pipeline,
2. On the backend, we will only set the pipeline sonar badge if `pipeline` itself exists and `projectUrl` is available
Only populate if `pipelineSonarBadge.defaultName` and `pipelineSonarBadge.defaultUri` were not generated, under assumption that `defaultName` and `defaultUri` does not change once populated. 
Users can override the `pipelineSonarBadge.name` and `pipelineSonarBadge.uri` however, just not the defaults
https://github.com/screwdriver-cd/data-schema/pull/540
https://github.com/screwdriver-cd/coverage-sonar/pull/73
> fix: integrate auto populate sonar projectUrl in pipeline badge [3]

- config/default.yaml
Coverage bookend is missing in OSSD builds
> fix: enable coverage bookend

- plugins/pipelines/update.js
Updating badges with PUT call returns new data, yet in GET call still has the stale data. So I went to DB to check, and database does not have the latest data in PUT call.
Found a reference when this happened before
https://github.com/screwdriver-cd/models/blob/f2ce8b730a17696ca2a361f1af1bc589dec99185/lib/pipeline.js#L1801
Rational is:
Because the original code was doing data replacement in-replace, thus not making code changes `dirty`, see
https://github.com/screwdriver-cd/models/blob/f2ce8b730a17696ca2a361f1af1bc589dec99185/lib/base.js#L63
This PR will fix that.
> fix: badges not storing new values in DB

- plugins/pipelines/README.md
- plugins/pipelines/index.js
- plugins/pipelines/templates/createTag.js
- plugins/pipelines/templates/get.js
- plugins/pipelines/templates/getTemplateById.js
- plugins/pipelines/templates/getVersion.js
- plugins/pipelines/templates/listTags.js
- test/plugins/data/pipelineTemplateTags.json
- test/plugins/data/pipelineTemplateVersion.json
- test/plugins/pipelines.templates.test.js
Add operations get, list for `pipelineTemplate` meta , `pipelineTemplateVersions` and `templateTags`
Below changes have been made
- added get,getVersion.getTemplateById API in `/pipeline/templates`
- added listTags,createTags API in `/pipeline/templates`
https://github.com/screwdriver-cd/models/pull/599
> feat: add get,getVersion,listTags,createTag fns

- plugins/builds/index.js
- test/plugins/builds.test.js
The build of `target` is not triggered in the following cases.
1. `a` fails.
2. `b` succeeds.
3. restarted `a` succeeds.
4. `c` succeeds.
The build created by restart in No. 3 is the latest build and the `target` build is not triggered in No. 4.
If `nextBuild` is not present, check for events that should be triggered within the same event.
Visually, the `target` build should be executed on the child event created by restart.
However, as the issue https://github.com/screwdriver-cd/screwdriver/issues/2957 is created, it is not easy to modify them that way.
As a matter of urgency, fix the builds that should be triggered so that they are triggered.
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its …
> fix: Fix join build not triggering on restart during build execution

- package.json
- test/plugins/data/stages.json
https://github.com/screwdriver-cd/data-schema/pull/547
Update mock data for stage tests to align to the latest schema
https://github.com/screwdriver-cd/screwdriver/issues/2767
> fix(2767): fix stages tests per latest schema

- Dockerfile
- Dockerfile.local
Current node image used for the docker build is node:18, while the latest node docker image is node:21
Update the node image with the latest version
Build has been failing recently with the connectivity issue to npm registry, hoping the upgrade of node image might help resolving. 
https://cd.screwdriver.cd/pipelines/1/builds/919086/steps/build-push
> fix: use node:20 for docker build

- plugins/pipelines/templates/validate.js
Remove auth scopes from validation API
Remove auth scopes from `/pipeline/template/validate` API
> remove auth scopes from validator

- plugins/builds/index.js
- test/plugins/builds.test.js
- test/plugins/data/validator.output.json
If a Remote Triggered downstream pipeline was Remote Triggered twice, only one job would be triggered.
Reference: https://github.com/screwdriver-cd/screwdriver/issues/2980.
Due to this issue, https://github.com/screwdriver-cd/screwdriver/pull/2964 was reverted.
I would like to change the https://github.com/screwdriver-cd/screwdriver/pull/2964 again with this issue resolved.
As mentioned in https://github.com/screwdriver-cd/screwdriver/issues/2980#issuecomment-1895114395, the problem is that the loop would return, so we will fix it so that it triggers all necessary builds without returning.
**The unit test fails until https://github.com/screwdriver-cd/workflow-parser/pull/49 is published.**
I confirm that this contribution is made under a BSD license and that I have the authority necessary …
> fix(2980): remote trigger does not work when the job includes other normal join jobs [2]

- plugins/pipelines/templates/create.js
- test/plugins/pipelines.templates.test.js
Create pipeline template endpoint should return namespace and name
Added a change to return the `templateMeta` information
> feat: return namespace, name in create pipelineTemplate

- plugins/pipelines/templates/getVersion.js
- test/plugins/pipelines.templates.test.js
Fix GET pipeline template version with version or tag
Fix GET pipeline template version with version or tag
> feat: fix getVersion for pipelineTemplates

- plugins/pipelines/templates/listVersions.js
- plugins/pipelines/templates/remove.js
- test/plugins/pipelines.templates.test.js
Move name, and namespace to config object for `pipelineTemplates`
Move name, and namespace to config for `pipelineTemplates`
> feat: move name, namespace to config for pipelineTemplates

- plugins/auth/token.js
- plugins/builds/steps/list.js
- plugins/pipelines/listEvents.js
- plugins/templates/listTags.js
Issues are where parameters cannot be specified or queries that cannot be used can be specified on the Swagger UI.
Details are on https://github.com/screwdriver-cd/screwdriver/issues/2368
PR [1] is https://github.com/screwdriver-cd/data-schema/pull/550
Fix the above problem. Details are as follows.
- getCount is only used in templates/ and commands/ endpoints, so it is disabled.
- Parameters can be specified.
However, due to the #3036 problem, /auth/token only accepts BuildId(integer) on the UI and not UserName(string).
Also, JWT cannot be obtained using api_token queries if buildId in auth/token is set to required, so it is set to optional.
The modified endpoints are as follows.
- [GET /v4/auth/token](https://api.screwdriver.cd/v4/documentation#/v4/getV4AuthTokenBuildid)
- [GET …
> fix(2368): Fix description in swagger [2]

- package.json
- plugins/swagger.js
Cullently Swagger plugin version is v2, but this version does not support some feature.
https://github.com/screwdriver-cd/screwdriver/issues/3036
Bump up `hapi/swagger` module.
After this PR, we will use OpenAPI v3 but its setting file is automatically generated by `hapi/swagger`.
https://github.com/screwdriver-cd/screwdriver/issues/3036
> feat(3036): update hapi-swagger package

- test/plugins/trigger.test.helper.js
- test/plugins/trigger.test.js
Helpers for trigger tests were added by https://github.com/screwdriver-cd/screwdriver/pull/3029 .
But we cannot use code completion on these models and factories. 
Add some interface classes for mock objects and add JSDocs to use code completion. (e.g. VSCode IntelliSense)
https://github.com/screwdriver-cd/screwdriver/issues/3012
> fix(3012): refactor trigger test helper

- package.json
- plugins/pipelines/README.md
- plugins/pipelines/index.js
- plugins/pipelines/templates/updateTrusted.js
- test/plugins/data/pipeline-template-untrusted.json
- test/plugins/pipelines.templates.test.js
add endpoint to mark pipeline template as trusted
add endpoint to mark pipeline template as trusted
https://github.com/screwdriver-cd/screwdriver/issues/3056
> feat(3056): add endpoint to mark pipeline template as trusted

- Dockerfile
API server cannot receive `SIGTERM`
See this issue for details:
https://github.com/screwdriver-cd/screwdriver/issues/3062
- Fix Dockerfile as belows:
- Add tini process
- Run the service by `node ./bin/server` directly, not via `npm start`
Issue: https://github.com/screwdriver-cd/screwdriver/issues/3062
Docker and Node.js Best Practices: 
https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
> fix(3062): fix Dockerfile not to use npm start

- plugins/pipelines/templates/removeVersion.js
- test/plugins/pipelines.templates.test.js
API `/pipeline/templates/{templateNamespace}/{templateName}/versions/{version}` invokes `getWithMetadata` method of `PipelineTemplateVersionFactory`. But, the method `getWithMetadata` returns a plain javascript object instead of an object that extends [BaseModel](https://github.com/screwdriver-cd/models/blob/master/lib/base.js).
This results in below error
```
{
"statusCode": 500,
"error": "Internal Server Error",
"message": "templateVersion.remove is not a function"
}
```
API should call `get` instead of `getWithMetadata`.
https://github.com/screwdriver-cd/screwdriver/issues/3072
> fix(3072): Unable to delete a specific version of a pipeline template

- plugins/pipelines/templates/removeVersion.js
- test/plugins/pipelines.templates.test.js
Reverts screwdriver-cd/screwdriver#3073
The core issue is fixed in the models that affects multiple APIs
https://github.com/screwdriver-cd/models/pull/620
Issue https://github.com/screwdriver-cd/screwdriver/issues/3072
> Revert "fix(3072): Unable to delete a specific version of a pipeline template"

- plugins/events/stopBuilds.js
- test/plugins/events.test.js
SD API returns 500 error when user logged in mismatch SCM host stops events.
```js
{
"statusCode": 500,
"error": "Internal Server Error",
"message": "Pipeline's scmHost xxx.com does not match with user's scmHost yyy.com"
}
```
But in this case, API should return 403 error (or 404 when private pipeline).
Add error handling same as https://github.com/screwdriver-cd/screwdriver/pull/2655
https://github.com/screwdriver-cd/screwdriver/pull/2655
> fix: return 403/404 error when stop events with mismatched scm host

- .github/workflows/issues.yaml
Run similarity analysis when issues are opened or labeled with `triage`. 
Perform cleanup of issues that have similarity and group issues accordingly based on the frequency of asks in order to learn the user pain points. 
The action used in the step was found in the [Github marketplace](https://github.com/marketplace/actions/issues-similarity-analysis). Some trial runs have been performed on the personal repo to ensure that the action is safe to run and produce the expected outcome. 
- [Sample workflow](https://github.com/VonnyJap/models/blob/master/.github/workflows/issues.yaml)
- [Sample events that have been run](https://github.com/VonnyJap/models/actions/workflows/issues.yaml)
- Sample issues that have been analyzed:
- https://github.com/VonnyJap/models/issues/10
- …
> feat: Create Workflow when Issues opened or labeled

- package.json
- plugins/auth/login.js
- test/plugins/auth.test.js
`scm-router` fn `isEnterpriseUser` needs `scmContext` param
This PR passes `scmContext` as param to fn
https://github.com/screwdriver-cd/scm-router/pull/35
> fix: scm-router fn needs scmContext

- plugins/pipelines/README.md
- plugins/pipelines/listEvents.js
- test/plugins/pipelines.test.js
It would be nice for users to be able to filter events by commit SHA.
This PR adds query param to filter by sha for pipeline events.
N/A
> fix: Add sha filter for pipeline events

- Dockerfile
- Dockerfile.local
In [the previous PR](https://github.com/screwdriver-cd/screwdriver/pull/3063), we have fixed the Dockerfile to use `tini`  to handle sigterm appropriately for graceful shutdown. However it seems there are some issues for signal TRAP with `tini` as [this comment](https://github.com/screwdriver-cd/screwdriver/pull/3063#issuecomment-2025390989) mentioned.
It switches `tini` to `dumb-init` for the init process in the container as same as `launcher` does.
[issue](https://github.com/screwdriver-cd/screwdriver/issues/3062)
[original comment](https://github.com/screwdriver-cd/screwdriver/pull/3063#issuecomment-2025390989)
[dumb-init official](https://github.com/Yelp/dumb-init)
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this …
> fix(3062): use dumb-init instead of tini

- plugins/pipelines/listEvents.js
Would be nice to be able to pass in shorthand sha to the pipeline event filter. The original limits the sha length to 40 (https://github.com/screwdriver-cd/data-schema/blob/master/models/event.js#L42).
This PR relaxes the query param validation schema for pipeline events sha filter.
Related to https://github.com/screwdriver-cd/screwdriver/pull/3088
> fix: Relax query param for pipeline event sha filter

- plugins/events/create.js
Currently, someone in pipeline admins is displayed in "Started by" when user executes events with pipeline access token.
Hence the user cannot know whether the event was executed by the user or by the token.
Display "Started by: Pipeline Access Token" when the event executed with pipeline access token.
https://github.com/screwdriver-cd/screwdriver/issues/3087
> feat(3087): Show that events was executed using Pipeline Access Token

- .github/workflows/issues.yaml
The workflow to find similar issues has a low threshold causing unrelated issues to be identified as similar. 
Increase the threshold to improve accuracy of finding similar issues so it is more meaningful. 
> fix: Increase the issue similarity threshold [skip ci]

- features/pipeline-templates.feature
- features/step_definitions/pipeline-template.js
- test/plugins/auth.test.js
Shared config is flattened into jobs in pipeline template. 
Remove shared config from pipeline template functional test. 
https://github.com/screwdriver-cd/screwdriver/issues/3068
> feat(3068): remove shared from pipeline template functional test

- features/step_definitions/stage.js
Stage functional test is failing with the error:
```
19:46:51    ? Then the "stage@setup_fail" stageBuild status is "FAILURE"
19:46:51        Undefined. Implement with the following snippet:
19:46:51 
19:46:51          Then('the {string} stageBuild status is {string}', function (string, string2) {
19:46:51            // Write code here that turns the phrase above into concrete actions
19:46:51            return 'pending';
19:46:51          });
```
This PR relaxes regex for stage functional test.
Related to https://github.com/screwdriver-cd/screwdriver/pull/3061, https://github.com/screwdriver-cd/screwdriver/issues/3042
> fix(3042): Stage functional test regex

- package.json
- test/plugins/webhooks.helper.test.js
Removing lodash because deep clone can be natively done in JS
Implement deep clone natively instead of using lodash 
https://github.com/screwdriver-cd/screwdriver/pull/3095#discussion_r1589653340
> fix: no lodash for cloning

- features/step_definitions/subscribe.js
- features/support/github.js
- test/plugins/webhooks.helper.test.js
When octokit is set as const at the beginning of module, like [this](https://github.com/screwdriver-cd/screwdriver/blob/a20a5fb2bd06bfc2d085121fe38f840c3ceee913/features/support/github.js#L5-L11), it is possible that the env variables involved are not initialized. Hence causing an unauthorized access to Github API. 
Octokit should be inited on the function that needs it. 
> fix: init octokit for all functions in github api

- features/stages.feature
- features/step_definitions/workflow.js
- plugins/builds/update.js
Functional tests on the stages feature have been failing due to a timeout error.
Fix the functional tests on the stages feature by making the following change:
- Remove the check of [intermediary status in the teardownFail branch](https://github.com/screwdriver-cd/screwdriver/blob/master/features/stages.feature#L123) because the stages status propagates too quickly, making it unrealistic to capture.
- Add a sleep before checking for a teardown build because I have noticed locally that checking it too quickly can cause a timeout error.
> fix: functional tests on stages timeout error

- plugins/events/create.js
- test/plugins/events.test.js
Currently, when create event, users can impersonate the user who created the event.
So API restricts overwriting username to restrict impersonate the user who created the event.
If the event is created by not sd:scheduler user, the username of the event's creator is set by the username of the token that called the API.
#3123 
> fix(3123): Restrict overwriting username on create Event

- plugins/builds/index.js
- test/plugins/trigger.test.helper.js
- test/plugins/trigger.test.js
Followup this PR
https://github.com/screwdriver-cd/screwdriver/pull/3122
Stage teardown jobs should be triggered when stage builds are complete regardless of build status.
But after merged PR, stage teardown jobs aren't triggered when some builds are failed.
Stage teardown jobs are triggered.
https://github.com/screwdriver-cd/screwdriver/pull/3122
> fix(3012): trigger stage teardown job when some stage builds failed

- plugins/builds/index.js
- plugins/builds/triggers/remoteJoin.js
- test/plugins/trigger.test.js
Followup this PR
https://github.com/screwdriver-cd/screwdriver/pull/3122
Remote Join job should be triggered on the new event on upstream when restart from an event downstream of the event in which Remote Join is successful.
However, the event and build are created but not triggered.
Fix the function call location so that the build can be fetched and triggered from the new event that was created.
In addition, add a test for this scenario. (In other words, make sure that it is triggered twice in total by start and restart)
> fix(3012): Trigger remote join job in restart when the last remote join job is successful

- plugins/builds/triggers/helpers.js
- test/plugins/trigger.helper.test.js
In a fix related to issue #3012, the triggering function has been carved out of the helper.
Add unit test for those functions that are exported.
- Add test for function in trigger's helper.
- Remove `joinParentBuilds` from the return value of `parseJobInfo` as it is not needed.
- In `getBuildsForGroupEvent`, if the item to be parsed in `JSON.parse` is not a string, an error will occur, so modify it to parse only if it is a string.
https://github.com/screwdriver-cd/screwdriver/pull/3122
> fix(3012): add tests for trigger helper

- plugins/pipelines/templates/validate.js
- test/plugins/pipelines.templates.test.js
The is displaying only the configurations stored in the database without extending the job template. It would be nice if it would merge template steps if the pipeline template is using a template.
This PR adds a new function for pipeline template validator to show users flattened job template steps.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3124
> feat(3124): Extend job template steps in pipeline template validation [3]

- plugins/events/index.js
- plugins/webhooks/helper.js
- test/plugins/events.test.js
- test/plugins/webhooks.helper.test.js
Currently, SD API uses pipeline admin's token due to access GitHub when start builds.
[The first of `pipeline.admins` is used as pipeline admin](https://github.com/screwdriver-cd/models/blob/4d6d9e7dfa5425a9ddd2e73625de623d370c1377/lib/pipeline.js#L1181), but admins list is not sorted anywhere.
As a result, the first admin's token is always used even if other admin started builds.
There is no problem to check user's permission, but the first admins's GitHub API rate limit is consumed excessively.
Put current user at the head of pipeline admins when update pipeline admins.
This sort update is applied when start builds, thus other admin's token will not be used.
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on …
> fix: The first admin's GitHub rate limit is consumed excessively

- plugins/builds/index.js
- plugins/builds/triggers/and.js
- test/plugins/trigger.test.js
This PR fixes some cases of the [issue](https://github.com/screwdriver-cd/screwdriver/issues/2957).
It corrects the join build to be properly restarted and executed on the event in the following two test cases that have been added:
- In the case where `[a, b]` are in the requires, `a` fails but succeeds after `a` restart, and then `b` succeeds.
- In the case where `[a, b, c]` are in the requires, `a` fails but succeeds after `a` restart, and then `b` and `c` succeed.
However, the following test case, which is also exemplified in the original issue, still requires fixing:
- In the case where `[a, b, c]` are in the requires, `a` fails, `a` is restarted, then `b` succeeds, `a` succeeds, and finally `c` succeeds.
Find trigger build in child event after current event has no trigger build. …
> fix(2957): Fix event where a restarted join build is run

- package.json
- test/plugins/pipelines.templates.test.js
Latest config-parser supports showing workflowGraph in pipeline template validation.
This PR updates test to reflect new changes.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3115
> fix(3115): Pull in latest config-parser with workflowGraph support for pipeline template validation

- plugins/builds/triggers/helpers.js
- test/plugins/builds.test.js
Now, it checks original job state to decide that the PR job is executable.
But the PR job is not able to be triggered if original job was deleted still it had been disabled.
Fix to check if the original job was deleted in the same way as `eventFactory`.
https://github.com/screwdriver-cd/models/blob/8291226e30963ad0a53acc222693c86e976437e9/lib/eventFactory.js#L154-L163
> fix: check original job is not archived

- plugins/webhooks/helper.js
- test/plugins/webhooks.helper.test.js
We will be able to get repository data from `pipeline.scmRepo` by the following PR.
https://github.com/screwdriver-cd/scm-github/pull/231
Pass `scmRepo` to skip GitHub access and get repository data from it.
(This PR's target is only webhook process.)
Prior PRs
- https://github.com/screwdriver-cd/data-schema/pull/570
- https://github.com/screwdriver-cd/scm-github/pull/231
Issue
- https://github.com/screwdriver-cd/screwdriver/issues/3146
> feat(3146): Get repository data from scmRepo without GitHub access [4]

- plugins/events/create.js
- test/plugins/events.test.js
This is a continuation of the following PR.
https://github.com/screwdriver-cd/screwdriver/pull/3147
Allow to pass scmRepo argument into methods that using lookupScmUri method inside even at the start of the event.
Thus reducing the number of API accesses to GitHub.
https://github.com/screwdriver-cd/screwdriver/issues/3146
> feat(3146): Get repository data from scmRepo without GitHub access from UI start

- package.json
- plugins/events/create.js
- plugins/helper.js
- test/plugins/events.test.js
Not allow users to start an event form a stage teardown
throw an error if the user tries to start an event from a stage teardown
[https://github.com/screwdriver-cd/screwdriver/issues/3143](url)
> feat(3143): Prevent event creation when started from a stage teardown

- plugins/commands/README.md
- plugins/commands/index.js
- plugins/commands/removeVersion.js
- test/plugins/commands.test.js
While there is API endpoints to [delete a command](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/commands/remove.js) and [a tag from a command](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/commands/removeTag.js), there is no endpoint to allow the deletion of specific version of a command. And it will be useful to allow specific command and its associated tag to be deleted because bad commits happen sometimes. 
This PR implements a new endpoint to allow specific version of a command to be deleted. 
https://github.com/screwdriver-cd/screwdriver/issues/3156
> feat(3156): New endpoint to delete specific version of a command

- plugins/builds/index.js
- plugins/builds/triggers/helpers.js
- test/plugins/builds.test.js
The job after the stage setup was being executed regardless of the startFrom being from the middle of stage or not
The startFrom job will be triggered next if the current job is stage setup and the startFrom is a non setup job in that stage
https://github.com/screwdriver-cd/screwdriver/issues/3143
> Skip execution of jobs between stage setup and event startFrom

- plugins/pipelines/README.md
- plugins/pipelines/listEvents.js
- test/plugins/pipelines.test.js
We need to be able to sort in a different order than descending.
This PR adds sort and sortBy to pipeline list events endpoint. Also updates joi schema for event ID query param for Swagger.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3163
> fix(3163): Add sort and sortby query params for pipeline list events

- features/collections.feature
- features/step_definitions/collection.js
- features/step_definitions/git-flow.js
- features/step_definitions/sd-cmd.js
- features/step_definitions/sd-setup-scm.js
- features/step_definitions/templates.js
- features/step_definitions/user-teardown-step.js
- features/step_definitions/workflow.js
- features/support/sdapi.js
- features/support/world.js
The functional tests may fail if the workload is high and processing is slow or if it is run continuously.
Prevent functional tests fail for the above reasons.
- Rename the collections for each scenario, as adding to the pipeline the same collection at the same time may cause one or the other to fail to be added.
- Ensures that the build executed at the end of the scenario is stopped.
- If a build is still running when a timeout or other failure occurs, it will fail if functional tests are restarted immediately.
- Replace waitForBuildStatus with waitForBuilds
- waitForBuildStatus waits forever until the desired status is reached, so if the status transitions before waitForBuildStatus is executed, the loop continues.
- Fixed waitForBuild to wait for build completion by assuming CREATED and …
> fix: Stabilize functional test

- plugins/builds/triggers/and.js
- plugins/builds/triggers/helpers.js
- plugins/builds/triggers/remoteJoin.js
- test/plugins/builds.test.js
- test/plugins/data/trigger/a_sd@2:a_sd@3:a-upstream.yaml
- test/plugins/data/trigger/b_sd@2:a_sd@3:a-upstream.yaml
- test/plugins/trigger.helper.test.js
- test/plugins/trigger.test.js
fix #2981
When an upstream job of the remote-join job is restarted, remote-join job immediately runs reusing build status from previous event.
When a remote join job's upstream jobs are restarted, the remote join job will use the post-restart build status as the trigger for jobs that may run from the restart job.
Enumerate jobs started after the restart job, referring to [the subgraph filter in the UI](https://github.com/screwdriver-cd/ui/blob/8a764ea1a6db38e29e85588a8cc7fcc56d770869/app/utils/graph-tools.js#L454), and do not use the recent build status of the group event.
- About the test
We found another bug related to remote join while working on this. (#3177)
Therefore, a test has been added to the “Tests for behavior not ideal” section
Also, with this fix, the test that was …
> fix(2981): remote join wait on downsream jobs during restart

- package.json
- screwdriver.yaml
- Pipeline template functional tests have been failing consistently
- The new headless Github user needs the correct API and Github token 
- Correct the API and Github token for `sd-buildbot-functional-beta-X1`
- Disable pipeline template functional tests to ensure that the new user is working as intended
https://github.com/screwdriver-cd/screwdriver/issues/3182
> fix: set the correct secrets and disable pipeline-template

- package.json
- screwdriver.yaml
As of now, the beta additional tests are run in different job and the pipeline template functional tests failing on the prod instance. 
- run beta tests in different steps instead of different jobs
- turned off pipeline template functional tests in the meantime
https://github.com/screwdriver-cd/screwdriver/issues/3182
> fix: run tests into different steps

- screwdriver.yaml
Wrong test username 
Fix with the right github username 
https://github.com/screwdriver-cd/screwdriver/issues/3182
> fix: change the name of the sd functional x1

- package.json
Move pipeline template workflowGraph out of config into a new field
Upgrade to latest command validator
https://github.com/screwdriver-cd/screwdriver/issues/3171
> fix(3171): upgrade to latest command validator

- features/stages.feature
- features/step_definitions/stage.js
- features/support/sdapi.js
- features/support/world.js
Stage trigger has supported join case. https://github.com/screwdriver-cd/screwdriver/issues/3066
But this tests are not implemented in stages functest.
- Add `requires: [ stage@foo, stage@bar ]` test case in the stages functest.
- Replace `waitForStageBuildStatus` as https://github.com/screwdriver-cd/screwdriver/pull/3172
- `waitForStageBuildStatus` waits forever until the desired status is reached
The test repository will be fixed by https://github.com/screwdriver-cd-test/functional-stage/pull/1 .
> feat: add stage join trigger case and stabilize stages test [2]

- plugins/builds/update.js
- test/plugins/builds.test.js
Whenever a `build` is updated, its `meta` is merged with `event` `meta`. But, this merge is shallow (one level). Due to this nested `meta` set by previous builds of this `event` could be lost when the latest `build` `meta` is merged. This is more common when the builds are triggered and executed in parallel.
`build` `meta` should be deep merged (recursively) into `event` `meta`.
https://github.com/screwdriver-cd/screwdriver/issues/3203
> fix(3203): Deep merge build meta into event meta

- plugins/builds/update.js
Need some minor adjustment to the changes made in https://github.com/screwdriver-cd/screwdriver/pull/3204
Create a new event meta object when deep merging build meta into event meta
https://github.com/screwdriver-cd/screwdriver/issues/3203
> fix(3203): Create new event meta when deep merging build meta into event meta

- config/default.yaml
- plugins/builds/triggers/helpers.js
Observed this scenario of workflowgraph
```
const workflowGraph = {
nodes: [
{
name: '~pr'
},
{
name: '~commit'
},
{
name: '~sd@123:deploy-db',
id: 573500
},
{
name: 'sd@123:deploy-api',
id: 573501
}
],
edges: [
{
src: '~pr',
dest: 'pr'
},
{
src: '~commit',
dest: 'component'
},
{
src: '~sd@123:deploy-db',
dest: 'certify-db'
},
{
src: 'certify-db',
dest: 'sd@123:deploy-api'
},
{
src: '~sd@123:deploy-api',
dest: 'sd@456:mysql'
}
]
};
```
When edges have src entry that slightly differ from the nodes entry, in this case with `~` then the key won't be found in the object causing to be undefined and hence resulting in error. 
https://github.com/screwdriver-cd/screwdriver/pull/3178
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this …
> fix: need to init a value when key does not exist in an object

- plugins/builds/index.js
- plugins/builds/triggers/and.js
- plugins/builds/triggers/helpers.js
- plugins/builds/triggers/joinBase.js
- plugins/builds/triggers/or.js
- plugins/builds/triggers/orBase.js
- plugins/builds/triggers/remoteJoin.js
- plugins/builds/triggers/remoteTrigger.js
- test/plugins/builds.test.js
- test/plugins/data/trigger/virtual-jobs-with-freeze-windows.yaml
- test/plugins/trigger.helper.test.js
- test/plugins/trigger.test.helper.js
- test/plugins/trigger.test.js
Changes were made in this PR https://github.com/screwdriver-cd/screwdriver/pull/3131 to skip execution of job with the annotation `screwdriver.cd/virtualJob: true`.
But this change did not take freeze windows in to the consideration. Due to this, the virtual jobs are skipped execution and marked as 'SUCCESS' with in the freeze window.
Do not skip the execution of virtual jobs with freeze windows. Instead add it to the execution queue.
Let Queue Service skip the execution when the job is picked up from the queue outside the freeze windows.
https://github.com/screwdriver-cd/screwdriver/issues/3209
> fix(3209): Honor freeze windows for virtual jobs

- plugins/pipelines/README.md
- plugins/pipelines/listEvents.js
- test/plugins/pipelines.test.js
Sometimes we might want to filter by groupEventId for pipeline events.
This PR adds a filter to `GET /pipelines/{pipelineId}/events` to return only events with a specified `groupEventId`.
NA
> fix: Allow groupEventId filter for list pipeline events

- plugins/builds/README.md
- plugins/builds/artifacts/get.js
- test/plugins/builds.test.js
Should use `type=download` for directory download.
This PR checks for `type` and also saves files in zip relative to current directory.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1749
> fix(1749): Download dir endpoint

- package.json
- plugins/builds/triggers/helpers.js
- plugins/builds/triggers/orBase.js
- plugins/builds/update.js
- test/plugins/builds.test.js
- test/plugins/trigger.helper.test.js
- test/plugins/trigger.test.js
Execution of virtual jobs are skipped and the build status is being set to "SUCCESS".
In the UI, we need to convey the same in the build details page.
Set `statusMessage` and `statusMessageType` on the build when the execution is skipped for the virtual job.
https://github.com/screwdriver-cd/screwdriver/issues/3211
> feat(3211): Set build status message while skipping execution of virtual job

- plugins/builds/README.md
- plugins/builds/artifacts/get.js
- test/plugins/builds.test.js
Trailing slash cannot be passed because of this setting in the Hapi server: 
```
router: {
stripTrailingSlash: true
}
```
https://github.com/screwdriver-cd/screwdriver/blob/master/lib/server.js#L118
This PR uses query param `dir=true` to indicate directory download instead of trailing slash.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1749
> fix(1749): Use query param dir=true to indicate directory download

- plugins/builds/index.js
- plugins/builds/triggers/helpers.js
- test/plugins/builds.test.js
- test/plugins/data/trigger/a_b-downstream.yaml
- test/plugins/data/trigger/~sd@1:a-and-~sd@1:b-downstream.yaml
- test/plugins/data/trigger/~sd@1:a-and-~sd@1:b-upstream.yaml
- test/plugins/trigger.helper.test.js
- test/plugins/trigger.test.js
https://github.com/screwdriver-cd/screwdriver/issues/3230
Fix external events triggered by the same event to be combined into one event.
In addition, fix the behavior on restart as follows.
- External events created when restarted with an upstream event belong to the same groupEvent as the external event created by the event before the restart.
- A remote trigger from a downstream event to an upstream event belongs to the same groupEvent as the upstream event that created the restarted downstream event.
Start event(Upstream), Downstream event
Restart event(Upstream), Downstream event
Relatedly, A Issues has been resolved too.
https://github.com/screwdriver-cd/screwdriver/issues/3177
https://github.com/screwdriver-cd/screwdriver/issues/3230 …
> fix(3230): fix assigned remote trigger events

- config/custom-environment-variables.yaml
- config/default.yaml
- lib/server.js
- plugins/builds/artifacts/get.js
- test/lib/server.test.js
- test/plugins/builds.test.js
Would be nice if we could check for max file download size before downloading.
This PR adds config for `maxDownloadSize` for downloading artifact directories.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3227
> fix: Add maxDownloadSize for artifact directory download

- plugins/pipelines/README.md
- plugins/pipelines/listEvents.js
- test/plugins/pipelines.test.js
Would be nice if users could search events based on commit message, author, or creator.
This PR adds ability to search events based on the above fields.
Related to #2775 
> fix: Add ability to filter pipeline events for commit message, author, or creator

- plugins/builds/triggers/helpers.js
- plugins/builds/triggers/joinBase.js
- plugins/builds/triggers/orBase.js
- test/plugins/builds.test.js
- test/plugins/trigger.helper.test.js
When an event is started from a frozen stage job, it again gets into frozen state.
This is because, when an event is started from a stage job, the stage `setup` is executed prior to executing the event origin job.
Pass the event `causeMessage` to the stage job build so that the executor can force start the build for the frozen stage job.
https://github.com/screwdriver-cd/screwdriver/issues/3242
> fix(3242): Unable to force start a frozen job that is part of a pipeline stage

- plugins/builds/steps/update.js
It is not possible to access the request payload for investigating the [steps/update API endpoint](https://github.com/screwdriver-cd/screwdriver/blob/9beed12ecae4cb08be5baeff895bf7b9efe6c186/plugins/builds/steps/update.js) 
To assist with troubleshooting, it would be helpful to log the payload using a logger. Additionally, having detailed logs would enable implementing log-based alerting.
https://github.com/screwdriver-cd/screwdriver/issues/3248
> feat(3248): log request payload for steps update endpoint

- plugins/builds/index.js
- plugins/builds/triggers/helpers.js
- test/plugins/data/trigger/sd@2:b_sd@2:c-downstream.yaml
- test/plugins/data/trigger/sd@2:b_sd@2:c-upstream.yaml
- test/plugins/trigger.test.js
A workflow containing a remote join may not trigger a build of the remote join if it is restarted from downstream.
Build succeeds downstream and remote join build is triggered upstream.
- upstream:
- downstream:
---
Upstream remote join is not triggered even if build succeeds after restarting from downstream.
- downstream:
- upstream:
---
This is due to a unique constraint error when creating a subsequent remote join build after a successful build restarted from a downstream, when trying to create in the restart source upstream event.
In the remote join workflow, when restarted from a downstream, create a new event on the upstream side and create a build on that event.
https://github.com/screwdriver-cd/screwdriver/issues/3133
I confirm that this contribution is made under a BSD license …
> fix(3133): upstream event creation when restarting remote join from downstream build

- package.json
- plugins/builds/helper/updateBuild.js
- plugins/builds/update.js
- plugins/events/create.js
- test/plugins/data/builds.json
- test/plugins/data/events.json
- test/plugins/events.test.js
Per changes made in https://github.com/screwdriver-cd/models/pull/635, virtual job builds at the beginning in the workflow for an event, may not be queued for execution. Status of such build will be set to `CREATED`.
Identify such build immediately after creating the event to mark its status as 'SUCCESS' and trigger its downstream jobs.
https://github.com/screwdriver-cd/screwdriver/issues/3181
> feat(3181): Skip execution of a virtual job when an event is started from that job

- plugins/builds/update.js
It is not possible to access the request payload for investigating the [builds/update API endpoint](https://github.com/screwdriver-cd/screwdriver/blob/36d3365e5ba59b5a6a905177c2f2b0389527c905/plugins/builds/update.js)
To assist with troubleshooting, it would be helpful to log the payload using a logger. Additionally, having detailed logs would enable implementing log-based alerting.
https://github.com/screwdriver-cd/screwdriver/issues/3248
> feat(3248): add logging in builds PUT to capture failure

- plugins/webhooks/helper.js
- test/plugins/webhooks.helper.test.js
If a user specifies a non-existent buildcluster for a job, models will return an error, but the API will return 500 because no status code is specified.
Also, even though models returns a detailed error, it does not output the error to the webhook, so the user cannot determine the cause of the error by looking at the webhook response.
Outputs a detailed error log to the webhook response
In addition, the status code set in the event of an error is specified in the webhook response.
Related: https://github.com/screwdriver-cd/models/pull/636
> fix: Show error details and change status code in case of webhook error [2]

- plugins/events/create.js
- test/plugins/events.test.js
When restart build was failed in `sd-setup-init` step and restart build from that build, meta is missing at that time.
So we fix this behavior by fetching parent event meta when creating event.
Fetch parent event meta when creating event.
#3225 
> fix(3235): Fetch parentEvent meta when create Event

- plugins/events/create.js
- plugins/events/helper/createEvent.js
- plugins/pipelines/startAll.js
- plugins/webhooks/helper.js
- test/plugins/pipelines.test.js
Changes made in the PR https://github.com/screwdriver-cd/screwdriver/pull/3252 introduced a regression. Virtual job builds at the beginning of the event workflow never got marked as completed (remain in `CREATED` state) when the event is created by SCM webhook. 
Mark virtual job builds at the beginning of the event workflow for all the scenarios.
https://github.com/screwdriver-cd/screwdriver/issues/3181
> fix(3181): Virtual builds not completed when triggered by webhook

- plugins/builds/update.js
- test/plugins/builds.test.js
A build pod with the same build ID may be launched twice.
See [this issue](https://github.com/screwdriver-cd/screwdriver/issues/3259) for detail.
Do not allow updating the build status to RUNNING if a build with the same ID is already running.
https://github.com/screwdriver-cd/screwdriver/issues/3259
> fix(3259): Add a function to prevent duplicate builds.

- features/pipeline-templates.feature
- features/step_definitions/pipeline-template.js
The pipeline template has an ignored scenario and is not well tested.
Activate a pipeline template scenario with`@ignore` tag and add new scenarios.
The following new branches are required for testing
- https://github.com/screwdriver-cd-test/functional-pipeline-template/pull/1
- https://github.com/screwdriver-cd-test/functional-pipeline-template/pull/2
- https://github.com/screwdriver-cd-test/functional-pipeline-template/pull/3
- https://github.com/screwdriver-cd-test/functional-pipeline-template/pull/4
> feat: Enables the ignored pipeline template test to be used [5]

- features/step_definitions/trigger.js
Making a remote join job a virtual job could cause the test to fail in functional test.
Allow virtual jobs to be used in functional test remote join jobs.
> fix: test of remote join acceleration by virtual job [3]

- plugins/builds/index.js
- plugins/builds/triggers/helpers.js
- plugins/builds/triggers/joinBase.js
- plugins/builds/triggers/orBase.js
- test/plugins/data/trigger/virtual-jobs-downstream.yaml
- test/plugins/data/trigger/virtual-jobs-upstream.yaml
- test/plugins/trigger.helper.test.js
- test/plugins/trigger.test.js
Handling for virtual jobs was added by https://github.com/screwdriver-cd/screwdriver/pull/3131 .
However, the virtual jobs are executed in remote triggers.
In remote trigger/join, [`isVirtual`](https://github.com/screwdriver-cd/screwdriver/blob/5a74c24e232a95a12d28e0ae7c4c3a5b25e6f872/plugins/builds/triggers/helpers.js#L905) is always `false` since the nodes of remote trigger does not have `virtual` property (ref. [here](https://github.com/screwdriver-cd/models/blob/7eac5d79e11620793ab8936cf6e06971a2c04eea/lib/pipeline.js#L1147-L1151)).
This PR gets the virtual info directly from the `job.annotations`.
> fix: handle virtual job properly in remote triggers

- plugins/pipelines/list.js
- test/plugins/pipelines.test.js
We are using `name` search to get sibling pipelines.
But it is not better.
Add the query `scmUri` for search pipelines to get sibling pipelines.
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/3284
> feat(3284): add scmUri param for search pipelines [1]

- features/metadata.feature
- features/step_definitions/metadata.js
- plugins/builds/triggers/helpers.js
- plugins/builds/triggers/joinBase.js
- plugins/builds/triggers/orBase.js
- test/plugins/trigger.helper.test.js
fix https://github.com/screwdriver-cd/screwdriver/issues/3287
Enable the metadata of the job immediately before the virtual job to take precedence over the event metadata.
The following PRs need to be merged first because functest is being added.
- https://github.com/screwdriver-cd-test/functional-metadata/pull/6
- https://github.com/screwdriver-cd-test/functional-metadata/pull/7
https://github.com/screwdriver-cd/screwdriver/issues/3287
https://github.com/screwdriver-cd/screwdriver/issues/3235
> fix(3287): Inherit the metadata of the job immediately before virtual job

- design/sd-build-cluster-selection.md
- plugins/pipelines/index.js
- plugins/pipelines/updateBuildCluster.js
- test/plugins/data/buildClusterInactive.json
- test/plugins/pipelines.test.js
As of now, if there is a need to make a change to build cluster, a manual db change for each pipeline has to be performed and this is not always possible since the DB might be protected with some limited access. 
This PR is to add a new endpoint to update a build cluster of a pipeline. 
https://github.com/screwdriver-cd/screwdriver/issues/3292
> feat(3292): New endpoint to update buildcluster of a pipeline

- plugins/webhooks/helper.js
If the pipeline admins is empty or if the admins account is suspended, then `Pipeline has no admin` error occurs when trying to create an event and get pipeline token in webhook process.
Add the webhook executor to admins before get pipeline token if webhook executor can be admin, so that the pipeline token does not generate errors in the above cases.
> fix: Prevent webhook pipeline has no admins

- plugins/banners/list.js
- test/plugins/banner.test.js
After https://github.com/screwdriver-cd/ui/pull/1326, the `isActive` parameter has been included in the request for `GET /banners` endpoint.
However, we cannot get banner list properly when we use MySQL since the value of `isActive` is string value on API side.
Convert the `isActive` parameter from string to boolean.
https://github.com/screwdriver-cd/screwdriver/issues/3277
> fix(3277): Convert string "true" value to boolean for MySQL on banner list endpoint

- plugins/webhooks/helper.js
- test/plugins/webhooks.helper.test.js
Empty events are created when the following case.
- Using source directory (e.g. `foo`)
- Commit/PR has a changed file that name matches the source directory (e.g. `foobar`, NOT `foo/bar`)
This PR will correct checking that changed files includes the files under source directory.
Ref:
- [checking before builds creation](https://github.com/screwdriver-cd/models/blob/3c515d63a2d7e52a25684e2ae93b552e204c90c2/lib/eventFactory.js#L224-L226)
- [source directory does not have trailing slashes](https://github.com/screwdriver-cd/screwdriver/blob/22967afca4701ea57064fcb5656b7c0eb65cde14/plugins/pipelines/helper.js#L30-L38)
> fix: skip event creation when there are changed files that name matches source directory

- package.json
- plugins/builds/index.js
- plugins/builds/triggers/helpers.js
- plugins/builds/triggers/joinBase.js
- plugins/builds/triggers/orBase.js
- test/plugins/builds.test.js
- test/plugins/trigger.helper.test.js
Workflow of upstream pipeline event was being used to determine if the external downstream job was virtual or not.
Use the event associated with the pipeline the job belongs to.
Also reverts few changes made in https://github.com/screwdriver-cd/screwdriver/pull/3283
Determining whether a job is virtual or not should be based on the event workflow and not on the latest job configuration (annotations). If we rely on latest job annotation, we may skip executing a build which not not marked as virtual when the event (parent event in case of restart) was created.
https://github.com/screwdriver-cd/screwdriver/issues/3310
> fix(3310): External trigger couldn't trigger a pipeline stage

- plugins/builds/helper/updateBuild.js
- plugins/builds/triggers/and.js
- plugins/builds/triggers/helpers.js
- plugins/builds/triggers/joinBase.js
- plugins/builds/triggers/orBase.js
- plugins/builds/triggers/remoteJoin.js
- plugins/jobs/buildCluster/update.js
- test/plugins/builds.test.js
- test/plugins/trigger.helper.test.js
Sometime, `parentBuildId` is not correct when parent builds are finished in same time.
For this reason, the build miss some metadata from the parent builds in launcher.
Likewise, virtual job cannot get some metadata from the parent builds.
https://github.com/screwdriver-cd/screwdriver/issues/3287#issuecomment-2674046847
- Update `parentBuildId` just before build execution
- Merge `metadata` from all of the parent builds into the virtual job just before build execution
Issue - https://github.com/screwdriver-cd/screwdriver/issues/3287#issuecomment-2674046847
> fix(3287): Set parentBuildId just before execution

- features/support/sdapi.js
Follow up https://github.com/screwdriver-cd/screwdriver/pull/3307 .
`parentBuildId` can be an array, so the current checking does not work if it is.
https://cd.screwdriver.cd/pipelines/1/builds/972603/steps/test
> fix: parentBuildId check in functest

- package.json
- plugins/pipelines/update.js
- test/plugins/data/collection.response.json
- test/plugins/data/pipeline.json
- test/plugins/data/pipelines.json
- test/plugins/data/pipelinesFromGitlab.json
- test/plugins/data/privatePipelines.json
- test/plugins/pipelines.test.js
Screwdriver restricts pipeline updates to admins within the same SCM context as the user’s login.
This PR relaxes the permission check, allowing admins from different SCM contexts to update the pipeline.
https://github.com/screwdriver-cd/screwdriver/issues/3304
Related PRs:
https://github.com/screwdriver-cd/data-schema/pull/595
> feat(3304): Relax permission check to allow admins from other SCMs to update pipeline

- plugins/builds/triggers/and.js
- test/plugins/builds.test.js
- test/plugins/trigger.test.helper.js
- test/plugins/trigger.test.js
This PR fixes some cases of the https://github.com/screwdriver-cd/screwdriver/issues/2957.
It corrects which event the next build should be triggered on in the following case:
```text
[ a, b, c ] is triggered in restarted event when a fails once and then restarts and succeeds before c succeeds
```
Find next build in the latest child event even if it is triggered from current event.
- Issue - https://github.com/screwdriver-cd/screwdriver/issues/2957
> fix(2957): trigger next build on the child event if some builds are restarted before complete all buidls

- lib/server.js
It will be useful for debugging to see the payload sent to API. 
This PR serves to add payload prior to logging the response to help troubleshooting. 
N/A
> feat: log request payload when available

- plugins/builds/create.js
- plugins/events/create.js
- plugins/events/index.js
- plugins/events/stopBuilds.js
- plugins/pipelines/sync.js
- plugins/webhooks/helper.js
- test/plugins/builds.test.js
- test/plugins/events.test.js
- test/plugins/webhooks.helper.test.js
https://github.com/screwdriver-cd/data-schema/pull/595 introduced a new field `adminUserIds` to identify pipeline admins based on the user identifier. 
Update `adminUserIds` based on user permission
https://github.com/screwdriver-cd/screwdriver/issues/3318
> feat(3318): Update pipeline admin user list based on the user permission

- plugins/builds/create.js
- plugins/events/index.js
- plugins/pipelines/sync.js
- plugins/pipelines/update.js
- plugins/webhooks/helper.js
If screwdriver using mysql 5.X, default value cannot be set in TEXT field.
Because of that, old pipelines have null adminUserIds column.
Check adminUserIds and set default value if a value is null.
https://github.com/screwdriver-cd/data-schema/pull/596
> fix: Add adminUserIds check for backward compatibility

- plugins/events/create.js
- plugins/pipelines/remove.js
- plugins/pipelines/sync.js
- plugins/pipelines/syncPRs.js
- plugins/pipelines/syncWebhooks.js
- plugins/pipelines/tokens/create.js
- plugins/pipelines/tokens/refresh.js
- plugins/pipelines/update.js
- plugins/pipelines/updateBuildCluster.js
- plugins/secrets/create.js
- test/plugins/events.test.js
- test/plugins/pipelines.test.js
- test/plugins/secrets.test.js
Pipeline related data is remaining after delete pipeline.
Details - https://github.com/screwdriver-cd/screwdriver/issues/3322
- Check the pipeline is not being deleted before start/update/etc... the pipeline.
Issue - https://github.com/screwdriver-cd/screwdriver/issues/3322
PRs
- [1] https://github.com/screwdriver-cd/data-schema/pull/598
- [2] https://github.com/screwdriver-cd/models/pull/644
> feat(3322): Add a DELETING state to the pipeline to block updates during the pipeline deletion [3]

- features/step_definitions/authorization.js
Follow up https://github.com/screwdriver-cd/screwdriver/pull/3330
Re-fix pipeline deletion in functional tests.
> fix(3322): stop builds before deleting pipeline in functional tests (part2)

- config/custom-environment-variables.yaml
- config/default.yaml
Because there is no `dialectOptions` property in the datastore config, 
we are currently unable to connect to the database via SSL.
This PR adds the `dialectOptions` property to the datastore config settings.
Issue: https://github.com/screwdriver-cd/screwdriver/issues/3339
Sequlize Docs: https://sequelize.org/docs/v6/other-topics/dialect-specific-things/
> fix (3339): Add dialectOptions settings for datastore conifg

- bin/server
follow up https://github.com/screwdriver-cd/screwdriver/pull/3321
In the previous fix, when a flag (true/false) was set in an environment variable, the value was of type string, so "false" was also equivalent to true.
Flags are correctly referenced as boolean types.
> fix: Can set log payload flag to false 

- bin/server
- config/custom-environment-variables.yaml
In the following PR, I added the `dialectOptions` property for establishing SSL connections to the database. 
https://github.com/screwdriver-cd/screwdriver/pull/3340
With this PR, I added a property to configure the CA certificate.
- Add `caCert` property to the configuration that specifies the CA certificate to be validated when connecting to the database via SSL
- Support for readOnly database connection
- The `dialectOptions` and `caCert` properties will be used in `datastore-sequelize` to connect to the database via SSL.
PR is here:
https://github.com/screwdriver-cd/datastore-sequelize/pull/101
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/3339
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution …
> [2] fix (3339): Add caCert property, and support for readOnly case

- plugins/events/create.js
There have been frequent 500 errors occurring during event creation.  
In some of these cases, improper error handling caused the default 500 status code to be returned.  
This PR improves error handling in the functions involved in event creation.
- Modified the call to updateAdmins to use a try-catch block
- Improved error handling during event creation by replacing .catch() with try-catch 
- The reason is that .catch() only handles cases where a Promise is explicitly rejected.
If an exception is thrown inside the called function, it may not be properly caught. 
- https://hapi.dev/api/?v=21.4.0
> Any error thrown by a lifecycle method is converted into a boom object and defaults to status code 500 if the error is not already a boom object.
I confirm that this contribution is made under …
> fix: Improve error handling in functions triggered by event creation

- plugins/builds/helper/updateBuild.js
Follow up https://github.com/screwdriver-cd/screwdriver/pull/3352 .
In PR workflow, some jobs are not created since these are not in PR workflow.
This PR adds checking job existence.
Issue - https://github.com/screwdriver-cd/screwdriver/issues/3043
> fix(3043): teardown job is not triggered in PR

- plugins/builds/helper/updateBuild.js
- plugins/builds/triggers/helpers.js
- plugins/builds/triggers/orBase.js
- test/plugins/builds.test.js
- test/plugins/trigger.helper.test.js
- test/plugins/trigger.test.helper.js
- test/plugins/trigger.test.js
Stage teardown build's commit status does not updated from `pending` to `success` when that stage has some failed builds or has not triggered build.
This is always happened in PR stage case because only child jobs of the stage setup are triggered and others are not triggered in PR stage.
- Add handling for virtual teardown job that triggered in non-completed stage
- Use `build.initMeta()` introduced by https://github.com/screwdriver-cd/models/pull/647
- Issue - https://github.com/screwdriver-cd/screwdriver/issues/3043
- Similar fix - https://github.com/screwdriver-cd/models/pull/632
> fix(3043): commit status for virtual teardown job always shows pending when the stage does not complete succeed

- plugins/webhooks/helper.js
- test/plugins/webhooks.helper.test.js
Currently, branch specific triggers on pr-closed is only triggered a pipeline has also `~pr-closed` and `~pr:{branch}` triggers.
I fixed this behavior and correctly triggered branch specific triggers without define `~pr-closed` and `~pr:{branch}` job.
- When pr-closed event is occurred, start from is not correctly determined. I fixed determineStartFrom logic for pr-closed event.
- When filtering pr-closed jobs, it is not considered on branch specific trigger. I fixed filtering criteria to account for branch-specific triggers.
> fix: Correctly triggered branch specific triggers on pr-closed

- config/custom-environment-variables.yaml
- config/default.yaml
- lib/server.js
- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
Webhook currently does not support configuration for multiple scm repo which is needed for running github enterprise and cloud
This PR adds logic to update configuration to support multiple scms
> feat: configure webhook settings based on scm

- package.json
- plugins/pipelines/admins/get.js
- test/plugins/pipelines.test.js
The current endpoint `/pipelines/{id}/admin` returns an admin for a pipeline where the admin user is from the same SCM context as that of the pipeline.
Update the endpoint to find admin for a pipeline where the admin user SCM context is different pipeline SCM context.
SCM context is passed via the query param `scmContext`
https://github.com/screwdriver-cd/screwdriver/issues/3363
> feat(3363): Update the existing endpoint to get admin for a pipeline from the specified SCM context

- plugins/pipelines/caches/delete.js
Users with `push` permission to the pipeline repo are not allowed to delete pipeline/job cache.
Only the users with `admin` permission to the pipeline repo are allowed to do so.
Relax the permission check in the below endpoint to allow users with `push` permissions (not admin on the repo) to delete cache. 
```
method: 'DELETE',
path: '/pipelines/{id}/caches',
```
https://github.com/screwdriver-cd/screwdriver/issues/3375
> feat(3375): Allow users with push permission to delete pipeline or job cache

- plugins/pipelines/update.js
- test/plugins/pipelines.test.js
The pipeline PUT endpoint supports configuring badges; however, the endpoint does not support removing a configured badge for a pipeline.
Add support to remove a badge with a payload of:
```
badges: {
[service-name]: {}
}
```
https://github.com/screwdriver-cd/screwdriver/issues/3367
> fix(3367): Add support for removing badges

- features/restrict-pr.feature
- features/step_definitions/pipeline-template.js
- features/step_definitions/restrict-pr.js
- features/step_definitions/sd-cmd.js
- features/step_definitions/templates.js
- features/support/world.js
Some feature tests currently use a hardcoded organization name.
- Make it possible to retrieve the organization name from an environment variable
- Specifically, allow the restrict-pr test to use a configurable org name via an environment variable, such as for forks
> fix: Enable environment variable for org name in feature tests

- features/git-flow.feature
- features/step_definitions/git-flow.js
The builds triggered from tag/release have special metadata such as `sd.tag.name`.
We should test that these metadata is prepared properly.
The following PR will add test for the metadata for tag/release.
https://github.com/screwdriver-cd-test/functional-git/pull/11766
This PR add checking that builds are succeed.
- Issue - https://github.com/screwdriver-cd/screwdriver/issues/3235
- PRs
- https://github.com/screwdriver-cd-test/functional-git/pull/11766
- https://github.com/screwdriver-cd/launcher/pull/493
> feat(3235): check tag/release test build status in feature tests [2]

- features/git-flow.feature
- features/step_definitions/git-flow.js
PR closed trigger is available now. We need to test this feature in the acceptance test.
This PR requires the following PR for the test repository.
https://github.com/screwdriver-cd-test/functional-git/pull/11776
After merging that PR, please create a `pr-closed-trigger` branch on that repository.
- Create acceptance tests for PR closed trigger
- PR - https://github.com/screwdriver-cd-test/functional-git/pull/11776
> feat: create acceptance tests for PR closed trigger [2]

- plugins/builds/helper/updateBuild.js
- plugins/events/stopBuilds.js
- test/plugins/data/trigger/sd@2:a-upstream-b.yaml
- test/plugins/data/trigger/stage-explicit-setup-teardown-b.yaml
- test/plugins/events.test.js
- test/plugins/trigger.test.js
When you press the stop button on the event card to stop the event, all builds are set to `ABORTED`, and normally all builds are expected to stop at that point.
However, due to synchronisation issues, if you stop event just before the build is complete, a new build is triggered after pressing stop, and the build does not actually stop and the event will continue to be held.
This occurs particularly when there are a large number of builds or when there are virtual jobs or stages.
In addition, remote join starts from downstream after the event is stopped, but it is not intuitive that the build can start after the event is stopped.
Make it possible to determine whether the event has been stopped by using the statusMessage when the event is stopped.
Fix details
- All builds (even if triggered …
> fix: Stop all builds when the event is stopped

- features/sd-setup-scm.feature
Running the `Normal build` and `External config build` scenarios in parallel can lead to failures, as new commits may be added during the execution of the `Normal build` tests.
(Example: https://beta.cd.screwdriver.cd/pipelines/19904/builds/220243/steps/teardown-test-sha)
To address this, the two scenarios are moved to different parallel groups, which resolves the flaky test issue.
This order of execution causes a mismatch between the event SHA and the latest SHA, resulting in a failure of the branch job.
1. [Given having two commit before an hour](https://github.com/screwdriver-cd/screwdriver/blob/d0d27531aef1eb5a48b2aba7da50cfb47dd5e745/features/sd-setup-scm.feature#L11)
2. [When start "~commit" job](https://github.com/screwdriver-cd/screwdriver/blob/d0d27531aef1eb5a48b2aba7da50cfb47dd5e …
> fix: Run sd-setup-scm acceptance tests in a different parallel group

- plugins/pipelines/batchUpdateAdmins.js
- plugins/pipelines/helper/updateAdmins.js
- plugins/pipelines/updateAdmins.js
- test/plugins/pipelines.test.js
https://github.com/screwdriver-cd/screwdriver/issues/3347 added a new endpoints which allowed cluster admins to add users from a different SCM context as admins for a pipeline.
```
/pipelines/{id}/updateAdmins
/pipelines/updateAdmins
```
Allow pipeline repo admins to add users from a different SCM context as admins for a pipeline.
These newly added users will have limited privileges. They can only switch the pipeline to a repository in the scm they belong to.
https://github.com/screwdriver-cd/screwdriver/issues/3401
> feat(3401): Allow pipeline repo admins to add users from a different SCM context as admins for a pipeline

- plugins/webhooks/index.js
- test/plugins/webhooks.test.js
The maximum payload size for webhooks was always falling back to the default value instead of respecting the custom value provided in the configuration.
`pluginOptions` contains the settings from `webhook.scms`, but since `maxBytes` is defined directly under `webhook`, it cannot be accessed via `pluginOptions.maxBytes`.
I will fix it so that `maxBytes` is referenced directly from `options`.
> fix: the payload size limit for webhooks reverts to the default value

- plugins/builds/index.js
- plugins/builds/triggers/helpers.js
- test/plugins/builds.test.js
- test/plugins/data/trigger/a_b.yaml
- test/plugins/data/trigger/sd@2:a_sd@2:b-downstream.yaml
- test/plugins/trigger.test.helper.js
- test/plugins/trigger.test.js
Remote join is not triggered when restart the downstream build by "Start pipeline from here".
Trigger remote join even use "Start pipeline from here".
- Issue - https://github.com/screwdriver-cd/screwdriver/issues/3408
> fix(3408): remote join is not triggered properly when restart the downstream build by "Start pipeline from here"

- plugins/builds/index.js
- test/plugins/builds.test.js
If trigger processing for downstream events in the same pipeline runs simultaneously, builds may be created for separate events.
Acquire a lock using the downstream pipeline ID and groupEventID to ensure external event creation processes execute sequentially.
> fix: Make the event creation process in the downstream pipeline sequential

- features/sd-setup-scm.feature
There are no functional tests for recursive cloning.
Add a test scenario for environment variables related to sd-setup-scm provided by screwdriver.
This change tests whether submodules can be recursively cloned and shallowly cloned.
Environment variables:
- GIT_RECURSIVE_CLONE
This change relates to the following PR
- https://github.com/screwdriver-cd/scm-github/pull/251
The following PR adds the test contents.
The test will fail because there are no jobs until the following PR is merged.
- https://github.com/screwdriver-cd-test/functional-sd-setup-scm/pull/190
> feat: Add tests for GIT_RECURSIVE_CLONE env [2]
